### PR TITLE
Toggle Properties Panel Errors When Toggling Error Panel

### PR DESCRIPTION
**Pull request by philippfromme**
Notable changes:

* all lint errors are shown in the properties panel
* toggling the error panel toggles the properties panel errors
* property panel errors are shorter versions of errors from error panel

Note that there is a lot of lining logic in the editor right now. This will likely change in the context of adding annotations to the canvas (cf. https://github.com/philippfromme/linting-playground).

electron_ajWsrhsJ9j

---

Requires https://github.com/bpmn-io/properties-panel/pull/160
Requires https://github.com/bpmn-io/bpmn-js-properties-panel/pull/716
Requires https://github.com/camunda/linting/pull/7

### CODE REVIEW

**Comment by philippfromme** [comment]
For some reason, the macOS checks won't run. 😢 They are cancelled immediately.

**Comment by pinussilvestrus** [comment]
After #3045, a rebase should make CI happy again.

**Comment by philippfromme** [comment]
> One little thing to consider: I see a pretty nice example for a bunch of linting errors in the attached screencast. Should we maybe add this file to the project fixtures? It would maybe make it easier to test the whole linting feature.

You mean an example diagram that produces these lint errors?

**Comment by pinussilvestrus** [comment]
Yes.

**Comment by philippfromme** [comment]
@pinussilvestrus I will include an example diagram. 👍🏻

**Comment by philippfromme** [comment]
I added an example diagram: https://github.com/camunda/camunda-modeler/pull/3014/commits/7cac249aed49df640258a726b892d1f90324f267

**Pull request merged**
