### PR TITLE
chore(TEMPLATES): add release to issue templates

### PR DESCRIPTION
**Pull request by marstamm**
Adds the Release checklist as a issue template 

required by https://github.com/bpmn-io/fake-join/pull/42

### CODE REVIEW

**Review by philippfromme — APPROVED** [review]
✅

**Comment by nikku** [comment]
I'm a little bit worried that this deters our users from picking the right issue: 

image

How was this a requirement for the issue creation bot to work?

**Comment by marstamm** [comment]
We needed the markdown as a template. Not neccesasarily having it as an issue template, I just thought this would be a nice side effect.

**Comment by marstamm** [comment]
We can move it to `docs/.project` as well

**Comment by nikku** [comment]
Let's move it to `docs/.project`. It is nothing a user would ever want to do, hence I'd not add it to our public inteface.

**Comment by nikku** [comment]
Created https://github.com/camunda/camunda-modeler/issues/3087 as a follow-up.

**Pull request merged**
