### PR TITLE
Linux Integration: Create a menu item and associate files

### PR DESCRIPTION
**Pull request by falko**
Add shell scripts that register a *.desktop file, icons and mime types.
They use the xdg-utils from https://www.freedesktop.org/ to do that in a standardized way that is supported by all major Linux desktop environments.
A script for removing the changes is provided as well.

After running the script, the Camunda Modeler can be easily associated as the default editor for *.bpmn, *.cmmn and *.dmn files in Eclipse.

I'm not sure in which directory these files should go in order to appear in the distro. Also you might want to adjust the paths, because I use this one level above the unpacked modeler and because you may not want all the files in the root directory.

### CODE REVIEW

**Comment by ricardomatias** [comment]
Someone else should review this, I'm using arch linux so I cannot test this end-to-end.

**Comment by falko** [comment]
@ricardomatias depending on the desktop environment your Arch Linux might also follow the XDG Standard: https://wiki.archlinux.org/index.php/default_applications#XDG_standard

**Comment by pedesen** [comment]
Thanks for the pull request, Falko. I tested it with Linux Mint. Register and unregister file associations and integration in the menu are working well.

There are some further steps I will take care of:
* moving the scripts to `resources/platform/linux/support` (the scripts will then be copied to the distribution package)
* adjust the paths
* renaming them (maybe `register.sh` / `unregister.sh`)
* adding some documentation

**Comment by nikku** [comment]
Merged via https://github.com/camunda/camunda-modeler/commit/3a4509099859cc75c8384e925b64f6babd80614b, thanks!

**Pull request closed without merging**
