### PR TITLE
Rename to C7/C8 in profile selection

### PR DESCRIPTION
**Pull request by smbea**
Related to https://github.com/bpmn-io/internal-docs/issues/481

This PR doesn't handle the addition of the DMN select or the addition of "Zeebe" in the older select options and status bar - see https://github.com/bpmn-io/internal-docs/issues/490

Artifacts:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-engine-select/camunda-modeler-rename-c7-c8-engine-select-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-engine-select/camunda-modeler-rename-c7-c8-engine-select-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-engine-select/camunda-modeler-rename-c7-c8-engine-select-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-engine-select/camunda-modeler-rename-c7-c8-engine-select-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-engine-select/camunda-modeler-rename-c7-c8-engine-select-win-x64.zip

### CODE REVIEW

**Comment by MaxTru** [comment]
Would it not make sense to bump linting-compat module as part of this so to also have 7.17 and 8.0 versions included?

**Comment by smbea** [comment]
@MaxTru There is already a seperate issue to track that - https://github.com/camunda/camunda-modeler/issues/2736 but I guess I can merge everything here after the release

**Review by MaxTru — APPROVED** [review]
lgtm

**Review by andreasgeier — APPROVED** [review]
I can only approve this on the condition that we will add the Zeebe label before the release. Currently, `Camunda Platform 1.x` in the status bar is just wrong.

**Comment by MaxTru** [comment]
> I can only approve this on the condition that we will add the Zeebe label before the release. Currently, `Camunda Platform 1.x` in the status bar is just wrong.

We will kick that off on Monday

**Pull request merged**
