### PR TITLE
feat: migrate to `codemirror@6`

### LINKED ISSUE #2923: Highlight in XML opage didn't match the text
__Describe the Bug__

When I try to highlight some text in the XML view of a process model, on some lanes the highlight didn't match the text.

__Steps to Reproduce__

1. model some elements
2. switch to the XML view
3. mark a line in the text with the mouse

__Expected Behavior__

The text is exactly marked.

But it isn't, as you can see in the screenshot:
grafik

It seems to depend on the line you want to mark with the mouse. On some lines it matches the text, on some it doesn't match.

__Environment__

Camunda Modeler system information
 * Version: 5.0.0
 * Operating System: Windows 10 amd64
 * Plugins: Cloud Connect, Migration, bpmn-js Token Simulation, BPMN Linter, Transaction Boundaries, Camunda Property Infos, Tooltip Plugin
 * Execution Platform: BPMN - Camunda Platform 7

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #2923

----

This updates the CodeMirror editors to the latest library version (`v6`). I used the [Form Playground JSON editor](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-playground/src/components/JSONEditor.js) + [FEEL Editor](https://github.com/bpmn-io/feel-editor/) as a blueprint.

_XML Editor_

image

_JSON Editor_

image

__Beforehand__
image

**It includes the following changes:**
* Update editor creation to new CodeMirror architecture
* Replace API with new CodeMirror command architecture
* ==> Everything should work the same as beforehand

**Known issues/up for discussion:**
* <del>The styles are different from the old version. Since we didn't use any particular theme, I simply used the default. We can still style if we want to.</del> (cf. https://github.com/camunda/camunda-modeler/pull/3103#issuecomment-1220765914)
* <del>The search bar is way more advanced than the old version. We can consider ditching some functions (probably via CSS).</del> (cf. https://github.com/camunda/camunda-modeler/pull/3103#issuecomment-1220765914)
* The `autoCloseTags` option is gone in CodeMirror 6, but autocomplete is enabled per default. It's up to the language packages to implement such a behavior
  * https://github.com/codemirror/lang-xml and https://github.com/codemirror/lang-json don't have a `autoCloseTags` option so far
* I didn't look into bringing both `CodeMirror` components together into one component, as spring cleaning is coming to an end. We can still consider it later.  
  
**Build artifacts:**

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2923-migrate-code-mirror/camunda-modeler-2923-migrate-code-mirror-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2923-migrate-code-mirror/camunda-modeler-2923-migrate-code-mirror-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2923-migrate-code-mirror/camunda-modeler-2923-migrate-code-mirror-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2923-migrate-code-mirror/camunda-modeler-2923-migrate-code-mirror-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2923-migrate-code-mirror/camunda-modeler-2923-migrate-code-mirror-win-x64.zip

**Helpful links I used to migrate:**
* https://codemirror.net/docs/migration/
* https://codemirror.net/docs/ref
* https://discuss.codemirror.net/c/v6

### CODE REVIEW

**Comment by christian-konrad** [comment]
@pinussilvestrus before merging, I would expect us to do 3 things:
- Apply our styles on the search+replace bar (btw. new bar is function-wise way better then the previous) 
Bildschirmfoto 2022-08-19 um 16 45 20
Hack:

```css
.cm-editor .cm-button {
    background: transparent;
    font-family: var(--font-family);
    font-weight: 500;
    border-radius: 2px;
    height: 28px;
    padding: 4px 14px;
    color: var(--color-grey-225-10-15);
    border: solid 1px var(--color-grey-225-10-75);
    background-color: var(--color-grey-225-10-95);
    text-transform: capitalize;
}

.cm-editor .cm-textfield {
    padding: 4px 8px;
    font-family: var(--font-family-monospace);
    font-size: 13px;
    height: 28px;
}

.cm-editor .cm-panel.cm-search label {
    font-size: 13px;
    font-family: var(--font-family);
    display: inline-flex;
    gap: 4px;
    line-height: 20px;
    text-transform: capitalize;
}

.cm-editor .cm-panel.cm-search [name=close] {
    font-size: 24px;
    padding: 0px 8px; 
}
```

- Apply same font size as in properties panel (14px)
- Apply another syntax highlighting color set for both XML and JSON, probably the same as for FEEL:
Bildschirmfoto 2022-08-19 um 16 30 17
(As someone with slight color blindness, I must say the greens and reds in the new one are hard to distinguish)

**Comment by pinussilvestrus** [comment]
+1 on aligning the styles (via custom theme or simply via CSS). 👍 I can apply the changes next week.

**Comment by pinussilvestrus** [comment]
I pushed the changes you proposed. I took the easy way and simply themed the editors via CSS to not mix code and theming. 

The builds and screenshots above are updated, so feel free to have another look.

**Review by nikku — CHANGES_REQUESTED** [review]
Let's perform the following minor additional changes:

* Set placeholder to modeler font (currently monospace)
* Apply minimal border radius (to match input look)
* vertically middle align check boxes + labels + buttons

**Comment by pinussilvestrus** [comment]
Adjusted accordingly: 

**Old**
image


**New**

image

**Review by nikku — APPROVED** [review]

**Pull request merged**
