### PR TITLE
chore: bump form-js deps

### PR DESCRIPTION
**Pull request by vsgoulart**
### Proposed Changes

 

Bump to `form-js@1.13.0` ([CHANGELOG](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js/CHANGELOG.md#1130)) together with the helper deps

### Checklist

To ensure you provided everything we need to look at your PR:

* [ ] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
I am looking into this today.

**Comment by barmac** [comment]
One thing in which you and @camunda/hto-frontend could support us great would be to provide the changelog update together with the deps update PR: https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#forms
I will do it myself now, but please keep it in mind for smooth collaboration :)

**Comment by barmac** [comment]
Done via https://github.com/camunda/camunda-modeler/pull/4757/commits/dd88de4398824a5a63d4fe49747d70b4e7d164d6
When merging, I will update the commit message to `deps` as this is how we mark production deps updates.

**Comment by barmac** [comment]
The documentation link should point to a specific page, not the home page:
image

Do you have a documentation page already? If not, we could also agree on a specific permalink if you commit that the page will be provided at the release date.

**Comment by barmac** [comment]
Overall, I think the tooltips are not enough to efficiently use the feature. I think a documentation page is a must.

**Comment by vsgoulart** [comment]
@barmac I'll use this URL `https://docs.camunda.io/docs/next/components/modeler/forms/form-element-library/forms-element-library-document-preview/` but it doesn't exist yet.

I'll just change it on `form-js` and then create a PR on the docs later today

**Comment by vsgoulart** [comment]
@barmac  Fixed the docs issue and bumped the deps via https://github.com/camunda/camunda-modeler/pull/4757/commits/43b2157498cc47b368f2c226b026bf6438edeabb
You can check the changelog [here](https://github.com/bpmn-io/form-js/commit/3aedec8abac33c8ba72dcfcd6d0af989a052349c)

**Comment by barmac** [comment]
I am merging this with promise of this link being available `https://docs.camunda.io/docs/next/components/modeler/forms/form-element-library/forms-element-library-document-preview/`. Do you have a docs PR with the page?

**Comment by vsgoulart** [comment]
> I am merging this with promise of this link being available `https://docs.camunda.io/docs/next/components/modeler/forms/form-element-library/forms-element-library-document-preview/`. Do you have a docs PR with the page?

I'll create it today by the end of the day

**Comment by vsgoulart** [comment]
@barmac Docs PR are here: https://github.com/camunda/camunda-docs/pull/4773

**Pull request merged**
