### PR TITLE
deps: update to dmn-js@11.1.2

### PR DESCRIPTION
**Pull request by barmac**

### CODE REVIEW

**Review by MaxTru — CHANGES_REQUESTED** [review]
This breaks the DMN editor for me in Camunda Modeler...


Try:
1. Open DMN diagram
2. Drill into Decision Table or literal expression
3. Edit stuff
4. Go back to DRD overview
5. This happens=>
```
[diagram_1.dmn] Cannot read property 'ids' of undefined
    at isIdValid (webpack-internal:///./node_modules/dmn-js-properties-panel/lib/Utils.js:156:28)
    at Object.validate (webpack-internal:///./node_modules/dmn-js-properties-panel/lib/provider/dmn/parts/IdProps.js:34:77)
    at Object.defaultParameters.validate (webpack-internal:///./node_modules/dmn-js-properties-panel/lib/factory/ValidationAwareTextInput.js:52:20)
    at PropertiesPanel.validate (webpack-internal:///./node_modules/dmn-js-properties-panel/lib/PropertiesPanel.js:807:37)
    at eval (webpack-internal:///./node_modules/dmn-js-properties-panel/lib/PropertiesPanel.js:1024:14)
    at arrayEach (webpack-internal:///./node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///./node_modules/lodash/forEach.js:38:10)
    at eval (webpack-internal:///./node_modules/dmn-js-properties-panel/lib/PropertiesPanel.js:982:60)
    at arrayEach (webpack-internal:///./node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///./node_modules/lodash/forEach.js:38:10) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
```

**Comment by barmac** [comment]
I am able to reproduce this. Thanks for reporting.

**Comment by barmac** [comment]
The error originates in a place where we try to validate the ID of the implicit root:
image

I will need to release another version of dmn-js to fix that.

**Comment by barmac** [comment]
The error has been already fixed but we haven't updated `dmn-js-properties-panel` 🙈

**Comment by barmac** [comment]
As there are some pending changes in `dmn-js-properties-panel`, I will release a new version and integrate it here.

**Comment by barmac** [comment]
@MaxTru @Skaiir It's ready for review.

**Comment by MaxTru** [comment]
Works now - approved

**Review by MaxTru — APPROVED** [review]

**Pull request merged**
