### PR TITLE
Feature - Deploy all files within a folder

### LINKED ISSUE #880: Deploy all files within a folder or same folder as BPMN - REST API Deployment
Similar to the use case of https://github.com/StephenOTT/camunda-deployment-maven-plugin where the plugin will grab all files within the defined folder and upload these as part of the deployment, it would be great to have the same feature as part of the Modeler deployment function:
You are often deploying many files, BPMN, script files, templates, CMMN, DMN, etc, all part of the same deployment.

Thanks

### PR DESCRIPTION
**Pull request by Ichigo85**
Good morning,
This branch makes possible to deploy an additional directory content to a Camunda engine. On deployment modal there is a new button to add a directory to the content. Every file inside the directory added is uploaded as part of the same deployment.
I already provided test cases for file-system and app classes.

Closes #880

### CODE REVIEW

**Comment by nikku** [comment]
Could you rebase your branch onto the latest development branch and share a screenshot of how your contribution looks like?

**Comment by Ichigo85** [comment]
Hi @nikku  :) I rebased my branch now. Here is a screenshot of the modal.
Screenshot_2020-01-22_14-59-52

**Comment by nikku** [comment]
First of all, thanks for your contribution!

As it is a bigger one we carefully need to decide if and to which extend we can integrate this into the tool. I'll hand this over to product management to decide if we'd like to have such functionality in the modeler. 

We will get back to you.

**Comment by nikku** [comment]
We've discussed this issue internally. Two results: 

We are going to work on this topic in Q2/Q3 so https://github.com/camunda/camunda-modeler/issues/880 will be addressed some day, eventually.

Given that timeline we decided not to accept your contribution (https://github.com/camunda/camunda-modeler/pull/1666) right now but consider all aspects, including an appropriate UI/UX later this year. Hope this makes sense.

**Pull request closed without merging**
