### PR TITLE
feat(app): set user path via flag

### LINKED ISSUE #1625: It should be possible to configure userData directory via flag
__Is your feature request related to a problem? Please describe.__

Currently, we use the default `userData` directory for each operating system as our [search-paths](https://github.com/camunda/camunda-modeler/tree/develop/docs/search-paths). This is not giving us the flexibility to offer custom directories, e.g. to use the app in integration testing with plugins. With the option to edit the `userData` path it would be possible to start Camunda Modeler instances without depending on the user's configuration and with a cleared setup.

__Describe the solution you'd like__

It should be possible to configure the `userData` path via flag, e.g. `--user-path='any/foo/path'`

__Describe alternatives you've considered__

/

__Additional context__

* [`electron#setPath`](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetpathname-path)

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Adds options to set user path via '--user-path' flag

Example: ./'Camunda Modeler' --user-path="/Users/foo/camunda-modeler"

Closes #1625

### CODE REVIEW

**Comment by nikku** [comment]
What does user path refer to here? Is it the path to the user directory that contains the actual app data or is it the app data path? The name confuses me slightly.

**Comment by nikku** [comment]
In chromium this thing is called `user-data-dir`:

```
       --user-data-dir=DIR
              Specifies  the  directory  that user data (your "profile") is kept in.  Defaults to $HOME/.config/chromium .  Separate instances of Chromium must use separate user
              data directories; repeated invocations of chromium will reuse an existing process for a given user data directory.
```

**Comment by pinussilvestrus** [comment]
It indicates the `userData` path, so 

> path to the user directory that contains the actual app data

Let's rename the flag to make it clearer. I like ` --user-data-dir`. Is that also something we should update the [`search path docs`](https://github.com/camunda/camunda-modeler/tree/develop/docs/search-paths) for? Maybe not as it's nothing we should publicly advertise (like the node-integration flag).

**Comment by nikku** [comment]
Let's add it to the search path documentation. It is not something that we actively discourage users from using.

**Comment by pinussilvestrus** [comment]
I also updated the `flags` documentation to have it as a table. The example json doesn't reflect the way to configure the application via CLI.

@oguzeroglu it's ready to review now.

**Comment by oguzeroglu** [comment]
LGTM. Looked for some tests but it seems like we don't really test any of our custom flags specifically.

**Pull request merged**
