### PR TITLE
chore(docs): improve release issue template

### PR DESCRIPTION
**Pull request by philippfromme**
An attempt at making the timeline of a release more clear to the release manager.

### CODE REVIEW

**Comment by philippfromme** [comment]
> I find the `Leading up to freeze day` concept a bit confusing. Considering:
> 
> 1. We merge master to develop 'leading up to freeze day', isn't that something we're supposed to do on the day of the release?
> 2. Same for the semantic release step
> 
> Before the release day we can still push stuff to master&develop? In that case we need to merge again on the release day.
> 
> Does it make sense to you?

You mean _Leading up to Release Day?_ These activities are supposed to happen on or after Code Freeze. I'll make this more clear.

**Comment by philippfromme** [comment]
@oguzeroglu Can you have a look again? I've also removed the headings based on feedback from @nikku.

**Comment by barmac** [comment]
LGTM

**Comment by nikku** [comment]
We have two more release infos ([patch release](https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/PATCH_RELEASE.md) / [alpha release](https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/ALPHA_RELEASE.md)), plus we got shortcuts to create these with a single click. 

image

Do you mind changing those, too?

**Comment by philippfromme** [comment]
Yes, will do. This PR was supposed to verify the general direction. Will adjust to remaining things.

**Comment by philippfromme** [comment]
Done.

I updated:

https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/RELEASE.md

https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/ALPHA_RELEASE.md

https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/PATCH_RELEASE.md

**Comment by nikku** [comment]
Really good work :clap:

**Comment by philippfromme** [comment]
Just putting on some support wheels for me basically. 😃

**Pull request merged**
