### PR TITLE
test(app): add coverage reporting

### PR DESCRIPTION
**Pull request by nikku**
This PR adds coverage for the `app` part of the Camunda Modeler, too.

Need to check back with CI, if reporting works.

### CODE REVIEW

**Comment by barmac** [comment]
It seems like appveyor build failed for no relevant reason. Do you know if there is a `restart build` button in this CI tool?

**Comment by nikku** [comment]
You should be able to restart it right in the tool, once you logged in via GitHub.

**Comment by nikku** [comment]
It does not get better after re-starting the build. Seems like the NPM registry has issues (HTTP 500 is returned).

**Comment by barmac** [comment]
Previously, it complained about "cannot copy some-dir/package.json". Anyway, let's monitor https://status.npmjs.org/

Regarding the build restart, I can't find the button 🙄.
screenshot 2019-01-24 at 10 12 59

**Comment by nikku** [comment]
Merged via https://github.com/camunda/camunda-modeler/commit/e5d2ceb355ec803244948682ffb2ad6cf5576d25. We'll need to see how this performs in practice and adjust accordingly.

**Pull request closed without merging**
