### PR TITLE
Update dependencies 4.12.0

### PR DESCRIPTION
**Pull request by smbea**
Related to #2583

### CODE REVIEW

**Comment by MaxTru** [comment]
This is missing: https://github.com/bpmn-io/bpmn-properties-panel/commit/1d151365a28ea872ac10d3ad48f5f7102826b5d9

**Review by MaxTru — CHANGES_REQUESTED** [review]
We miss this reverted change:
https://github.com/bpmn-io/bpmn-properties-panel/commit/1d151365a28ea872ac10d3ad48f5f7102826b5d9

**Comment by smbea** [comment]
The commit was released with bpmn-properties-panel v5.2 and integrated here

**Comment by smbea** [comment]
I will add the missing commits (related to the engines) on a separate PR

**Review by MaxTru — APPROVED** [review]

**Pull request merged**
