### PR TITLE
Feature: Set correct permissions to files and directories

### LINKED ISSUE #2439: Very relaxed file permissions in Linux distribution tarball
__Describe the Bug__

When extracting the Linux tarball distribution it has very relaxed file permissions.

There is Read, Write and Execution permission for all files and folder.

__Steps to Reproduce__

Doing a listing of files and folders in the shell will show that the file permissions are very relaxed.

1. Navigate to the place where you want to extract the Linux tarball: `cd /opt/camunda`
2. Extract the Linux tarball distribution in a folder: `sudo tar -xzvf ~/Download/camunda-modeler-4.8.1-linux-x64.tar.gz`
3. List files to check file permissions: `ln -la .`

```bash
drwxrwxrwx 6 root root      4096 mai   12 13:39 .
drwxr-xr-x 4 root root      4096 sep.  23 20:30 ..
-rwxrwxrwx 1 root root 136615040 mai   12 13:39 camunda-modeler
-rwxrwxrwx 1 root root    126787 mai   12 13:39 chrome_100_percent.pak
-rwxrwxrwx 1 root root    189438 mai   12 13:39 chrome_200_percent.pak
-rwxrwxrwx 1 root root   4708288 mai   12 13:39 chrome-sandbox
-rwxrwxrwx 1 root root  10412752 mai   12 13:39 icudtl.dat
-rwxrwxrwx 1 root root    242528 mai   12 13:39 libEGL.so
-rwxrwxrwx 1 root root   3064624 mai   12 13:39 libffmpeg.so
-rwxrwxrwx 1 root root   7263376 mai   12 13:39 libGLESv2.so
-rwxrwxrwx 1 root root   4042184 mai   12 13:39 libvk_swiftshader.so
-rwxrwxrwx 1 root root   6720648 mai   12 13:39 libvulkan.so.1
-rwxrwxrwx 1 root root      1095 mai   12 13:39 LICENSE.camunda-modeler.txt
-rwxrwxrwx 1 root root      1060 mai   12 13:39 LICENSE.electron.txt
-rwxrwxrwx 1 root root   4978855 mai   12 13:39 LICENSES.chromium.html
drwxrwxrwx 2 root root      4096 mai   12 13:39 locales
drwxrwxrwx 3 root root      4096 sep.  23 20:31 resources
-rwxrwxrwx 1 root root   5148619 mai   12 13:39 resources.pak
-rwxrwxrwx 1 root root     47955 mai   12 13:39 snapshot_blob.bin
drwxrwxrwx 2 root root      4096 mai   12 13:39 support
drwxrwxrwx 2 root root      4096 mai   12 13:39 swiftshader
-rwxrwxrwx 1 root root    538485 mai   12 13:39 THIRD_PARTY_NOTICES.camunda-modeler.txt
-rwxrwxrwx 1 root root    164759 mai   12 13:39 v8_context_snapshot.bin
-rwxrwxrwx 1 root root        24 mai   12 13:39 VERSION
-rwxrwxrwx 1 root root       107 mai   12 13:39 vk_swiftshader_icd.json
```

__Expected Behavior__

Tarball archive should have sensible file permissions,

```bash
drwxr-xr-x 6 root root      4096 april  8 10:04 .
drwxr-xr-x 4 root root      4096 sep.  23 20:30 ..
-rwxrwxr-x 1 root root 115543344 feb.   5  2021 camunda-modeler
-rw-rw-r-- 1 root root    178136 feb.   5  2021 chrome_100_percent.pak
-rw-rw-r-- 1 root root    316984 feb.   5  2021 chrome_200_percent.pak
-rwxrwxr-x 1 root root   5583056 feb.   5  2021 chrome-sandbox
-rw-rw-r-- 1 root root  10426784 feb.   5  2021 icudtl.dat
-rw-rw-r-- 1 root root    248168 feb.   5  2021 libEGL.so
-rw-rw-r-- 1 root root   2973944 feb.   5  2021 libffmpeg.so
-rw-rw-r-- 1 root root   8375488 feb.   5  2021 libGLESv2.so
-rw-rw-r-- 1 root root      1095 feb.   5  2021 LICENSE.camunda-modeler.txt
-rw-rw-r-- 1 root root      1060 feb.   5  2021 LICENSE.electron.txt
-rw-rw-r-- 1 root root   4675743 feb.   5  2021 LICENSES.chromium.html
drwxr-xr-x 2 root root      4096 feb.   5  2021 locales
-rw-rw-r-- 1 root root     82118 feb.   5  2021 natives_blob.bin
drwxr-xr-x 3 root root      4096 april  8 09:43 resources
-rw-rw-r-- 1 root root   8646956 feb.   5  2021 resources.pak
-rw-rw-r-- 1 root root    280392 feb.   5  2021 snapshot_blob.bin
drwxr-xr-x 2 root root      4096 april  8 10:04 support
drwxr-xr-x 2 root root      4096 feb.   5  2021 swiftshader
-rw-rw-r-- 1 root root    165333 feb.   5  2021 THIRD_PARTY_NOTICES.camunda-modeler.txt
-rw-rw-r-- 1 root root    701056 feb.   5  2021 v8_context_snapshot.bin
-rw-rw-r-- 1 root root        24 feb.   5  2021 VERSION
```

__Environment__

- OS: Linux Ubuntu 20.04.3
- Camunda Modeler Version: 4.8.1, 4.9.0, 4.10.0
- Execution Platform: N/A
- Installed plug-ins: N/A

### PR DESCRIPTION
**Pull request by kyteinsky**
Set [improved permissions to files and directories](#2439).

---

Closes #2439

### CODE REVIEW

**Comment by nikku** [comment]
Also, the update permissions check will only run on `linux` targets now.

**Comment by nikku** [comment]
@barmac @MaxTru Please have a look.

**Comment by kyteinsky** [comment]
@nikku Thanks for the review and the simplification of the code. Personally, even I did feel unsatisfied with the code and pushed it just as a draft PR for help regarding executable files :laughing:

**Comment by barmac** [comment]
> If we wanted to add it, what is the `electronPlatformName`?

`darwin`

**Comment by barmac** [comment]
> > Looks legit. Shouldn't we also add it for MacOS?
> 
> Not sure. I'd assume MacOS did take care of the basics, as users are essentially installing these apps.

Probably you're right.

**Comment by nikku** [comment]
If you want to give it a go you could try if tightening the permissions on the Mac App does any harm. I cannot check that locally.

**Pull request merged**
