### PR TITLE
feat: Implement info level lint messages

### LINKED ISSUE #3933: Support linter type `info`
### What should we do?

Support linter type `info` that we produce / our users may produce through validation rules.

### Why should we do it?

It seems like the [web modeler supports it](https://github.com/camunda/web-modeler/blob/main/webapp/src/components/ErrorPanel/ErrorIcon.js#L16) but [not the desktop modeler](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/panel/tabs/linting/LintingTab.js#L124).

### PR DESCRIPTION
**Pull request by vsgoulart**
Closes #3933

I just copied the same icon from the web modeler.
Example of how it looks like:

### CODE REVIEW

**Comment by nikku** [comment]
@vsgoulart One thing that made me wonder is whether we want to start summing up "errors, warnings and info" under a general "x Issues" in the footer. Info in general is "nice to know, but I don't have to care about them".

One improvement we could make is to only show the actual most relevant icon, with a number, i.e. "(ERROR_ICON) 1" if one error exists, "(INFO_ICON) 1" if no errors and warnings, just info category items exist. What this does is to give users a very quick idea of what is the state of their diagram, and if they should actually consider the problems tab at all, without becoming too verbose.

@philippfromme maybe you can help out, cross checking VSCode as a role-model? I believe they are able to show info in their "errors panel", too.

**Comment by philippfromme** [comment]
I'd probably go for the VS Code approach here. We could reduce the noise by reducing the colors.

**Comment by nikku** [comment]
I believe VSCode only shows info items if these actually exist, so let's make it so and consider following up with reduced colors some day, maybe.

**Comment by nikku** [comment]
I pushed https://github.com/camunda/camunda-modeler/pull/3936/commits/435263458ab47ab5f430cd893d89504892d88622 to be able to test this:

capture sO1QYq_optimized

**Comment by nikku** [comment]
I went ahead and implemented "show info only if it exists" via https://github.com/camunda/camunda-modeler/pull/3936/commits/9f452028c18e3499abb4312cf24dc59842d2a9f4. @philippfromme Please review. 

capture ig5QPd_optimized

**Review by barmac — APPROVED** [review]

**Pull request merged**
