### PR TITLE
Integrate latest dmn-js dependencies

### PR DESCRIPTION
**Pull request by philippfromme**
### Proposed Changes

Integrates fix for https://github.com/bpmn-io/dmn-js/issues/848 by integrating latest `camunda-dmn-js`, `dmn-js` and `dmn-js-shared`.

### CODE REVIEW

**Comment by marstamm** [comment]
On linux, I can navigate using the arrow keys to navigate and the entry does get the `focused` class, but no visual indication is shown. Did we update the CSS properly?

image

**Comment by philippfromme** [comment]
@marstamm I can reproduce this issue. I think we forgot to integrate this into camunda-dmn-js. 🤦🏻

**Comment by philippfromme** [comment]
Fix incoming: https://github.com/camunda/camunda-dmn-js/pull/122

**Comment by philippfromme** [comment]
@marstamm Should be fixed now.

electron_9lJiqXWLMV

**Review by marstamm — APPROVED** [review]

**Pull request merged**
