### PR TITLE
deps: update to moddle@6.2.3

### LINKED ISSUE #3589: Diagram containing custom namespace can not be opened
### Describe the bug

When I try to open a diagram containing a custom namespace, the tab crashes
image

### Steps to reproduce

1. Open [converted-c8-c7-test.bpmn.txt](https://github.com/camunda/camunda-modeler/files/11383299/converted-c8-c7-test.bpmn.txt)
2. It breaks

### Expected behavior

Custom Namespaces are ignored

### Environment

 * Version: 5.11.0-rc.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 8

### Additional context

This is a regression in 5.10.0, it worked in 5.9.0

Originally reported by @jonathanlukas on Slack

### PR DESCRIPTION
**Pull request by marstamm**
closes #3589

### CODE REVIEW

**Comment by nikku** [comment]
Good stuff. Let's consider bumping this in `bpmn-js`, too.

**Comment by marstamm** [comment]
Converting to draft: `set` and `get` get serialized in the XML 🙈 

```
      <conversion:message get="function(key) {
      return this[key];
    }" set="function(key, value) {
      (0,min_dash__WEBPACK_IMPORTED_MODULE_0__.set)(this, [ key ], value);
    }" severity="INFO">Element 'property' was transformed. Property 'key' lives in the Zeebe namespace now.</conversion:message>
```

**Comment by nikku** [comment]
:see_no_evil:

**Comment by marstamm** [comment]
fixed in moddle ==> https://github.com/bpmn-io/moddle/pull/55

**Comment by marstamm** [comment]
Addressed with [0111039](https://github.com/camunda/camunda-modeler/pull/3591/commits/0111039a50073407aacb3e42f73be0475d88e038)

**Review by nikku — APPROVED** [review]

**Pull request merged**
