### PR TITLE
Migrate to ESLint 9 and flat config

### PR DESCRIPTION
**Pull request by philippfromme**
### Proposed Changes

Migrate to `eslint@9`, adjust code base to follow new (improved) conventions.

Related to https://github.com/bpmn-io/internal-docs/issues/1042

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
@philippfromme What's left to wrap up this topic?

**Comment by philippfromme** [comment]
@nikku When using the latest version `eslint-plugin-bpmn-io` we're getting a lot of React-related errors:

```sh
C:\workspace\camunda\camunda-modeler\client\src\app\EmptyTab.js
  122:112  error  `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`  react/no-unescaped-entities
  122:117  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities
  122:123  error  `"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`  react/no-unescaped-entities

C:\workspace\camunda\camunda-modeler\client\src\app\TabsProvider.js
  141:18  error  Component definition is missing display name  react/display-name

C:\workspace\camunda\camunda-modeler\client\src\app\resizable-container\__tests__\ResizableContainerSpec.js
  323:7  error  Do not pass children as props. Instead, nest children between the opening and closing tags  react/no-children-prop

C:\workspace\camunda\camunda-modeler\client\src\app\slot-fill\Slot.js
  72:37  error  Component definition is missing display name  react/display-name

C:\workspace\camunda\camunda-modeler\client\src\app\slot-fill\__tests__\SlotFillSpec.js
   85:7   error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated   
  103:7   error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated   
  124:26  error  Do not depend on the return value from ReactDOM.render                                                                       react/no-render-return-value
  124:26  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated   
  136:26  error  Do not depend on the return value from ReactDOM.render                                                                       react/no-render-return-value
  136:26  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated   
  161:26  error  Do not depend on the return value from ReactDOM.render                                                                       react/no-render-return-value
  161:26  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated   
  197:26  error  Do not depend on the return value from ReactDOM.render                                                                       react/no-render-return-value
  252:28  error  Do not depend on the return value from ReactDOM.render                                                                       react/no-render-return-value
  252:28  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated
  281:28  error  Do not depend on the return value from ReactDOM.render                                                                       react/no-render-return-value
  281:28  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated

C:\workspace\camunda\camunda-modeler\client\src\index.js
  95:3  error  ReactDOM.render is deprecated since React 18.0.0, use createRoot instead, see https://reactjs.org/link/switch-to-createroot  react/no-deprecated

C:\workspace\camunda\camunda-modeler\client\src\plugins\version-info\VersionInfoOverlay.js
  40:13  error  `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`  react/no-unescaped-entities

✖ 23 problems (23 errors, 0 warnings)
```

We could either reconfigure the respective rules or adjust the code.

**Comment by nikku** [comment]
Happy to look into this, once you pushed the changes.

**Comment by philippfromme** [comment]
I did already push them.

**Comment by nikku** [comment]
> We could either reconfigure the respective rules or adjust the code.

That would have been a good practice for you, to evaluate the practicality of the new rules :upside_down_face:.

I went ahead and did the evaluation. As seen in previous (bpmn-js, diagram-js, properties-panel*) code bases, the new rules are _very good_ at detecting subtle errors (duplicate tests, ...), but also to prevent common oversights. I approve them.

See my changes attached on this PR.

**Comment by nikku** [comment]
Went ahead and further simplified this PR. What I noticed is that we silently migrated to `package-lock#lockfileVersion=3`. If we decide to go that route, let's make it explicit; hence I reverted this here.

**Comment by nikku** [comment]
Looking for CI to not get stuck now :crossed_fingers:, so we can merge this.

**Pull request merged**
