### PR TITLE
feat(startProcessInstance): add the text field to set up variables when starting a new process instance

### PR DESCRIPTION
**Pull request by aivinog1**
This is a Camunda Platform part of #2437. There will be the Camunda Cloud/Zeebe part of #2437.

I decided to move all logic to the `StartInstanceTool` right before calling Camunda REST API. I'm not sure about it 🤷🏻‍♂️.

### CODE REVIEW

**Review by MaxTru — CHANGES_REQUESTED** [review]
Thanks for the contribution!

I had a first high-level look. Some questions / remarks:

1. You state this is part of #2437. Could you please explain what other "parts" you expect (e.g., breakdown of the issue)
2. Even typing simple JSON strings, I run into this validation issue, can you please check:
Screenshot_20211004_084755
3. Could you please somehow indicate in the Label or description of the field that a valid JSON string needs to be provided

Thanks

**Comment by barmac** [comment]
Note that machine-generated error is not super helpful:

image

**Comment by andreasgeier** [comment]
UX review:

- Variables are optional. This should be clear by adding the information to the label: `Variables (optional)` 
- We cannot add example data as value. This would lead to the unintended creation of a variable or would force the user to manually delete it each time when starting an instance. Better: put the example outside of the field and let the field empty.
- If we have a textarea component, we should use it here. A single-line text input might be insufficient.

Please consider these changes.

As inspiration, this is the solution in Camunda Cloud:

Screen Shot 2021-10-08 at 15 00 34

Link target in screenshot: [Variables](https://docs.camunda.io/docs/product-manuals/concepts/variables)

**Comment by andreasgeier** [comment]
> Note that machine-generated error is not super helpful:

As the first iteration of this topic, I believe a JSON validation that just returns just true/false is okay.

**Comment by barmac** [comment]
@aivinog1 Are you willing to implement the suggestion left by @andreasgeier? If so, please let us know. Otherwise, we will probably close this PR but you can get back to it when you have time.

**Comment by barmac** [comment]
Cool, then I keep it open :)

**Comment by MaxTru** [comment]
@aivinog1 will you continue to work on this or shall I close this PR?

**Comment by aivinog1** [comment]
@MaxTru Please, do not close this, I'll look at it on 16th October 🙂

**Comment by MaxTru** [comment]
> @MaxTru Please, do not close this, I'll look at it on 16th October slightly_smiling_face

Sure - will leave it open. I assume you mean November 16? :-)

**Comment by aivinog1** [comment]
Hey @MaxTru @barmac @andreasgeier! Finally, I've found time to look at this. Can you check this out, please? :)

**Comment by MaxTru** [comment]
I have two comments:

1. For me this still does not work, it complains that even simple strings are not valid JSONs. Do I miss something:?
Screenshot_20211201_165150

2. The UI looks a bit broken (see Screenshot above). @andreasgeier maybe you can advice?

**Comment by barmac** [comment]
> For me this still does not work, it complains that even simple strings are not valid JSONs. Do I miss something:?
JSON uses double quotes. So it should be`{"a":"b"}` in your example.

**Comment by MaxTru** [comment]
> > For me this still does not work, it complains that even simple strings are not valid JSONs. Do I miss something:?
> 
> JSON uses double quotes. So it should be`{"a":"b"}` in your example.

Ups. Yeah indeed it works that way.

Implementation wise this looks good! Thanks for this contribution.

I think the UI needs some cleanup:

* The PR breaks the UI of "deploy" => there is now a horizontal scroll bar?
  * Screenshot_20211201_192136
* This looks broken. @andreasgeier maybe you can advice?
  * Screenshot_20211201_192220

**Comment by andreasgeier** [comment]
@aivinog1

Cool to see your progress! Feedback from product design:

- avoid breaking the layout of the dialog (horizontal scrollbar)
- avoid bold text and links within labels

Suggestion:

[Label:] Variables (optional)
[Textarea in full width]
[Description:] Must be a proper JSON object. [Learn more about variables](https://docs.camunda.io/docs/components/concepts/variables/).

**Comment by aivinog1** [comment]
Hey @MaxTru @andreasgeier! I've fixed all your review comments, can you check this out, please? :)

**Comment by MaxTru** [comment]
@andreasgeier Screencast for you
ScreenCast

**Comment by MaxTru** [comment]
Looks good!

Some minor things:

* Could you please fix the linting errors? (e.g. run `npm run lint`)
* Could we please give the textArea a min and max width to avoid something like this:
maxWidth
* The link provided by @andreasgeier pointed to the Cloud docs, but we should use Platform docs here. I suggest to use: https://docs.camunda.org/manual/latest/reference/rest/process-definition/post-start-process-instance/#request.
* @andreasgeier I think the description should be more explicit to educate the user that it needs to be a JSON object according to the structure described in the docs. So what about.
```
[Description:] Must be a proper JSON variables object. [Learn more and find an example for variables](https://docs.camunda.org/manual/latest/reference/rest/process-definition/post-start-process-instance/#request).
```

**Comment by MaxTru** [comment]
By the way @aivinog1 => this really looks great already. If you want, I can take over the final polishing things. Please let me know.

**Comment by aivinog1** [comment]
@MaxTru It is done. Can you check again, please? :)

**Comment by MaxTru** [comment]
Nice! Merged.

Thanks for the contribution <3

**Pull request merged**
