### PR TITLE
DropdownButton: Add Multi button feature

### PR DESCRIPTION
**Pull request by nikku**
This should help both run and deploy.

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I just was about to ask you regarding this ;) Will have a look on Monday! 🚀

**Comment by nikku** [comment]
Found and fixed.

**Comment by nikku** [comment]
Fixed, at last.

**Comment by pinussilvestrus** [comment]
I'll test this in order to integrate in the start instance state. Will also test some test cases for it to complete.

**Pull request merged**
