### PR TITLE
Deploy Camunda 8 Forms

### PR DESCRIPTION
**Pull request by philippfromme**
electron_9FMSW36Jpi

---

Related to https://github.com/camunda/camunda-modeler/issues/3656

### CODE REVIEW

**Comment by philippfromme** [comment]
Depends on https://github.com/camunda-community-hub/zeebe-client-node-js/pull/338 to be integrated.

**Comment by nikku** [comment]
Integrated `zeebe-node` via https://github.com/camunda/camunda-modeler/pull/3952/commits/2e75d7eca0f78546a819a846e89c90b38a2a0a12.

**Review by nikku — COMMENTED** [review]
Looks great and works for me.

:+1: for cleaning up on the way :slightly_smiling_face:

**Review by nikku — APPROVED** [review]

**Comment by marstamm** [comment]
I found a related issue when setting form-id in the properties panel
https://github.com/camunda/camunda-modeler/issues/3963

**Comment by marstamm** [comment]
I can deploy forms to an 8.3.1 SaaS cluster (so the modeler part works), but Tasklist does not seem to pick it up. Is this expected? Is there an easy way to test it end to end?

**Comment by nikku** [comment]
> I can deploy forms to an 8.3.1 SaaS cluster (so the modeler part works), but Tasklist does not seem to pick it up. Is this expected? Is there an easy way to test it end to end?

I'd verify two things:

* Is it deployed according to zeebe :arrow_right: check deployed resources
* Are we running into the "tasklist idle timeout" trap?

**Comment by philippfromme** [comment]
Fix for #3963: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/998

**Comment by marstamm** [comment]
> I'd verify two things:
> 
> * Is it deployed according to zeebe ➡️ check deployed resources
> * Are we running into the "tasklist idle timeout" trap?

I am running into problems in the first step: Where can we even check deployed resources? Console does not show it, Operate only shows Processes (and Decision INSTANCES, no definitions), Tasklist shows Tasks and process Definitions. `zbctl` does not seem to have a "list" method either. 

Am I missing something?

**Comment by nikku** [comment]
@marstamm It looks to me as if tasklist does not support deployments yet, it will come with the next alpha.

**Comment by nikku** [comment]
> Tasklist shows Tasks and process Definitions. zbctl does not seem to have a "list" method either.

We indeed need to trust the response we get from `zeebe-node` for the time being.

**Pull request merged**
