### PR TITLE
Introduce reduced color scheme

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Adds the new, reduced color scheme and updates the existing colors with the new ones. Also see the transformation plan for the existing scheme: https://github.com/camunda/camunda-modeler/issues/2459#issuecomment-951977843

Note that this only includes updating the colors for this project. For the libraries, we have separate issues (cf. [epic issue](https://github.com/camunda/camunda-modeler/issues/2459)).

----

Related to #2459 

**Artifacts**

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2459-new-color-scheme/camunda-modeler-2459-new-color-scheme-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2459-new-color-scheme/camunda-modeler-2459-new-color-scheme-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2459-new-color-scheme/camunda-modeler-2459-new-color-scheme-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2459-new-color-scheme/camunda-modeler-2459-new-color-scheme-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2459-new-color-scheme/camunda-modeler-2459-new-color-scheme-win-x64.zip

image

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Note for the reviewer: I added artifacts to [the description](https://github.com/camunda/camunda-modeler/pull/2539#issue-771199971). Since this includes lots of tiny changes, it makes sense to check it out, look and feel.

**Comment by nikku** [comment]
Quick feedback from my side: 

* As expected fonts + new colors are slightly less readable than the old version. This may be due to miss-configured hinting on my OS (Linux) but also is due to the nature of the font being fairly nuanced / playful.
* The link color is hard to see, also A11y tools in Chrome warn me regarding the contrast:
    capture HJFjJV_optimized

**Comment by pinussilvestrus** [comment]
Thanks! Let's include @andreasgeier to tackle these discussion points.

> Descriptive texts, tab outline and names are barely visible in the BPMN properties panel (see screen above)

Color-wise, the BPMN properties panel did not change in this PR (at least it shouldn't). Except for the font of course, but that's not part of this PR.

**Comment by nikku** [comment]
Good point @pinussilvestrus! 

As mentioned both, font and color have an impact on contrast. So if we did not change anything in the properties panel with this PR it is likely the introduction of the new font that causes what I describe.

**Review by nikku — APPROVED** [review]
:+1: for proper `--color` prefixing. 

Let's get this merged and iterate.

**Pull request merged**
