### PR TITLE
fix(element-templates-modal): get local and global element templates

### LINKED ISSUE #2021: Catalog Is Aware of Versions
* [x] Catalog shows version instead of date
* [x] Catalog only shows latest version of a template

Related to camunda/camunda-modeler#1969
Child of camunda/camunda-modeler#1969

### PR DESCRIPTION
**Pull request by philippfromme**
__Which issue does this PR address?__

Closes https://github.com/camunda/camunda-modeler/issues/2012

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by nikku** [comment]
Can you elaborate how this fixes the problem at hand? How is that change in the plug-in API required for element templates to work?

**Comment by nikku** [comment]
Could you also update the commit to reference the correct issue (#2012)?

**Comment by philippfromme** [comment]
@nikku The reason local element templates weren't shown anymore is that `config.get('bpmn.elementTemplates')` is missing a second parameter which is the active tab. [`App#getConfig`](https://github.com/camunda/camunda-modeler/blob/v4.4.0/client/src/app/App.js#L1741) was introduced for that reason. When calling `getConfig` the caller doesn't have to know about the active tab. [`BpmnEditor` uses `getConfig`](https://github.com/camunda/camunda-modeler/blob/v4.4.0/client/src/app/tabs/bpmn/BpmnEditor.js#L200), too, for that reason. Another fix would be to get hold of the active tab and to call `Config#get` with it.

**Comment by nikku** [comment]
Makes perfect sense. Thanks for taking the time to elaborate.

You could put that into the commit as a two liner description, too.

**Pull request merged**
