### PR TITLE
Update release info for 5.22.0

### PR DESCRIPTION
**Pull request by barmac**
image

### CODE REVIEW

**Comment by nikku** [comment]
Look good to me! :)

**Comment by lmbateman** [comment]
Assuming we mentioned Zeebe user tasks in the previous release notes, this looks good to me, too!

**Comment by barmac** [comment]
@crobbins215 @nikku @lmbateman I updated the proposal based on the Forms new features. Please check the screenshot now.

**Comment by barmac** [comment]
Thank you for your suggestions. The "the" issue is fixed now.

I will change it to sentence case as in the example: https://github.com/bpmn-io/internal-docs/blob/main/releases/modeler/CAMUNDA_MODELER.md#whats-new-communication
It looks like we introduced title case in the previous release.

**Comment by barmac** [comment]
I updated the screenshot accordingly.

**Pull request merged**
