### PR TITLE
feat: show error in properties panel on lint error click

### PR DESCRIPTION
**Pull request by philippfromme**
IKPvRv01dT

---

Requires https://github.com/camunda/camunda-bpmn-js/pull/99
Requires https://github.com/bpmn-io/properties-panel/pull/142
Requires https://github.com/bpmn-io/bpmn-js-properties-panel/pull/601

### CODE REVIEW

**Comment by philippfromme** [comment]
# Artifacts

* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/linting-final/camunda-modeler-linting-final-linux-x64.tar.gz
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/linting-final/camunda-modeler-linting-final-mac.dmg
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/linting-final/camunda-modeler-linting-final-mac.zip
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/linting-final/camunda-modeler-linting-final-win-ia32.zip
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/linting-final/camunda-modeler-linting-final-win-x64.zip

**Comment by andreasgeier** [comment]
@philippfromme can we avoid the flickering/delay of the context pad when clicking on an error message link? When I select an element on the canvas manually there is no delay of the context pad.

**Review by MaxTru — COMMENTED** [review]
General integration works and is tested. Nice!

One finding regarding the path mappings below: However, I would not see that blocking for this PR here (which I primarily see as doing the integration). So I would propose a follow-up issue for this one. wdyt @philippfromme ?

* Jump to proppanel does not work for Loop Characteristics
Screenshot_20220331_114749

**Comment by nikku** [comment]
Great stuff (seeing it end-to-end).

Side note: You're sure Task Definition requires retries? If that is the case, we should fix it on our end, i.e. by assuming a sensible default (i.e. `3`). Otherwise there is just too much stuff for a user to walk through in order to get a task implemented.

**Comment by MaxTru** [comment]
Triggered by what Nico stated: I am not convinced that `retries` is mandatory. This also contradicts the docs...

Screenshot_20220331_130802

**Comment by MaxTru** [comment]
I quick-checked rules against docs.

1. <task definition must have retries> [does not fit to the docs](https://docs.camunda.io/docs/components/modeler/bpmn/service-tasks/#task-definition). Also I can deploy a process without retries without issues to Zeebe 1.4.
=> So I think we can simply remove this rule
===> @andreasgeier since this defaults to `3` on engine side, shall we maybe indicate this with a description or so?

----the following are not of priority for 5.0.0, but should be soon to follow-up rules I believe, since we are already active in their domain----
2. We validate that a message is referenced by the `messageEventDefintion`. However, a `message` must also have a name, which we don't check. See https://docs.camunda.io/docs/components/modeler/bpmn/message-events/#messages
3. We validate that a error is referenced by the `errorEventDefinition`. However, an `error` must have an errorCode, which we don't check. See https://docs.camunda.io/docs/components/modeler/bpmn/error-events/#defining-the-error
4.

**Comment by philippfromme** [comment]
1. The delay of the context pad being shown I cannot explain. I'm using the same API. I will look into this but it shouldn't keep us from merging.
2. The issue with multi instance not working I cannot reproduce. Can you tell me how to, @MaxTru?
3. You're right about `zeebe:retries`. The only requirement is that it must be a valid FEEL expression if it is one but we don't lint that kind of stuff yet. I'll remove that check.

This PR is primarily about the integration of all the components. We could merge this and I'll follow up with a fix regarding 3. and potentially more fixes.

**Comment by MaxTru** [comment]
> > 1. So I think we can simply remove this rule
> >    ===> @andreasgeier since this defaults to `3` on engine side, shall we maybe indicate this with a description or so?
> 
> Can we ensure that this default is equal across all engine versions now and in the future? I tend to avoid such a dependency to engine behavior.

For the past: yes :-) For the future: no. But is that not always the case for the future :-)

**Review by MaxTru — APPROVED** [review]
Approving considering https://github.com/camunda/camunda-modeler/pull/2861#issuecomment-1084524943

**Comment by benhoffmann** [comment]
One quick comment as this just came up in the stakeholder meeting:

It would be really cool if those error messages were aligned with errors that show up in tests. So if there was a problem with the model and that causes a test to fail, ideally the message would look the same or very similar to the one that is displayed in the Modeler.

I'm referring to https://github.com/camunda/zeebe-process-test and

**Pull request merged**
