### PR TITLE
Allways Fall Back to Default Properties Panel Layout

### LINKED ISSUE #2252: Cannot read property open of undefined when toggling properties panel for the first time
__Describe the Bug__

On a clean installation of Camunda Modeler, when I click "Toggle properties panel", an error appears:

```
2021-05-10T11:38:06.814Z  ERROR client Cannot read property 'open' of undefined
    at open (webpack:///src/app/tabs/dmn/DmnEditor.js:614:39)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:259:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1719:15)
    at fn (webpack:///src/app/App.js:2244:19)
    at file:///Applications/Camunda%20Modeler%204.7.app/Contents/Resources/app.asar/public/bundle.js:65:127778
    at exec (webpack:///src/app/AppParent.js:76:11)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2469:16)
```

__Steps to Reproduce__

1. Remove config.json
2. Open Camunda Modeler
3. Click "Toggle properties panel" in the menu

https://user-images.githubusercontent.com/28307541/117653863-40c7a000-b195-11eb-9700-2a09dba82722.mov

__Expected Behavior__

No errors.

__Environment__

- OS: macOS
- Camunda Modeler Version: 4.7, 4.8
- Installed plug-ins: [...]

### PR DESCRIPTION
**Pull request by philippfromme**
BPMN and DMN properties panel will always fall back to default layout.

Closes #2252

### CODE REVIEW

**Comment by barmac** [comment]
I think we should just copy the default layout provided in https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/PropertiesContainer.js#L23. Then, the width will be provided and it should open.

**Review by nikku — CHANGES_REQUESTED** [review]
Cf. https://github.com/camunda/camunda-modeler/pull/2255#issuecomment-836797978

**Comment by philippfromme** [comment]
I cannot work on this at the moment due to the [broken development setup](https://github.com/camunda/camunda-modeler/issues/2269) on Windows. But I don't think this is an urgent fix.

**Review by nikku — APPROVED** [review]
Good job :clap:

**Pull request merged**
