### PR TITLE
feat(cloud-bpmn): integrate `@bpmn-io/bpmn-properties-panel`

### LINKED ISSUE #2347: Integrate New Cloud Properties Panel
__What should we do?__

Integrate the new properties panel for Cloud diagrams (cf. https://github.com/bpmn-io/bpmn-properties-panel/pull/1). 

**tbd**: add a feature toggle for this.

__Why should we do it?__

Make it available for Cloud diagrams.

__Context__

Child of https://github.com/bpmn-io/properties-panel/issues/5

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Replaces old with new properties panel in Cloud Bpmn Editor

Related to bpmn-io/properties-panel#5
Closes #2347
Depends on https://github.com/bpmn-io/bpmn-properties-panel/pull/14

Bildschirmfoto 2021-07-12 um 10 14 32

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I integrated [`bpmn-io/bpmn-properties-panel@0.1.0`](https://github.com/bpmn-io/bpmn-properties-panel/tree/v0.1.0) via GitHub dependency. Therefore it's ready for review now.

We decided against a feature toggle for now. Let's roll it out via nightly 🔥

**Comment by nikku** [comment]
Integration looks :cool:.

As this is the first time I'm trying out the full thing end-to-end in the Camunda Modeler I'd love to give two bits of structured feedback:

__Input Colors__

Example of the current panel:

image

Looks a little bit like the inputs are disabled, especially considering how other inputs look like in the app:

image

I know that we want to settle down on _one_ style for the inputs, across the whole app, that is not the issue here. The issue is really that gray as a background for inputs is nothing I know and expect from editable inputs (cf. https://getbootstrap.com/docs/5.0/forms/input-group/, https://get.foundation/sites/docs/forms.html, ...). Not sure if we user tested that, if we did not, we should. Such things can be real UX issues (cf. my comment on the cloud deploy dialog :arrow_right: slack).

From my personal experience we do not gain much by tweeking colors on core UI controls. These things should just work.

__Assistive / descriptive texts__

It is great that we have _General (edited)_ as a hint. What I'd expect as a user though is that the hint is where the visual (indicating) UI elements are. I'm hovering a thing to understand it.

capture Py12xt_optimized

To improve the situation: Add appropriate hints to our dots _and_ the expand / collapse arrows. A smaller improvement: Do show the descriptive title on the whole header, not only the header text.

/CC @andreasgeier

**Review by nikku — APPROVED** [review]
Assuming we never officially allowed extensions for the Zeebe Properties Panel (cf. https://github.com/bpmn-io/internal-docs/issues/323) we should be good.

**Comment by pinussilvestrus** [comment]
Yep 👍  
Cf. https://github.com/camunda/camunda-modeler/issues/2284

**Comment by andreasgeier** [comment]
@nikku thx for your comments:

1. regarding light grey background on inputs: let's discuss when the design finishing takes place. For now, this acts as little contrast between inputs and the surrounding background.
2. regarding tooltip for dots: I agree that it would be helpful (and expected) to have a title for this element as well. This will be solved during design finishing (not only the hint but also the size of the interactive area)
3. regarding checkboxes: we do not have final design yet and no global style for customized form elements. again, design finishing will take place asap

I'm eager to do these changes (definitively in Q3) but for now, we agreed to proceed with implementing the function and fix the design afterward.

**Comment by nikku** [comment]
> I'm eager to do these changes (definitively in Q3) but for now, we agreed to proceed with implementing the function and fix the design afterward.

Makes sense, hence my approval, too :)

**Comment by pinussilvestrus** [comment]
@andreasgeier any particular from your side to add or can with merge this?

**Pull request merged**
