### PR TITLE
feat: add basic auth to Zeebe deployments

### LINKED ISSUE #4160: Support HTTP Basic authentication for C8 SM deployment
### Problem you would like to solve

Modeler supports currently only OAuth for secure deployment to C8 Self-Managed. This is a blocker for users who implement HTTP Basic (username + password) authentication.

### Proposed solution

Add option to provide username and password when deploying to C8 SM.

### Alternatives considered

There are none.

### Additional context

Reported via [SUPPORT-20648](https://jira.camunda.com/browse/SUPPORT-20648).

[HTTP Basic is supported out of the box in zeebe-node](https://github.com/camunda-community-hub/zeebe-client-node-js?tab=readme-ov-file#basic-auth).

### PR DESCRIPTION
**Pull request by philippfromme**
electron_kMPMFQn9xa

* adds basic auth to self-managed deployments
* aligns naming of endpoint types and authentication types across codebase

Closes #4160

### CODE REVIEW

**Review by barmac — CHANGES_REQUESTED** [review]
The credentials should be redacted from the log:
```
ERROR app:zeebe-api connection check failed {
  parameters: {
    endpoint: {
      type: 'selfHosted',
      authType: 'basic',
      url: 'http://localhost:8000',
      basicAuthUsername: 'abc',
      basicAuthPassword: 'def'
    }
  }
}
```

**Comment by philippfromme** [comment]
@nikku No success testing this end-to-end. I'm trying to get help from the Zeebe team. Otherwise I'd need your help.

**Comment by philippfromme** [comment]
@barmac Done: https://github.com/camunda/camunda-modeler/pull/4269/commits/b346b79ef03bc6a0464ad8ec2f5d90d728671c2c

**Comment by nikku** [comment]
I was able to end-to-end test this using a standard reverse proxy setup, based off our [zeebe-connection-test project](https://github.com/camunda/zeebe-connection-test), [`basic-auth` branch](https://github.com/camunda/zeebe-connection-test/tree/basic-auth).

### Topology (test setup)

```
Camunda Modeler -> [NGINX; enforces basic auth] -> Zeebe
```

### Test it yourself

You can use the following script to test it yourself :tm::

```sh
# Clone repository
git clone git@github.com:camunda/zeebe-connection-test.git
cd zeebe-connection-test
git checkout -b basic-auth
```

Proceed with the [run instructions](https://github.com/camunda/zeebe-connection-test/tree/basic-auth?tab=readme-ov-file#script-3) to spin up Zeebe.

Then to test with the [Camunda Modeler](https://github.com/camunda/camunda-modeler) specify self-managed, `http://sub.example.com`, basic auth and pass `demo:demo` as credentials.


----

### Test results

* Initially when no credentials are provided we pass `undefined` for both basic auth username and password; I suggest we rather pass `''` (an empty string). Otherwise zeebe-node will assume no basic auth is set
* When testing for errors we do not properly handle authentication failures. What I see is the standard "Cannot connect to Zeebe cluster" error, but no indication that this may be due to wrong or missing credentials.

  screenshot pwqbVl screenshot PmVY6q

Besides these two things it works; I can deploy successfully.

**Review by nikku — CHANGES_REQUESTED** [review]
To be followed-up, cf. https://github.com/camunda/camunda-modeler/pull/4269#issuecomment-2098236389.

**Comment by philippfromme** [comment]
I'm not sure how to deal with the errors. After setting up a reverse proxy with basic auth the error I get when using the wrong credentials is

`Error: 13 INTERNAL: Received RST_STREAM with code 0\n    at callErrorFromStatus (C:\workspace\camunda\camunda-modeler\node_modules\@grpc\grpc-js\build\src\call.js:31:19)\n    at Object.onReceiveStatus (C:\workspace\camunda\camunda-modeler\node_modules\@grpc\grpc-js\build\src\client.js:192:76)\n    at C:\workspace\camunda\camunda-modeler\node_modules\@grpc\grpc-js\build\src\call-interface.js:78:35\n    at Object.onReceiveStatus (C:\workspace\camunda\camunda-modeler\node_modules\zeebe-node\dist\lib\GrpcClient.js:97:36)\n    at InterceptingListenerImpl.onReceiveStatus (C:\workspace\camunda\camunda-modeler\node_modules\@grpc\grpc-js\build\src\call-interface.js:73:23)\n    at Object.onReceiveStatus (C:\workspace\camunda\camunda-modeler\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:360:141)\n    at Object.onReceiveStatus (C:\workspace\camunda\camunda-modeler\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)\n    at C:\workspace\camunda\camunda-modeler\node_modules… …
`

which is just a GRPC error but doesn't provide any hint that this might be related to wrong credentials.

I could just map `code === 13 && authType === 'basic'` to and unauthorized error but I suspect that this error can also occur unrelated to wrong credentials. 🤔

**Comment by philippfromme** [comment]
@nikku @barmac We could decide to fix the [error handling](https://github.com/camunda/camunda-modeler/pull/4269#issuecomment-2098586341) as a follow-up.

**Comment by nikku** [comment]
Agreed that it makes sense to maybe improve the error handling as a follow-up.

**Pull request merged**
