### PR TITLE
deps: downgrade to form-js@1.10.0

### LINKED ISSUE #4559: Input field looses focus
### Describe the bug

If I type in the `Task Definition > Retries` field the input looses focus. The same issue can be replicated across different types of `FEEL (optional)` fields.

capture wR68uZ_optimized

### Steps to reproduce

1. Write `= some expression` into a `Task Definition > Retries` field
2. Remove expression (all content)
3. Type `= s` again in the field
4. **Input is no longer focussed**

### Expected behavior

Input keeps focus when field turns into an expression field

### Environment

- OS: Linux
- Camunda Modeler Version: v5.28.0 (works in v5.27.0)
- Execution Platform: Camunda 8
- Installed plug-ins: None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by barmac**
### Proposed Changes

As we were not able to easily find the problem cause, this reverts commit 8f6662dc5a8e6e558a6d2052a747b5654673d031.

Closes #4559

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Review by nikku — APPROVED** [review]
I can confirm the fix, and also confirm that forms still work.

Good work.

**Comment by nikku** [comment]
Confirmed this breaks with the codemirror updates that were pulled in via https://github.com/camunda/camunda-modeler/pull/4535. Steps to reproduce, from `main`:

```
npm update --save @codemirror/language @codemirror/view @codemirror/autocomplete @codemirror/commands @codemirror/language @codemirror/lint @codemirror/state
```

:arrow_right: https://github.com/camunda/camunda-modeler/issues/4559 reappears.

**Comment by barmac** [comment]
Have you found out which dependency is breaking?

**Comment by barmac** [comment]
OK I'll check

**Comment by barmac** [comment]
Packages which can be safely updated:

* [ ] @codemirror/language 
* [ ] @codemirror/view 
* [ ] @codemirror/autocomplete 
* [ ] @codemirror/commands 
* [ ] @codemirror/language 
* [ ] @codemirror/lint 
* [ ] @codemirror/state

**Comment by barmac** [comment]
It breaks on the `@codemirror/view` update.

**Comment by barmac** [comment]
The bug appears as early as with `@codemirror/view@6.29.0`

**Comment by barmac** [comment]
OK it actually broke one patch after the current version, so [@codemirror/view@6.28.2](https://github.com/codemirror/view/blob/main/CHANGELOG.md#6282-2024-06-21)

**Pull request merged**
