### PR TITLE
Bump camunda-bpmn-js from 0.9.3 to 0.10.0

### LINKED ISSUE #2423: Add support for manual tasks
__Is your feature request related to a problem? Please describe.__

In the next release (1.2.0) Zeebe will have support for manual tasks. These tasks can not yet be modeled in Camunda Cloud diagrams. (https://github.com/camunda-cloud/zeebe/issues/7806)

__Breakdown__

- [x] [Enable replacing of Elements to `ManualTask` => camunda/camunda-bpmn-js](https://github.com/camunda/camunda-bpmn-js/pull/49)
- [ ] [Integrate updated version of camunda/camunda-bpmn-js into camunda modeler](https://github.com/camunda/camunda-modeler/pull/2445)

__Describe the solution you'd like__

Support manual tasks in Camunda Cloud diagrams.

__Describe alternatives you've considered__

None

__Additional context__

Apart from the id and name, manual tasks do not require any further properties.

### PR DESCRIPTION
**Pull request by smbea**
Closes #2423 and related to #2420

### CODE REVIEW

**Comment by nikku** [comment]
Does this issue fix any of our issues in our [`fixed upstream`](https://tasks.bpmn.io/board?s=label%3A%22fixed%20upstream%22) column? If so, please add a 

```
Closes #issueNR
```

to the version bump PR.

**Comment by barmac** [comment]
> Does this issue fix any of our issues in our [`fixed upstream`](https://tasks.bpmn.io/board?s=label%3A%22fixed%20upstream%22) column? If so, please add a
> 
> ```
> Closes #issueNR
> ```
> 
> to the version bump PR.

@smbea This applies to the commit message :)

**Comment by barmac** [comment]
BTW https://github.com/camunda/camunda-modeler/issues/2420 will also be done once we merge this, right? If so, it should be `Closes #2420` too.

**Comment by smbea** [comment]
> BTW #2420 will also be done once we merge this, right? If so, it should be `Closes #2420` too.

#2420 is also missing the update on the new properties panel

**Review by MaxTru — APPROVED** [review]

**Pull request merged**
