### PR TITLE
deps: update forms dependencies

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes https://github.com/camunda/camunda-modeler/issues/3448

* `form-js@0.13.0`
* `form-playground@0.5.0`
* `form-linting@0.6.0`

### CODE REVIEW

**Comment by nikku** [comment]
Looking into this.

**Comment by nikku** [comment]
I was not able to break the implementation as integrated in this PR. Looks like a solid start!

Feedback on the integration:

* The form should be visually aligned, but it is not; this disturbs me:
  image
* The overall placement algorithm feels shaky still; it takes me quite some time to place elements into different places:
  capture U5bgCI_optimized
* I cannot press `ESC` to stop the create operation
* I cannot create vertical layouts and/or influence the height of resizable elements such as `img` and `textarea` components.

**Comment by nikku** [comment]
@pinussilvestrus If you could ammend the CHANGELOG as part of your contribution and showcase the main highlights, that could be wonderful.

**Comment by nikku** [comment]
I found two (bigger) issues with the new TEXT template editing feature:

* Does not comply with our existing color scheme (cf. feel-editor)
* Does not support selection, or if it does then the selection is not visible to me

capture hBCDQk_optimized

As a quick fix I suggest to simply use the existing feel-editor color scheme.

**Review by nikku — CHANGES_REQUESTED** [review]
Is it worth fixing https://github.com/camunda/camunda-modeler/pull/3523#issuecomment-1488295353? @pinussilvestrus @Skaiir?

**Comment by pinussilvestrus** [comment]
> Is it worth fixing [#3523 (comment)](https://github.com/camunda/camunda-modeler/pull/3523#issuecomment-1488295353)? @pinussilvestrus @Skaiir?

I'll sync with @Skaiir on whether and how to mitigate that. Note that we're trying[ a new theme](https://camunda.slack.com/archives/GP70M0J6M/p1679941570532899) here. It might make sense to hold this back for this release.

**Comment by nikku** [comment]
> Note that we're trying[ a new theme](https://camunda.slack.com/archives/GP70M0J6M/p1679941570532899) here. It might make sense to hold this back for this release.

It definitely makes sense to hold that one back, and stay aligned initially.

**Comment by Skaiir** [comment]
@nikku 

Actually, the FEEL theme doesn't cover markdown headings, it also doesn't cover feelers-specific syntax. So I would have had to rewrite a new theme anyways. I can't just use the feel theme unfortunately.  We can iterate on the theming as much as we like, but it's honestly not a huge deal. Yeah, it looks a little out of place for now in this one component, but at the same time it's a little out of place of a feature.

Regarding the highlighting, I'm in agreement this is an oversight, I made the background transparent and didn't notice the field selection colors were basically the same. We're gonna provide a monkey patch for that for the modelers.

**Comment by nikku** [comment]
Thanks for elaborating @Skaiir.

Let's move towards theme alignment (color wise!) quickly post 8.2. Looking forward to the fix for hover styles.

**Comment by pinussilvestrus** [comment]
@nikku we mitigated the missing selection color via `@camunda/form-playground@0.5.1`. Let me know whether this works out for you 👍 

image

As @Skaiir mentioned, we should aim for a consistent theme across our editors together. This should also include other parts, e.g. the JSON editors for form input & output (cf. https://github.com/camunda/form-playground/issues/64). I'm looking forward to that 👍

**Review by nikku — APPROVED** [review]
Thanks for your contribution. Works for me.

**Comment by christian-konrad** [comment]
@nikku thanks for the feedback!

I created 
* https://github.com/bpmn-io/form-js/issues/582
based on one of your points

**Pull request merged**
