### PR TITLE
Update electron to latest (19.0.5)

### PR DESCRIPTION
**Pull request by smbea**
I did `npm run all`, played around with it and did some of the integration tests. There seems to be no issues.

I also build artifacts, to make sure it would work:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-win-x64.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-mac.zip

---

Closes https://github.com/camunda/camunda-modeler/pull/2991

### CODE REVIEW

**Comment by nikku** [comment]
What I've found is that the update check does not work but that is due to the update server not handling feature branch builds gracefully:

capture 1sK5kH_optimized

**Comment by nikku** [comment]
Works fine on Arch Linux.

**Comment by Skaiir** [comment]
Works fine on windows as well.

**Review by Skaiir — COMMENTED** [review]
Should this target master instead of dev since we're upgrading electron to bugfix?

**Comment by smbea** [comment]
> Should this target master instead of dev since we're upgrading electron to bugfix?

Although we are hoping to fix a bug with this, it's not a direct bug fix and we aren't sure it even will fix it. So I would say no. But let's check with @MaxTru

**Comment by nikku** [comment]
Let us keep it at `develop`. It is a major change, that requires a minor version bump (at least).

**Pull request merged**
