### PR TITLE
deps: bump bpmn-js

### PR DESCRIPTION
**Pull request by nikku**
Closes https://github.com/camunda/camunda-modeler/issues/2026

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
Works for me 👍 
Not sure whether I can give my approval right now and merge-me will merge immediately. 😄

**Comment by nikku** [comment]
Give approval. It will work :see_no_evil:

**Comment by nikku** [comment]
@andreasgeier, please approve, too. 

Testing 1, one.

**Review by pinussilvestrus — APPROVED** [review]

**Comment by nikku** [comment]
Best software works sometimes only. And you really do not know, when that sometimes is. :wink:

**Review by barmac — APPROVED** [review]

**Comment by barmac** [comment]
Does it count?

**Comment by nikku** [comment]
No chance guys, I fixed everything :wink:

**Comment by nikku** [comment]
Should be possible to try out via this one:

```
npx @bpmn-io/sr camunda/camunda-modeler#bump-bpmn-js -c 'npm run dev'
```

**Review by andreasgeier — APPROVED** [review]
LGTM

**Pull request merged**
