### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kambojshalabh35**
Made readme.md more personalized.

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Unfortunately, we do not accept pull requests that don't provide substantial improvements.

**Comment by kambojshalabh35** [comment]
@nikku  please remove the invalid label as due to it I am not qualified to participate in hacktober this year, Please, It's a request.

**Comment by kambojshalabh35** [comment]
@nikku @pinussilvestrus please remove the invalid label as due to it I am not qualified to participate in Hacktober this year 😭
Please, It's a request.

**Comment by kambojshalabh35** [comment]
@nikku @pinussilvestrus please remove the invalid label as due to it I am not qualified to participate in Hacktober this year 😭
Please, It's a request.

**Comment by kambojshalabh35** [comment]
@nikku @philippfromme @falko @pinussilvestrus can anyone please remove the "invalid" label as due to it I am not qualified to participate in Hacktober this year 😭
Please, It's a request.

**Comment by philippfromme** [comment]
Please stop wasting our time.

**Pull request closed without merging**
