### PR TITLE
Remove docs

### PR DESCRIPTION
**Pull request by MaxTru**
* depends on https://github.com/camunda-cloud/camunda-cloud-documentation/pull/664
* depends on publishing of https://github.com/camunda-cloud/camunda-cloud-documentation/commit/8ea3f9273d609244970add5914be134c9a09ec00

### CODE REVIEW

**Comment by MaxTru** [comment]
Dependencies resolved, ready for review

**Comment by marstamm** [comment]
Looks good, although this line is a bit irrelevant now:

https://github.com/camunda/camunda-modeler/blob/6e80e4de8e638834d03afba75bfba4ff2969815e/.gitignore#L6

**Comment by MaxTru** [comment]
@marstamm thanks, adjusted.

**Review by marstamm — APPROVED** [review]
:rocket:

**Pull request merged**
