### PR TITLE
Update DMN deps and integrate boxed expression viewer

### PR DESCRIPTION
**Pull request by barmac**
deps: update to `dmn-js@16.3.0`

deps: update to `camunda-dmn-js@2.3.1`

### CODE REVIEW

**Comment by philippfromme** [comment]
Still a draft so I'll wait?

**Comment by barmac** [comment]
Oh OK it's failing on CI

**Comment by barmac** [comment]
Ready!

**Comment by barmac** [comment]
Known issue (missing feature): https://github.com/bpmn-io/dmn-variable-resolver/issues/15

**Review by philippfromme — APPROVED** [review]

**Pull request merged**
