### PR TITLE
feat(client/App): add file drop feature

### LINKED ISSUE #571: Dropping file (svg, xml, text) into any XML editor pastes text instead of opening the file
Camunda Modeler Version: 1.8.0

N.B. Could apply to all platforms

Two options:

* Dropping replaces XML contents
* Dropping allows opening new diagram

### LINKED ISSUE #1085: Restore file drop feature
__Is your feature request related to a problem? Please describe.__

As a user I want to open files by dragging and dropping on application window.

__Describe the solution you'd like__

Allow to drag a file and drop it on the app so that it is automatically opened. See: https://github.com/camunda/camunda-modeler/issues/607

Mind the bug on `master` that `file-drop.js` never stops to add event listeners.

__Describe alternatives you've considered__

🙊

### PR DESCRIPTION
**Pull request by barmac**
Closes #1085 
Closes #571

Regarding #571, dropping a text to XML editor is still possible, whereas dropping a file will trigger file opening action.

### CODE REVIEW

**Comment by barmac** [comment]
Resolved conflict and rebased on HEAD.

**Comment by philippfromme** [comment]
On Windows 10 when dropping a BPMN file onto the XML editor the file is opened but its also inserted into the XML editor:

foobar

**Comment by barmac** [comment]
I'll fix this and let you know.

**Comment by barmac** [comment]
@philippfromme please check now

**Comment by barmac** [comment]
@philippfromme 
I resolved the merge conflict so that it's ready for review again.

**Pull request merged**
