### PR TITLE
chore: update dependencies and changelog

### LINKED ISSUE #2982: Modeler 5.0 doesn't show multi-line fields for scripts anymore
### Describe the bug

The rework of the property panels in 5.0 doesn't support multi-line property fields anymore. This is needed when writing a script to be executed by a script worker (on Camunda Platform 8), or when working with JSON values.

### Steps to reproduce

1. Add a script task.
2. Give it type `script` so it can be picked up by https://github.com/camunda-community-hub/zeebe-script-worker for example.
3. Add a header `language` = `javascript`.
4. Add a header `script` and try to add a script there. There is only room for one line.

image

image

### Expected behavior

It should be possible to expand the input field so it can contain multi-line values. This is how it worked in Modeler 4.x and earlier.

### Environment

- OS: Ubuntu 22.04
- Camunda Modeler Version: 5.0
- Execution Platform: N/A (happens with Camunda Platform 7 and 8 BPMN files)
- Installed plug-ins: N/A

### Additional context

_No response_

### LINKED ISSUE #4419: Name text area doesn't auto resize if General tab isn't open
### Describe the bug

If General tab on properties panel isn't already open when selecting an element, the text area for name won't properly resize to fit multiple lines of text.

https://github.com/camunda/camunda-modeler/assets/24656920/4541be1f-9c7f-4a98-b159-ef27de5ab556

### Steps to reproduce

1. Create an element with multiline Name.
2. Close General tab in properties panel.
3. De-select the element.
4. Select the element and open General tab in properties panel.

### Expected behavior

Name text area should always resize to fit multiple lines of text.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

Related to https://github.com/bpmn-io/properties-panel/issues/314

### PR DESCRIPTION
**Pull request by jarekdanielak**
### Proposed Changes

- feat: change Header value and Field Injection value to text areas ([bpmn-io/bpmn-js-properties-panel#1065](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1065))
- feat: support Zeebe execution listeners ([bpmn-io/bpmn-js-properties-panel#1048](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1048))
- fix: improve behavior of text areas with `autoResize` property ([#4419](https://github.com/camunda/camunda-modeler/issues/4419))
- deps: update to `camunda-bpmn-js@4.14.0`
- deps: update to `@bpmn-io/properties-panel@3.22.3`
- deps: update to `bpmn-js-properties-panel@5.19.0`
- deps: update to `zeebe-bpmn-moddle@1.2.0`

Closes #2982
Closes #4419

### Checklist

To ensure you provided everything we need to look at your PR:

* [X] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [X] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
> Closes https://github.com/camunda/camunda-modeler/issues/3951 (@barmac)

This is not done yet; it's an epic with a couple of items still to close.

**Comment by nikku** [comment]
Let's follow our established practices for commits:

* Production dependency updates are marked as `deps: {WHAT DEPENDENCIES CHANGED}`, if possible grouped semantically (i.e. `deps: bump BPMN modeling dependencies`)
* Development dependency updates are marked as `chore: {UPDATE TEST DEPENDENCIES OR WHAT NOT}`

@jarekdanielak you can have a look into the [commit log](https://github.com/camunda/camunda-modeler/commits/develop/) to see how this usually is done.

**Comment by nikku** [comment]
@jarekdanielak I wonder what our strategy was in fixing this. I still see many places in the editor where multi-line is still not supported, but should be:

#### Missing multi-line support

* C7 - Any Task - Extension properties - value :arrow_right: no multi-line support
* C8 - Any Task - Extension properties - value :arrow_right: no multi-line support

#### Missing auto-resize:

* C7 - Service Task - Inputs - * - value :arrow_right: multi-line, but does not auto-resize for me:
  capture GTqTsO_optimized
* C7 - Service Task - Outputs - * - value :arrow_right: same like inputs
* C8 - Any Element - Example Data
* C8 - Any Element - Documentation
* C7 - Any Element - Documentation

So yea, while we partially fixed these bugs, we did not consistently addressed the user feedback. We could though :slightly_smiling_face:.

This relates to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/713. What I indicated there is that I think there is little value in keeping the existing "multi-line, but no auto-resize" behavior we have in some places, but instead rely on "auto-resize any multi-line field". We did not achieve that with the two incorporated fixes.

---

I don't see the new changes break anything, hence I'm happy to merge them. In the future I'd love to see us advance/clean up things in a more holistic manner :star_struck:.

**Comment by nikku** [comment]
Just for reference, another quirk I found in the auto-resize department: https://github.com/camunda/camunda-modeler/issues/4419#issuecomment-2247759501. Consider if it is worth to follow-up.

**Pull request merged**
