### PR TITLE
fix: save flag on handle change in xml editor

### LINKED ISSUE #1876: Cannot save diagram in XML view
__Describe the Bug__

when pasting stuff to a bpmn diagram in the xml view, I cannot use the keyboard shortcut ctrl + s in order to save the file

__Steps to Reproduce__

1. switch to xml view
2. paste something into the bpmn diagram --> e.g. <bpmn:message id="messageOne" name="Message_one" />
3. save the diagram by using the keyboard shortcur

__Expected Behavior__

save the diagram

__Environment__

- OS: Linux Mint 19.3 Cinnamon
- Camunda Modeler Version: 4.1.0

### PR DESCRIPTION
**Pull request by kerlon5**
Closes #1876

### CODE REVIEW

**Review by barmac — CHANGES_REQUESTED** [review]
Thanks for your contribution! Please make sure the commit message follows the [conventional commits guidelines](https://www.conventionalcommits.org/en/v1.0.0/) and also add a test case which verifies the solution:
* Diagram can be saved in the XML view.
* Diagram cannot be saved if it is not dirty.

**Comment by barmac** [comment]
This fixes most of the cases, but the diagram still cannot be saved if the change happens only in the visual (BPMN, DMN, Form) editor. Cf. 

https://user-images.githubusercontent.com/28307541/198255376-b7dfe1ff-482f-43e7-a9f5-b3dde7d7b557.mov

Notice that tab is dirty but the XMLEditor seems to consider it not dirty. Perhaps the "save" property should be handled in the MultiSheetTab instead as it can use information from both editors.

**Comment by barmac** [comment]
> ok, I'll see what we can do. also I have a question. If you open a bpmn diagram from disk, then you can save it multiple times in a row. Is this correct behavior?

I checked the files and it seems we always allow to save in BPMN, DMN, and Form editors. I couldn't find a test case which would confirm that this is expected, but the Modeler would behave like this in 4.12.0.

I don't see a reason why we should ever disallow to save file, so I think it's OK if you just change to allow save independently from the dirty state.

**Comment by kerlon5** [comment]
maybe save always set to true because of #2925

**Comment by barmac** [comment]
> maybe save always set to true because of #2925

Yes, I think it would be OK.

**Comment by kerlon5** [comment]
so, with the save flag setted to true you can save anytime in xml view. also updated tests. anything else on this?

**Review by barmac — APPROVED** [review]
Cool, thank you!

**Pull request merged**
