### PR TITLE
Redesign tab container

### LINKED ISSUE #2562: Redesign tab container
__What should we do?__

Adjust the tab container to the [new design](https://github.com/camunda/camunda-modeler-design/issues/43).

image

__Tasks__

* [ ] Remove borders of the existing tab container
* [ ] Ensure the container still fits other containers (data panel, properties panel, ...)

__Why should we do it?__

Contribute to the editor redesign.

---

Cf. [design issue](https://github.com/camunda/camunda-modeler-design/issues/43)
Child of https://github.com/camunda/camunda-modeler/issues/2461

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #2562

_New_
image

_Old_
image

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Note that the first tab link has no margin to the left after removing the border

image

We could fix that by adding some margin temporarily, but notice that we anyway restyle it via #2563.

**Comment by nikku** [comment]
I honestly do not see the difference between _old_ and _new_. :see_no_evil:

**Comment by pinussilvestrus** [comment]
Please refer to the referenced issue to see the requirements: https://github.com/camunda/camunda-modeler/issues/2562#issue-1057032368

>  * Remove borders of the existing tab container
 > * Ensure the container still fits other containers (data panel, properties panel, ...)
 
 This is a tiny preparation for the tab bar redesign, which requires the padding to be removed.

**Review by smbea — APPROVED** [review]
Looks nice.
I don't see much point in adding a margin now to then remove it later

**Review by andreasgeier — APPROVED** [review]
✅ LGTM

**Pull request merged**
