### PR TITLE
feat: build for arm64 on MacOS

### LINKED ISSUE #1996: I can run the App on ARM based Macs
__Is your feature request related to a problem? Please describe.__

Apple is going to release new ARM-based Mac books this fall. To my knowledge we do not ship ARM-based binaries for the Camunda Modeler yet.

__Describe the solution you'd like__

Be able to run the modeler on ARM as well as intel based architectures.

__Describe alternatives you've considered__

Ignore ARM as _too brand new_.

__Additional context__

This may be blocked by https://github.com/electron-userland/electron-builder/issues/5095, as electron builder does not build Mac binaries for ARM yet.

### LINKED ISSUE #4236: Cannot build application locally on MacOS (`spawnSync zip ENOENT`)
### Describe the bug

I cannot build the application locally due to an error: `⨯ spawnSync zip ENOENT  failedTask=build stackTrace=Error: spawnSync zip ENOENT`.

### Steps to reproduce

1. Be on Mac
2. Run `npm run build`
3. now this happens

### Expected behavior

It should work.

### Environment

- OS: MacOS Sonoma 14.4
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

Discovered by @jwulf 

Related to https://github.com/camunda/camunda-modeler/issues/1996

### PR DESCRIPTION
**Pull request by barmac**
Closes #1996
Closes #4236

### CODE REVIEW

**Comment by nikku** [comment]
Three years after opening https://github.com/camunda/camunda-modeler/issues/1996. Time seems to be right. :slightly_smiling_face:

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
Let's include an update server check to verify things still work.

**Comment by barmac** [comment]
The website links will need to be updated after the release: https://camunda.com/download/modeler/

I will create an issue and add it to the release issue.

**Comment by barmac** [comment]
Follow-up: https://github.com/camunda/camunda-modeler/issues/4239

**Pull request merged**
