### PR TITLE
deps: add missing `run-s` dependency

### PR DESCRIPTION
**Pull request by philippfromme**
To make the CI happy.

### CODE REVIEW

**Comment by nikku** [comment]
Why? This is added via `npm-run-all`, cf. https://github.com/mysticatea/npm-run-all#cli-commands.

**Comment by philippfromme** [comment]
Reported as missing here: https://github.com/camunda/camunda-modeler/actions/runs/6144039893/job/16668658882

**Comment by philippfromme** [comment]
Wait, it might actually be `run-s` reporting something else as missing. 🤔

**Comment by barmac** [comment]
`npm-run-all` adds binaries: `run-p` (run in parallel) and `run-s` (run in sequence). There is no need for `run-s`.

**Comment by nikku** [comment]
I'm currently verifying `npm run build -- --linux` works on Linux. It looks like it does, locally.

**Pull request closed without merging**
