### PR TITLE
Fix tooltip implementation does not match the designs

### LINKED ISSUE #1761: Tooltip implementation does not match the designs
__Describe the Bug__

Tooltip implementation does not match the designs. See the image:

Related to: https://github.com/zeebe-io/zeebe-modeler/pull/194

__Steps to Reproduce__

1. Open Deployment Tool
2. Type some invalid URL
3. Hover to the warning icon

__Expected Behavior__

Tooltip implementation matches the designs.

__Environment__

- OS: N/A
- Camunda Modeler Version: N/A

### PR DESCRIPTION
**Pull request by barmac**
Before:
before

After: 
after-after

__Which issue does this PR address?__

Closes #1761

### CODE REVIEW

**Comment by barmac** [comment]
@andreasgeier Can you please have a look?

**Comment by barmac** [comment]
Updated the PR with even smaller triangle. Previous fix:
after

**Comment by barmac** [comment]
Related to https://github.com/zeebe-io/zeebe-modeler/pull/194#issuecomment-609698874

**Comment by oguzeroglu** [comment]
Looks good from my perspective. We can merge this after Andreas approves!

**Comment by andreasgeier** [comment]
✅ Design review done. Tooltip arrow looks as expected.

**Pull request merged**
