### PR TITLE
deps: bump form-js@1.11.3

### PR DESCRIPTION
**Pull request by vsgoulart**
### Proposed Changes

 

Bump to `form-js@1.11.3`: [changelog](https://github.com/bpmn-io/form-js/blob/main/packages/form-js/CHANGELOG.md#1113)

Closes https://github.com/camunda/camunda-modeler/issues/4644

### Checklist

To ensure you provided everything we need to look at your PR:

* [ ] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
[CI fails](https://github.com/camunda/camunda-modeler/actions/runs/11591137372/job/32270232138?pr=4647#step:5:3599), because styles can no longer be found. Anything else that we changed to break this?

**Comment by vsgoulart** [comment]
@nikku Should be fixed now, I think the MacOS failure is not because of this PR, correct?

**Comment by nikku** [comment]
Correct, Ci failure is unrelated to your PR.

**Comment by nikku** [comment]
General feedback on this: We should probably move the hint to a tooltip: 

image

I already see tooltips used consistently in other places.

**Review by nikku — APPROVED** [review]
Works, I could not break it. Thanks for the contribution :sun_with_face: 

I stumbled upon the internally missing test coverage (https://github.com/bpmn-io/form-js/commit/983713584e817bb1e67e787302ea450c92bb0bec#r148545446), but also that we do not use the tooltip for meta-hints (https://github.com/camunda/camunda-modeler/pull/4647#issuecomment-2446782809).

Both are non blocking for this merge.

**Pull request merged**
