### PR TITLE
Prepare 5.13.0 release

### PR DESCRIPTION
**Pull request by nikku**
Updates what's new communication: 

image

Updates changelog.

### CODE REVIEW

**Review by barmac — APPROVED** [review]
Looks good to me

**Review by YanaSegal — APPROVED** [review]
Looks good :)

**Comment by philippfromme** [comment]
`The release improves the handling of broken diagram validation rules. We got you and your users covered in case you maintain a <a href="https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin">linter plug-in</a>.`

1. Shouldn't it be _This release_?
2. The second sentence sounds unprofessional. Camunda is not my bro. Also, how exactly am I covered? As a user who are my users? 🤔

**Comment by nikku** [comment]
@philippfromme Will change `The` to `This`. Regarding the second sentence, you're covered in a sense that we provide a reasonable and safe way for you to build + ship, but also to consume these lint rules. Is the following a better alternative?

> This release improves the handling of broken diagram validation rules, adding an additional safe-guard for authors and users of <a href="https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin">custom validation rules</a>.

Happy to incorporate an update into the final release.

**Comment by philippfromme** [comment]
> This release improves the handling of broken diagram validation rules, adding an additional safe-guard for authors and users of [custom linter rule plug-ins](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin).

Sounds much better!

**Pull request merged**
