### PR TITLE
Prepare 5.17.0 release

### PR DESCRIPTION
**Pull request by marstamm**
Dependency and changelog updates 

closes https://github.com/camunda/camunda-modeler/issues/3921, closes https://github.com/camunda/camunda-modeler/issues/3963, closes https://github.com/camunda/camunda-modeler/issues/2936

### CODE REVIEW

**Comment by marstamm** [comment]
We will also have to integrate the latest Linting, that's why it's a draft :)

**Comment by barmac** [comment]
DMN part is ready.

**Comment by barmac** [comment]
Let's add "Closes #2936" to the commits.

**Comment by nikku** [comment]
https://github.com/bpmn-io/diagram-js/issues/822 reproduces on the DEV build, too.

**Comment by nikku** [comment]
https://github.com/camunda/camunda-modeler/pull/3965#issuecomment-1798860155 is addressed via https://github.com/camunda/camunda-modeler/pull/3965/commits/f146b94cc9a9e203553f6fb45b93459e6ea70019.

**Review by nikku — APPROVED** [review]
Smoke tested and verified all diagrams worthings work.

:+1:

**Pull request merged**
