### PR TITLE
Privacy Preferences

### LINKED ISSUE #1543: Ask user for privacy preferences
__Is your feature request related to a problem? Please describe.__

As part of our automatic update check (#1541) we are going to send data to an update server to check, whether a new version of the app is available. We need to get the users consent, whether we are allowed to do that or not.

We take this as an opportunity to ask for three kinds of consent:

* Consent for update checks
* Consent for automatic crash reports
* Consent for anonymous analytics data

__Describe the solution you'd like__

* [x] If not asked before, ask the user about the privacy preferences:
    - whether to send crash reports
    - whether to send anonymous analytics data
    - whether to automatically check for updates
* [x] Store that information in the user configuration on her local disk

__Additional context__

Linked to [Prodpad idea](https://app.prodpad.com/ideas/207/canvas).

--- 

Child of #1541

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #1543

### CODE REVIEW

**Comment by barmac** [comment]
@oguzeroglu I left the plugin sketch on this branch: https://github.com/camunda/camunda-modeler/tree/1543-user-privacy-preferences

**Comment by barmac** [comment]
Screenshot 2019-11-21 at 12 15 02

I think we definitely should not make the checkboxes pre-checked per default. This is considered as a UX dark pattern by some authors ([link](https://www.interaction-design.org/literature/article/the-dark-side-of-ux)) and specifically in our case there are also doubts about if it's GDPR-compliant ([link](https://www.itgovernance.eu/blog/en/gdpr-when-do-you-need-to-seek-consent)). The point is that IMO it's hard to talk about consent if we require the user to actively protest against their data being collected. I think with enough reasons given we can rely on our users to agree on help without making choices for them.

**Comment by oguzeroglu** [comment]
@barmac I'm closing this as I re-implemented the same feature as a plugin here: https://github.com/camunda/camunda-modeler/pull/1597

**Comment by oguzeroglu** [comment]
d

**Pull request closed without merging**
