### PR TITLE
Refactor saving denied dialog

### LINKED ISSUE #977: Refactor Existing File Dialog
This is part of the overall dialog refactoring #959 

- remove hardcoded `existing-file` dialog in favor of reusable dialogs
- implement new dialog in a way that it is configured through the client

### PR DESCRIPTION
**Pull request by philippfromme**
* whenever there is an error when trying to open/save a file a dialog is shown
* contains a couple of refactorings

Closes #977

### CODE REVIEW

**Comment by barmac** [comment]
screenshot 2018-11-14 at 16 19 28

Steps to reproduce:

1. Open a file
2. Remove it from disc
3. Click on _disabled_ save button.

So there are two issues to fix:
1) No error message for `Error: ENOENT: no such file or directory` (IMO to fix in this PR)
2) Calling save callback for disabled button (separate issue [#1010](https://github.com/camunda/camunda-modeler/issues/1010))

**Comment by pinussilvestrus** [comment]
Closes #977

**Comment by barmac** [comment]
@philippfromme any update about this?

**Comment by philippfromme** [comment]
Unfortunately not. I have it on my list but won't be able to work on it until tomorrow at least. Bear with me.

**Comment by nikku** [comment]
Rebased on top of latest `next` branch.

**Comment by nikku** [comment]
@barmac How to reproduce error N.1, now as https://github.com/camunda/camunda-modeler/issues/1010 is fixed?

If there are no other concerns with the implementation I'm inclined to simply get this merged and create follow up issues for what is missing.

I guess there is more important downstream issues, i.e. fixing dirty state checking (which prevents us from saving at all right now).

**Comment by barmac** [comment]
@nikku Indeed, the save button is disabled after the file is deleted. I agree that it's time to merge it.

**Pull request merged**
