### PR TITLE
Implement concept for modal windows

### LINKED ISSUE #1681: Implement concept for Modal windows
This is a status issue for what I am working on at the moment.

__What should we do?__

* [x] Location: It needs to appear upper half of the screen, 110px from the top and 60px from the bottom per default in a 1440x1024 screen. As the size of the viewport changes, the modal window will be centered in the viewport accordingly and the top position of the modal will be relocated.
* [x] Resizing: If the modal window needs to grow for adding more elements, then the modal window height will be increased from the bottom. Top position of the modal window will not change by adding more elements in the modal.
* [x] Scrolling: When the modal window hit the maximum distance to the bottom of the viewport then the content will be scrollable. The modal window itself should be visible all the time (header, content and buttons area).
* [x] Size: Width of the window will be static and be 636px [this is not a final value yet]. Height of the window will be dynamic.
* [x] Closing: User can close the window by clicking Close icon (X), Close / Cancel button and  pressing ESC key. Dismissible modals (click on background closes modal) should not be allowed.
* [x] Submitting: Primary action should be triggered by Enter key if the focus in on the button.
* [x] Buttons: If only one option exists, this option should be primary button ("Close") and can be triggered by ESC / Enter buttons.
* [x] Focus: 
  * [x] Trap: Keyboard focus needs to stay in the modal window, focus should not reach elements behind the modal window.
  * [x] Background: While modal window is visible, darken the background with a transparent overlay to help user to concentrate on modal.
* [x] Implement new look
  * [x] layout

Some of the items are already implemented.

__Why should we do it?__

We want modals to look and feel good.

---

Child of https://github.com/camunda/camunda-modeler/issues/1609

### PR DESCRIPTION
**Pull request by barmac**
Summary of changes:
* Close button is now focusable.
* Close by background click is removed.
* Modal has a fixed width.
* Header, body and footer are now visibly separated.
* Modal keeps responsiveness for smaller screens.
* In case of content being higher than maximum height,
  modal body is scrollable.

Closes #1681 
Closes https://github.com/camunda/camunda-modeler/issues/1575

### CODE REVIEW

**Comment by barmac** [comment]
Umm I missed the close icon hover/active style. Let me fix that.

**Comment by barmac** [comment]
@nikku @nazlikaya Ready for review

**Comment by nikku** [comment]
Some visual impressions:

image

image

image

**Comment by nikku** [comment]
Looks good from the feel perspective.

**Comment by nikku** [comment]
Added two minor fixes on top.

**Comment by philippfromme** [comment]
Looking goood! 👍

**Comment by barmac** [comment]
Noticed: missing X button for some modals

**Comment by barmac** [comment]
Screenshot 2020-02-11 at 10 05 02

This needs to be clarified. Not sure what could be the meaning of X button in case of privacy preferences.

**Comment by nikku** [comment]
> This needs to be clarified. Not sure what could be the meaning of X button in case of privacy preferences.

This is by design. The user may not close the dialog via ESC or close button. Instead, she has to explicitly confirm what is written there (provide consent).

**Comment by barmac** [comment]
> > This needs to be clarified. Not sure what could be the meaning of X button in case of privacy preferences.
> 
> This is by design. The user may not close the dialog via ESC or close button. Instead, she has to explicitly confirm what is written there (provide consent).

Exactly.

**Comment by nazlikaya** [comment]
Enter needs to trigger the Primary button, only if the primary button is on focus.

**Comment by barmac** [comment]
> Enter needs to trigger the Primary button, only if the primary button is on focus.

That's how it works right now, right?

**Comment by barmac** [comment]
I added `X` button for Privacy Preferences when they are already saved somehow (so not for the first startup modal).

**Comment by nikku** [comment]
:cake:

**Pull request merged**
