### PR TITLE
fix(tabs-provider): change order of bpmn providers

### LINKED ISSUE #2130: When you save a Zeebe diagram with unknown extension, it opens as a Camunda diagram
__Describe the Bug__

When you save a Zeebe diagram with unknown extension, it opens as a Camunda diagram.

__Steps to Reproduce__

1. Create a Zeebe diagram.
2. Save file as `diagram.foo`.
3. Close the diagram and reopen it.

__Expected Behavior__

It should open as Diagram (Zeebe).

__Environment__

- OS: MacOS
- Camunda Modeler Version: `develop`

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Take `cloud-bpmn` first, `bpmn` as fallback

Closes #2130

### CODE REVIEW

**Comment by philippfromme** [comment]
So the idea is the `camunda-cloud` is more specific than `bpmn`, right?

**Comment by pinussilvestrus** [comment]
Yes, exactly

**Review by barmac — APPROVED** [review]
✅

**Comment by barmac** [comment]
oops

image

**Pull request merged**
