### PR TITLE
fix(client): show open file error dialog if tab couldn't be created

### LINKED ISSUE #1314: No feedback when dropping non-empty file
drop-compressed

__Steps to Reproduce__

1. Drop non-empty file (e.g. txt)

__Expected Behavior__

I get feedback that the file could not be opened.

__Actual Behavior__

I get NO feedback that the file could not be opened.

__Environment__

Please complete the following information:

 - OS: Windows 10
 - Camunda Modeler Version: 3.0.0-beta.3

### PR DESCRIPTION
**Pull request by philippfromme**
* if tab couldn't be created for whatever reason we show a generic error to the user
* add documentation for isDroppableItem

Closes #1314

### CODE REVIEW

**Comment by barmac** [comment]
Screenshot 2019-03-20 at 16 19 02
This is what happens in dev mode 🤯

**Comment by philippfromme** [comment]
@barmac Yes, because

```
"app:dev": "electron ./app/dev.js resources/diagram/simple.bpmn",
```
🤣

**Comment by barmac** [comment]
I pushed a commit to resolve this problem.

**Comment by barmac** [comment]
Should we display an error dialog for each file which cannot be opened?

**Comment by philippfromme** [comment]
@barmac Yes, I think so. If you try to open multiple files it would be nice to know which ones could not be opened.

**Comment by barmac** [comment]
On MacOS I get only one dialog. Also, dialog for namespace conversion is not displayed if there was an error in other file. The effect is a never ending loader :(

**Comment by philippfromme** [comment]
@barmac I can't reproduce that on Windows 10. I'm getting a dialog for every file.

dialogs-compressed

**Comment by philippfromme** [comment]
@barmac You should now get one dialog after another. The missing `return` in [this line](https://github.com/camunda/camunda-modeler/pull/1320/files#diff-5ee2f0ebccac2c66c29c469ca0b70d86R51) meant that awaiting dialogs didn't work.

**Comment by philippfromme** [comment]
@nikku Can you take over the review?

**Comment by nikku** [comment]
Merged via https://github.com/camunda/camunda-modeler/commit/5d776f2ae8f7ae0f93f02d29487a896e2fc235f2.

**Pull request closed without merging**
