### PR TITLE
Update modeling deps

### LINKED ISSUE #4590: Support user task listeners
### What should we do?

Implement user task listeners in Camunda 8

```xml
<userTask id="my_user_task" name="my_user_task">
 <extensionElements>
   <zeebe:userTask/>
   <zeebe:taskListeners>
     <zeebe:taskListener eventType="create" type="create_listener" retries="2"/>
     <zeebe:taskListener eventType="assignment" type="assignment_listener"/>
     <zeebe:taskListener eventType="update" type="update_listener" retries="8"/>
     <zeebe:taskListener eventType="complete" type="complete_listener"/>
   </zeebe:taskListeners>
   <zeebe:priorityDefinition/>
   <!--other extension props e.g. assignmentDefinition, priorityDefinition-->
 </extensionElements>
 <!--other props-->
</userTask>
```

* [x] I can define task listeners on user task
  * [x] type (string, FEEL expression)
  * [x] eventType: `complete`, `assignment`
  * [x] retries (string, FEEL expression, default is 3)
* [x] TLs can be used in Camunda 8.7 or newer
* [x] When I switch from Zeebe user task to job worker, the task listeners are removed

Projects:
* [x] https://github.com/camunda/zeebe-bpmn-moddle/pull/67
* [x] https://github.com/camunda/camunda-bpmn-js-behaviors/pull/88
* [x] https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1088
* [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/181
* [x] https://github.com/camunda/linting/pull/123

### Why should we do it?

Product hub epic: https://github.com/camunda/product-hub/issues/1316

### PR DESCRIPTION
**Pull request by nikku**
### Proposed Changes

Updates to `camunda-bpmn-js@5.2.0`, addressing the following issues:

Closes https://github.com/camunda/camunda-modeler/issues/4182
Closes https://github.com/camunda/camunda-modeler/issues/4658
Closes https://github.com/camunda/camunda-modeler/issues/4122
Closes https://github.com/camunda/camunda-modeler/issues/3439
Closes #4590

_Highlight - Search ships with improved UX:_

capture jmYxG3_optimized

_Prioritizing exact and start matches:_

capture azK1wN_optimized

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [x] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

----

Depends on https://github.com/camunda/camunda-modeler/pull/4620

### CODE REVIEW

**Comment by barmac** [comment]
This will also close https://github.com/camunda/camunda-modeler/issues/4590

**Comment by nikku** [comment]
@barmac I believe to close https://github.com/camunda/camunda-modeler/issues/4590 we need to incorporate linting, too?

**Comment by barmac** [comment]
Right!

**Comment by jarekdanielak** [comment]
Modeler freezes when I search for a whitespace: `SyntaxError: Unexpected end of JSON input`

**Comment by nikku** [comment]
@jarekdanielak great find :medal_sports: 

I was able to reproduce it; I think it is reasonable to ignore whitespace for the sake of searching, and whitespace only should not trigger a search (at all).

Find the fix here: https://github.com/bpmn-io/diagram-js/pull/954

**Comment by nikku** [comment]
I'll integrate fixed versions of the dependencies shortly.

**Comment by barmac** [comment]
Linting / user task listeners added via https://github.com/camunda/camunda-modeler/pull/4711/commits/77c84b1c8029e728b918d33cd5fab29eb04f7aac

**Comment by barmac** [comment]
BTW shouldn't we mention the search improvements in the general part of changelog? They affect dmn-js-drd partially.

**Comment by nikku** [comment]
All bugs fixed :heavy_check_mark:, `camunda-bpmn-js@5.2.1` is in :rocket:

**Comment by nikku** [comment]
Verified user task listeners are in, too :checkered_flag:

**Review by barmac — APPROVED** [review]

**Pull request merged**
