### PR TITLE
1235 notify third parties for changes in the license book

### LINKED ISSUE #1235: Notify third parties for changes in the license book
As part of our license process we must notify third parties, e.g. LEGAL with every change in the license book (or with every release we ship that may introduce changes in the license book).

Carried out as a post-release step, cf. [`SRE-403`](https://app.camunda.com/jira/browse/SRE-403).

### PR DESCRIPTION
**Pull request by barmac**
Closes #1235

### CODE REVIEW

**Comment by barmac** [comment]
Note for reviewer: We use [diff package](https://www.npmjs.com/package/diff) due to broken behaviour of Node's child_process module when `diff`ing big files.

**Comment by barmac** [comment]
@philippfromme ready.

**Comment by nikku** [comment]
> We use diff package due to broken behaviour of Node's child_process module when diffing big files.

What is the broken behavior and why / how does it apply to setup?

**Comment by barmac** [comment]
Previously, I tried to use execa.sync to generate diff:
```javascript
const exec = require('execa').sync;

const diff = exec('diff', ['-u', '-', file], { input: anotherFile }).stdout;
```
However, it always throws error when the files differ. `diff` simply exits with 1 for not identical files and it's considered as error for `child_process` and `execa` 🙄. Cf. https://github.com/nodejs/node/issues/19494#issuecomment-374721063.

Anyway, the alternative would be to read `stdout` from error which feels hacky for me.

**Comment by nikku** [comment]
Thanks for the note. 

I'd personally prefer built-in utilities, especially if the alternative is to require another dependency that is really only required on the CI.

Just to understand correctly, what we'd need is something like this, right?

```javascript
const exec = require('execa').sync;

async function computeDiff(file, otherFile) {

  // diff exits with <1> if a diff exists; we must account for that special behavior
  // cf. https://github.com/nodejs/node/issues/19494#issuecomment-374721063
  try {
    return exec('diff', ['-u', '-', file], { input: otherFile }).stdout;
  } catch (e) {

    if (e.code !== 1) {
      throw e;
    }
    
    return e.stdout;
  }
}
```

**Comment by philippfromme** [comment]
Should I review this or not?

**Comment by barmac** [comment]
@nikku Correct, this is more or less what I wrote before.

@philippfromme I'll include Nico's suggestion and then it's ready. Just a sec.

**Comment by barmac** [comment]
@philippfromme ready

**Pull request merged**
