### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by nikku**
Based on https://github.com/camunda/camunda-modeler/pull/2064, this updates our app as well as app test dependencies.

### CODE REVIEW

**Review by pinussilvestrus — CHANGES_REQUESTED** [review]
`npm run dev` crashes for me on macOS 10.15

<details>
  <summary>Open for logs</summary>

```log
/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron[29506]: ../../third_party/electron_node/src/node_platform.cc:444:std::shared_ptr<PerIsolatePlatformData> node::NodePlatform::ForIsolate(v8::Isolate *): Assertion `data' failed.
 1: 0x10d83cb15 node::Abort() [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10d83c89f node::Assert(node::AssertionInfo const&) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10d8a3f97 node::options_parser::SplitHostPort(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x108dce225 v8::internal::GlobalHandles::InvokeOrScheduleSecondPassPhantomCallbacks(bool) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x108dce42f v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x108bcbaef v8::internal::Heap::CreateFillerObjectAt(unsigned long, int, v8::internal::ClearRecordedSlots, v8::internal::ClearFreedMemoryMode) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x108bc9772 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x108bd4bda v8::internal::Heap::PromotedExternalMemorySize() [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x108bd4fc1 v8::internal::Heap::PromotedExternalMemorySize() [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x108dd8d82 v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x108fa02ff v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x1090a2287 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x1096a1c19 v8::internal::compiler::ZoneStats::ReturnZone(v8::internal::Zone*) [/Users/niklas.kiefer/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
```
</details>

**Comment by pinussilvestrus** [comment]
@barmac maybe you can reproduce this as well? Not urgent of course #springcleaning 🧹

**Review by barmac — APPROVED** [review]
It works on my machine ¯\_(ツ)_/¯

**Review by pinussilvestrus — APPROVED** [review]
Worked after restarting my computer.

:-))

**Pull request merged**
