### PR TITLE
feat(update-checks): display errors

### LINKED ISSUE #2086: As a user, I'd like to know when an update check triggered by me fails
__Is your feature request related to a problem? Please describe.__

When I trigger update check and there are network problems or the update server responds with anything but 200, it fails silently and the user can only notice it via console. 

__Describe the solution you'd like__

Show a notification on such problems.

__Describe alternatives you've considered__

Leave it as it is.

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Displays update check errors inside the Log View and via Notification (if actively triggered).

Bildschirmfoto 2021-04-16 um 13 37 51

Closes #2086

---

I decided to do it the same as we handle deployment errors: display the error in the Log View instead of the Notification contents. Errors thrown by the Update Server can differ in the number of details they reveal.

### CODE REVIEW

**Comment by andreasgeier** [comment]
I assume it is about the _Modeler_ update check. However, this might be not clear enough in the message since we also have template versions for instance. My first thought was that it is about a template within the opened diagram.

Maybe the text could be more precise by something like _Modeler Update Check_

Another thought, maybe already considered, maybe out of scope for this PR: as a user, I would expect such a message only in case a manual update check was triggered. If auto check is enabled, I would expect the Modeler to not inform me but retry in a defined interval.

**Comment by pinussilvestrus** [comment]
Good points 👍 

Let's update the titles to make them more explicit. Regarding the "when-to-display": How would I recognize that update checks are failing when I never press this button?

If I think a bit about it: update checks should _ be simply working_ in the background, without any noise. If they don't, we shouldn't notify the user any time. A manual check is a good place to really get visual feedback if I want to. So I agree 👍

**Comment by andreasgeier** [comment]
> If I think a bit about it: update checks should _ be simply working_ in the background, without any noise.

Yes, this was my thought. But if the check returns true, we need to inform and ask the user. I can imagine we consider this as part of the planned topic "What's new", then we have version information and an update indicator in the status bar and can do all this communication and interaction there.

**Comment by nikku** [comment]
My two cents: Let us not display the update check errors, unless the user explicitly triggered the check.

If check explicitly triggered => Get feedback in _any_ case. 

If check is happening in background => Do not disturb users with errors. Still, the errors should end up in the persisted application log, if that is feasible.

**Comment by pinussilvestrus** [comment]
Thanks both, I will update it accordingly 👍

**Comment by pinussilvestrus** [comment]
I updated the behavior in a way it only displays notifications if actively triggered. Otherwise, it won't show anything to the user (silent background checks).

I also structured the tests a bit more in visuals and actual update checks.

**Comment by barmac** [comment]
I agree with Nico. See my comment https://github.com/camunda/camunda-modeler/issues/2086#issuecomment-821115311

**Comment by andreasgeier** [comment]
> I updated the behavior in a way it only displays notifications if actively triggered. Otherwise, it won't show anything to the user (silent background checks).

Just to ensure I understood correctly: with silent background checks, you refer only to errors, not success messages ("new update available"), right?

**Comment by pinussilvestrus** [comment]
Excactly. 👍

**Comment by pinussilvestrus** [comment]
any chance to get this thing merged?

**Review by barmac — APPROVED** [review]
LGTM

**Review by andreasgeier — APPROVED** [review]
LGTM

**Pull request merged**
