### PR TITLE
deps: update to latest Electron

### PR DESCRIPTION
**Pull request by marstamm**
- bump to latest electron version and fix userPath to be consistent across all devices
- run `npm audit fix` while we're at it

Builds to test:
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2538-update-electron/camunda-modeler-2538-update-electron-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2538-update-electron/camunda-modeler-2538-update-electron-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2538-update-electron/camunda-modeler-2538-update-electron-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2538-update-electron/camunda-modeler-2538-update-electron-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2538-update-electron/camunda-modeler-2538-update-electron-win-x64.zip

----

#### Works on 

* [x] MacOS @smbea 
* [x] Linux @nikku @marstamm
* [x] Windows

### CODE REVIEW

**Comment by nikku** [comment]
I can confirm it works for me (Linux), too.

**Comment by marstamm** [comment]
Let's check if for windows as well (/cc @Skaiir, @philippfromme)

**Comment by Skaiir** [comment]
Works a charm, both 32 and 64 bits

**Comment by marstamm** [comment]
Thank you!

Integration test done, leaving it open for code review

**Comment by nikku** [comment]
Code great!

**Pull request merged**
