### PR TITLE
chore: move release issue creation to gh-action

### PR DESCRIPTION
**Pull request by marstamm**
related to https://github.com/bpmn-io/fake-join/pull/44

### CODE REVIEW

**Comment by marstamm** [comment]
https://github.com/bpmn-io/actions/ is currently internal. Camunda should have access to it, but if it fails we can make it public if needed

**Comment by pinussilvestrus** [comment]
Should that maybe go to `master`?

**Comment by marstamm** [comment]
will rebase 👍

**Comment by marstamm** [comment]
Let's wait for the CI to run through again an then merge

**Pull request merged**
