### PR TITLE
Improve notifications

### LINKED ISSUE #2607: Improve Notifications
> this is an epic issue that might be broken down into specific tasks

__What should we do?__

Redesign notifications of deploy + start instance to match new UI - https://github.com/camunda/camunda-modeler-design/issues/38

Also consider https://github.com/camunda/camunda-modeler/issues/1827

__To Do:__
* update UI of notifications
   * placement + animation
* expand deploy notification description to include `deployment ID`
    * (maybe) link to cockpit (deployment section) or link to run

- update cloud-connect-plugin notifications to match new UI - https://github.com/camunda/cloud-connect-modeler-plugin/pull/72
  - add error notifications for invalid credentials and cawemo connection
  - match text and letter cases to new UI

__Why should we do it?__

That's part of our one Visual IDE efforts.

### PR DESCRIPTION
**Pull request by smbea**
Closes #2607 
**Design issue:** https://github.com/camunda/camunda-modeler-design/issues/38

Artifacts:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/notifications/camunda-modeler-notifications-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/notifications/camunda-modeler-notifications-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/notifications/camunda-modeler-notifications-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/notifications/camunda-modeler-notifications-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/notifications/camunda-modeler-notifications-win-x64.zip

[cloud-connect] - https://github.com/camunda/camunda-modeler/files/7702545/cloud-connect-3.2.1.zip

<hr/>

For the deploy + start instance notifications, the goal is to give meaningful feedback to the user, that can help them in the following step, instead of just displaying "Successed". For this, I added links to Cockpit/Operate and relavant IDs (`process definition id` and `process instance id`).

https://user-images.githubusercontent.com/25825387/145778823-be62dc9a-ee87-41b7-9d30-11deba656e06.mov

__Platform:__

__Cloud:__

### CODE REVIEW

**Comment by smbea** [comment]
@andreasgeier Ready for review. Please also give your review on the ID's are being displayed

**Comment by nikku** [comment]
My quick and personal feedback on the UI you've attached:

* this goes into a great direction (ensuring users are not stuck!) :tada: :partying_face: 
* consider ID without space
* does the notification stay open if it is mouse focussed (so I can copy and paste IDs, if possible)?
* consider renaming "deplyyment successed" -> "Process Definition(s) deployed"
* consider simplifying ID description => it shall be obvious from the error message; detailed information can be contained in the title tag of the ID:
    * Process Instance started => ID = Process Instance ID
    * Process Definition Deployed => ID = Process Definition ID

**Comment by smbea** [comment]
Thank you for your feedback @nikku. Generally, I agree with your feedback and will look into these suggestions.


> consider renaming Process ID => Process Definition ID (or whatever is talked about in cloud / platform context; it is Process Definition in Platform context)

For cloud, the response returns a `bpmnProcessID` and a `processKey` for deploy. I used the `bpmnProcessID` and Process ID because we do so in the codebase when naming variabled (but that's just for us, of course) . Would it make sense to display these two?

**Comment by nikku** [comment]
I think we should pick one and wait for feedback accordingly.

**Comment by andreasgeier** [comment]
Design review based on your artifact:

- the messages disappear too fast (~3 s), double the time to 6 sec
- keep messages open on mouse over, except the user clicks on the close icon
- it seems that a process ID is only shown once, it's not shown on additional deployments of the same unchanged process
- ensure that the notification type icon on the left and the close icon on the right always appears on the same position (from top and left respectively right edge) regardless of the content of the message. Do not align it centered to the title which could have multiple lines.
- enable hover state for close icon
- I like the proposed style for the code snippets. Do not include whitespaces before or after the ID as part of the code snippet but ensure there is a whitespace between the code snippet and the other text content.
- optional: the animation is not smooth. The message appears half visible and starts to animate then. Could you change so that the animation begins outside of the view and we have a complete slide-in?

@smbea Please note that I was not able to check all types of messages and all cases. So I considered your screen recording for review, too. Ideally, we should have a list of all messages including their content so I could also check that. I would leave this decision to you, depending on the effort.

@nikku Do you think the link target for deployed processes is the best option? What about linking to the runtime view instead (Dashboard > Processes > Process Name: Runtime)? In case we are not sure what is prefered we could provide both links like:

Go to Cockpit > Deployment
Go to Cockpit > Runtime

The target for new instances is the history view. Shouldn't we link to runtime instead since history is ee only? Or, we could use the same link targets as we do for processes.

**Comment by nikku** [comment]
Andi, thank you so much for this detailed review :pray:. 

> The target for new instances is the history view. Shouldn't we link to runtime instead since history is ee only? Or, we could use the same link targets as we do for processes.

That is my proposal, too. We shall not link to EE-only features (i.e. the history view). On the other hand, quickly running processes are not available on the runtime view anymore. I believe that is something to be fixed on Cockpit side: If the process completed (and EE History is available), a link from the run-time view to the (still existing) history view shall be provided.

> @nikku Do you think the link target for deployed processes is the best option? What about linking to the runtime view instead (Dashboard > Processes > Process Name: Runtime)? In case we are not sure what is prefered we could provide both links like:

To answer this question I'd think about the user intend: What is the view that allows the user to get most information out of the information? Let's use that. Also, let's iterate over it. If we don't know and could be better, we'll get feedback.

**Comment by ingorichtsmeier** [comment]
Hi @nikku,

> I believe that is something to be fixed on Cockpit side: If the process completed (and EE History is available), a link from the run-time view to the (still existing) history view shall be provided.

this is already implemented (at least in the EE cockpit). If you open a completed process in the runtime view, you see a link to open the history view: 

grafik

**Comment by nikku** [comment]
@ingorichtsmeier Thanks for chiming in! So then, :heavy_plus_sign: :five: for showing CE.

**Comment by smbea** [comment]
> @andreasgeier: it seems that a process ID is only shown once, it's not shown on additional deployments of the same unchanged process

This is a platform-side issue. We only receive an answer for the first deployment with a specific deployment name. I believe, by the second deployment with the same name, the id's are reused but the deployment version is increased. We also don't receive this version in the response so there isn't much we can do on our side.

<hr/>

**For the deployments link:**
Through the current link, the user can also get to the process runtime. I believe this view is important for when we use the "Additional files" feature, because this generates one process definition for each:

https://user-images.githubusercontent.com/25825387/145994965-f4612013-bb14-44e7-9910-58d84672e4ae.mov

<hr/>

**Regarding the process instances link:**
This is already implemented. If the process instance is  still running, it will go to that view, otherwise it defaults back to the history, as shown by Ingo.

**Comment by smbea** [comment]
Regarding the other UI aspects mentioned (@andreasgeier ), I addressed these in the new pushed changes.

**Comment by andreasgeier** [comment]
@smbea 

I could not trigger a notification with a multi line title but I trust you that you fixed the position of the icons 🙂 

In the screen recording you can see that the animation is still not smooth, jump sometimes, and sometimes there is even a scroll bar for a moment. See recording below.

But since we do not aim for perfection in a first increment this state is good enough 👍 

✅ &nbsp; Approved

https://user-images.githubusercontent.com/938244/146034198-703ba4a4-d540-43af-a2b8-2823053072e4.mov

**Review by andreasgeier — APPROVED** [review]

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
A major improvement :clap:

**Comment by smbea** [comment]
I was able to fix the scroll and here is an example of what a long title would look like:

image

**Pull request merged**
