### PR TITLE
fix(example): rename camunda:javaDelegate to camunda:class

### PR DESCRIPTION
**Pull request by falko**
camunda:javaDelegate does not exist: https://docs.camunda.org/manual/7.5/reference/bpmn20/tasks/service-task/#camunda-extensions

### CODE REVIEW

**Comment by nikku** [comment]
Good catch. Thx.

**Comment by falko** [comment]
After studying this further I'm not so sure any more: Are we referencing actual XML attributes here or rather internal IDs of widgets in the property panel?

**Comment by nikku** [comment]
Did you try it out?

**Comment by falko** [comment]
Now, I did try it...

Binding to a property from a different namespace, doesn't produce anything in the XML:

      "binding": {
        "type": "property",
        "name": "foo:bar"
      }

Binding to any property in the camunda namespace...

      "binding": {
        "type": "property",
        "name": "camunda:foo"
      }

...does produce XML, but will obviously not work in the engine:

     <bpmn:serviceTask id="Task_0ya5e77" camunda:foo="com.mycompany.MailTaskImpl" camunda:modelerTemplate="com.camunda.example.MailTask" >

This is explains why `camunda:javaDelegate` showed up in the XML, but it should obviously be `camunda:class`

**Pull request closed without merging**
