### PR TITLE
Pass tenant ID to run

### PR DESCRIPTION
**Pull request by nikku**
Closes https://github.com/camunda/camunda-modeler/issues/4016

### CODE REVIEW

**Comment by smbea** [comment]
@nikku please target master

**Comment by nikku** [comment]
This turned out to be impossible to "simply test", so I executed an integration test to verify the following (through [MT enabled camunda/camunda-platform self-managed setup](https://github.com/camunda/camunda-platform/pull/429/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L215)):

* With MT enabled the field is mandatory, or else there is an error in the logs
* Without MT enabled the field shall not be filled, or else there is an error in the logs

---

I likely ran into https://github.com/camunda/camunda-modeler/issues/4021 as the problems panel did not update.

**Comment by nikku** [comment]
Currently investigating test failures.

**Comment by nikku** [comment]
Green, against `master` :checkered_flag:

**Pull request merged**
