### PR TITLE
feat: allow collapsed subprocess in 8.4

### LINKED ISSUE #4020: Support collapsed subprocesses in C8
_Implementation task for https://github.com/camunda/product-hub/issues/294._

### Problem you would like to solve

Camunda 8 (target version pending) is going to support collapsed sub-processes. Our tool should reflect that.

### Proposed solution

Enable support for collapsed subprocesses in C8:

* [x] Validation allows collapsed sub-processes for `8.4`
* [x] Validation disallows collapsed sub-process with aligned message `Only supported in 8.4 and newer` for older Camunda versions.

Follow-up in Web Modeler:

* [ ] Allow collapsed sub-process modeling (already allowed in Desktop Modeler) - https://github.com/camunda/web-modeler/issues/2969

### Alternatives considered

None.

### Additional context

We currently support modeling already, but mark the sub-process as "unsupported", using an outdated message:

image

### PR DESCRIPTION
**Pull request by barmac**
deps: update `@camunda/linting`

Closes #4020

### CODE REVIEW

**Comment by barmac** [comment]
Hmm is this a problem?

image

**Comment by barmac** [comment]
I'd say we don't care about this edge case. The point is that ad-hoc subprocess is not likely to be supported in automations. Somebody has to choose the activity to execute anyway.

**Comment by nikku** [comment]
What should be a problem about https://github.com/camunda/camunda-modeler/pull/4029#issuecomment-1855828134?

**Comment by philippfromme** [comment]
I guess the proper fix would be a configuration option for the `collapsed-subprocess` rule similar to the `element-type` rule so all currently known versions only check subprocesses.

**Comment by barmac** [comment]
It says it's allowed but it's not.

**Comment by barmac** [comment]
On the other hand, "must be expanded" is also misleading. Same as "must have a start event". It's not supported anyway.

**Comment by nikku** [comment]
@barmac I'm not sure if this is ready to be merged, given what you discussed? Please give me a heads-up and we can proceed :star_struck:

**Comment by barmac** [comment]
I'll rebase this and IMO we can proceed. See https://github.com/camunda/product-hub/issues/294#issuecomment-1857716754

**Review by nikku — APPROVED** [review]
Works as intended, great stuff!

image

**Pull request merged**
