### PR TITLE
Gracefully handle creating milestone with existing name

### PR DESCRIPTION
**Pull request by misiekhardcore**
### Proposed Changes

 

- add some basic error handling to the `create milestone` action, to gracefully handle the case when we try to create a milestone that already exists (e.g. https://github.com/camunda/camunda-modeler/actions/runs/11072955308/job/30768404834)

related to https://github.com/bpmn-io/internal-docs/issues/1052

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [x] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
@misiekhardcore Please use the `ci:` prefix to tag CI related things.

**Comment by nikku** [comment]
@misiekhardcore CI failures should have been addressed via https://github.com/camunda/camunda-modeler/pull/4640. 

How did you test these changes?

**Comment by misiekhardcore** [comment]
@nikku what should I tag with `ci:`?
I tested these changes by creating a bash script locally, with the changes I then put in the action. I was able to create milestone successfully, then when I tried to do it again it was also handled gracefully with the new message, the `else` should then catch all the remaining error states, print them and `exit 1`

**Review by nikku — APPROVED** [review]
Let's try this out; I don't have immediate ideas how to simplify it. 

Thanks for your contribution.

**Comment by nikku** [comment]
I changed the commit message to 

`ci: ...` to reflect this as a CI change.

**Comment by misiekhardcore** [comment]
ah, alright, you meant the commit message. I will keep that in mind for the future.
regarding the implementation I didn't come up with cleaner solution either. Bash is pretty limited if we want the script to be simple and understandable

**Pull request merged**
