### PR TITLE
fix: handle bad request for update check

### PR DESCRIPTION
**Pull request by kerlon5**
400 Bad Request handler for #2999

### CODE REVIEW

**Comment by marstamm** [comment]
Hi @kerlon5 , thank you for tackling this issue.

The code looks good, but is missing a test. Please consider adding a test case. You can use one of the existing Cases as a starting point. 

https://github.com/camunda/camunda-modeler/blob/6960d4b578b4cd497ecdaef7f8210fe420d1a751/client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js#L282-L301

Let me know if you have further questions 🙂

**Comment by kerlon5** [comment]
@marstamm hi, I was struggling with this test, it would be nice if you help me to handle it. For a proper test we need to mock the fetch call inside sendRequest. But I can't figure out how to do it. [on this line](https://github.com/camunda/camunda-modeler/blob/74ecb39b006582eaf3480aa0ef739bdf708318d9/client/src/plugins/update-checks/UpdateChecksAPI.js#L32)

**Comment by marstamm** [comment]
Hi @kerlon5 ,

I added a unit test that tests the server response. Can you have a look? Cf. 167ad1dce8f86c8545f0d4e56c6b5d075eeee41d

**Comment by kerlon5** [comment]
@marstamm I have made runs of this test, looks great. Can it be merged like this, or should I make it all as a single commit?

**Comment by marstamm** [comment]
I will squash the commits and merge it. Thanks for your contribution 🙂

**Pull request merged**
