### PR TITLE
Status bar initial implementation

### LINKED ISSUE #2175: Implement status bar (step 1)
__What should we do?__

- [ ] Status bar is present.
- [ ] XML button toggles XML view.
- [ ] Log button toggles the log.
- [ ] Log is opened above the status bar.
- [ ] Show the engine profile as non-clickable status text.
- [ ] For an empty tab, display log button only.

__Why should we do it?__

We want to improve the UI.

Related to https://github.com/bpmn-io/internal-docs/issues/222

### PR DESCRIPTION
**Pull request by barmac**
Closes #2175

### CODE REVIEW

**Comment by barmac** [comment]
During today's meeting with @andreasgeier, we decided on the next steps:

* I'll update the branch to use a light status bar.
* For Monday, I'll provide an application build which can be used for experiments with the colors.
* My next step will be to implement the status bar overlay with Engine Profile specifically.

**Comment by nikku** [comment]
Clean implementation, I like :+1:.

One tiny issue: The engine profile does have a different font-size, resulting in a slight miss-alignment: 
image.

Should be `13px` instead of `14px` I believe and we're good: 

image

**Comment by barmac** [comment]
I've adjusted the line height and the status bar height so that we can keep the font as it is. Should be in the centre now.

**Comment by nikku** [comment]
The font sizes should be the same, right? Or is there a reason `XML` and the engine profile are off by `1px`?

**Comment by nikku** [comment]
As mentioned the fix is to make the profile text `13px` in size, just like the other texts in the status bar: https://github.com/camunda/camunda-modeler/pull/2176#issuecomment-809317005

**Comment by barmac** [comment]
Oh sorry. I haven't noticed :D

**Comment by barmac** [comment]
There is no reason for that. Thanks for noticing!

**Review by nikku — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
After closing the XML View, the button has a weird focus state

image

**Comment by pinussilvestrus** [comment]
Oh, actually I saw my branch was not updated to the latest state... It's gone :)

**Review by pinussilvestrus — APPROVED** [review]
LGTM

**Review by andreasgeier — APPROVED** [review]
Looks fantastic - great job @barmac

**Comment by pinussilvestrus** [comment]
Wazzup `merge-me`?

**Pull request merged**
