### PR TITLE
chore: fix security audit issues

### PR DESCRIPTION
**Pull request by MaxTru**

### CODE REVIEW

**Comment by philippfromme** [comment]
So we're switching to npm@7?

**Comment by MaxTru** [comment]
> So we're switching to npm@7?

Thanks for spotting, that was by mistake. Corrected it

**Review by philippfromme — APPROVED** [review]
👍🏻

**Comment by MaxTru** [comment]
I will revert this, since this creates an error on Windows:
```
connection check
      √ should display hint if the username and password are missing when submitting
      × should display hint if token is missing
	AssertionError: expected {} to have a length of 1 but got 0
	    at eval (webpack:///./src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigModalSpec.js?:127:61)
```

**Comment by nikku** [comment]
Proposal: Let's do it after the release when we have time to look into this issue.

**Comment by MaxTru** [comment]
Agreed, lets do that. I will continue then now

**Pull request merged**
