### PR TITLE
Lint Camunda Cloud and Platform BPMN Diagrams

### LINKED ISSUE #2625: Basic linting infrastructure is available for Platform and cloud BPMN diagrams (with no-op for actual platform lint rules)
__What__

Port the linting infrastructure from cloud to platform BPMN provider.

__Why__

It does not make sense to have it available in cloud only. It shall be possible to use it in platform, potentially, too (cf. https://github.com/camunda/camunda-modeler/pull/2624).

### PR DESCRIPTION
**Pull request by philippfromme**
* [x] Platform BPMN diagrams are linted
* [x] feature is tested

Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/5
Closes #2625

### CODE REVIEW

**Comment by nikku** [comment]
What I'm wondering here is related to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/5#issuecomment-1008800817.

Why don't we have a single linter configuration for the time being, that lints both cloud _and_ platform diagrams. The overhead is minimal and we shall carefully decide when to split things up anyway.

**Comment by philippfromme** [comment]
> What I'm wondering here is related to [camunda/bpmnlint-plugin-camunda-compat#5 (comment)](https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/5#issuecomment-1008800817).
> 
> Why don't we have a single linter configuration for the time being, that lints both cloud _and_ platform diagrams. The overhead is minimal and we shall carefully decide when to split things up anyway.

Addressed as part of https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/5.

**Comment by nikku** [comment]
@philippfromme Could you ask someone else from the team to take over the review for this PR / feature. I'll not be able to follow up this week.

**Comment by philippfromme** [comment]
@nikku Will do! 👍🏻

**Comment by philippfromme** [comment]
Tests are timing out. I'm on it.

**Comment by philippfromme** [comment]
I've been struggling to fix a [failing test case](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/__tests__/IntegrationSpec.js#L67). This test case started failing after linting of Camunda Platform BPMN diagrams [was introduced](https://github.com/camunda/camunda-modeler/pull/2629/commits/5e73bf281b8930bf1c503f62eba15f4504bc30a1#diff-a8ee53f63c47900983b24616f87f9b04023e1b48be19fd3ee726d0138276b811R160). The test is timing out:

```sh
27 01 2022 23:17:45.841:WARN [HeadlessChrome 90.0.4427 (Windows 10.0.0)]: Disconnected (0 times)reconnect failed before timeout of 2000ms (ping timeout)
HeadlessChrome 90.0.4427 (Windows 10.0.0) ERROR
  Disconnectedreconnect failed before timeout of 2000ms (ping timeout)
```

It turns out that the test gets stuck in an infinite loop of importing XML, telling the app to lint the imported XML which causes the app to update the tab causing another import and so on:

```sh
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_1">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_2">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_1">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_2">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_1">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_2">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_1">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_2">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_1">'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'needs import', '<bpmn:process id="Process_2">'
LOG LOG: '#lintTab calling #updateTab', []
LOG LOG: '#updateTab'
LOG LOG: 'BpmnEditor#checkImport'
LOG LOG: 'BpmnEditor#checkImport'
```

The props of `BpmnEditor` keep changing between one XML and the other for no apparent reason.

Interestingly, changing the linter's code to simply return an empty array prevents the infinite loop.

```javascript
export default function createBpmnLinter({ config, moddleExtensions }) {
  const moddle = new BpmnModdle(moddleExtensions);

  const linter = new Linter(config);

  return class BpmnLinter {
    static async lint(contents) {
      
      // return without linting
      return [];

      let rootElement;

      if (isString(contents)) {

        try {
          ({ rootElement } = await moddle.fromXML(contents));
        } catch (err) {
          return [];
        }

      } else {
        rootElement = contents;
      }

      let results;

      try {
        results = await linter.lint(rootElement);
      } catch (err) {
        return [];
      }

      return Object.values(results).reduce((results, result) => {
        return [ ...results, ...result ];
      }, []);
    }
  };
}
```

I'm currently stuck with this issue.

**Comment by philippfromme** [comment]
After discussing this issue with @pinussilvestrus we decided to skip the failing test for now. This issue cannot be reproduced manually and might be caused by the way the test is set up. Furthermore, we test whether external file changes are picked up during our [manual integration tests](https://github.com/camunda/camunda-modeler/blob/develop/docs/.project/INTEGRATION_TEST.md#fs-integration-platform-specific). We could also consider creating actual integration tests using [WebdriverIO](https://webdriver.io/) which we decided against when we discussed this topic long time ago simply because we didn't have capacity at that time.

**Review by pinussilvestrus — APPROVED** [review]
LGTM 👍

**Pull request merged**
