### PR TITLE
deps: update codemirror deps

### PR DESCRIPTION
**Pull request by barmac**
### Proposed Changes

This updates codemirror deps. Not sure why renovate does not pick this up.
We can merge it after the release.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
Pushed via https://github.com/camunda/camunda-modeler/pull/4561/commits/dd71dfbb00b15704d236c629018676bbc05df53c.

**Comment by nikku** [comment]
To be handled with care and/or paused for the moment, cf. https://github.com/camunda/camunda-modeler/pull/4563#issuecomment-2377014379.

**Comment by barmac** [comment]
This needs to be merged together with https://github.com/camunda/camunda-modeler/pull/4487

**Comment by barmac** [comment]
Closing this in favor of https://github.com/camunda/camunda-modeler/pull/4565

**Pull request closed without merging**
