### PR TITLE
Support placeholders in String and Text templates properties

### PR DESCRIPTION
**Pull request by barmac**
deps: update to `@bpmn-io/properties-panel@3.20.0`

deps: update to `bpmn-js-element-templates@1.16.0`

deps: update to `camunda-bpmn-js@4.10.0`

### CODE REVIEW

**Comment by barmac** [comment]
The new feature can be tried out on the dev email connector:
image

**Comment by marstamm** [comment]
Works on linux 👍

**Review by nikku — APPROVED** [review]
Works on my machine:

capture 3De6Km_optimized

**Comment by nikku** [comment]
@barmac did we already document this? If not let's capture it as a follow-up.

**Comment by barmac** [comment]
No, I still need to prepare documentation for this.

**Comment by nikku** [comment]
Follow-up for documentation - https://github.com/camunda/camunda-modeler/issues/4331.

**Pull request merged**
