### PR TITLE
chore: reword release info

### PR DESCRIPTION
**Pull request by barmac**
Related to #4691
Related to https://github.com/camunda/camunda-modeler/pull/4713

### Proposed Changes

This captures the @crobbins215's suggestions:

Side-by-side:

| current | proposal
| ------- | -------- |
| image | _Users_maciej_workspace_bpmn-io_camunda-modeler_client_build_index html
 |

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
Current version from https://github.com/camunda/camunda-modeler/pull/4713#issue-2678941600:

image

**Comment by barmac** [comment]
Side-by-side:

| current | proposal
| ------- | -------- |
| image | image |

**Comment by lmbateman** [comment]
Just a couple of minor comments:
- I think "variables" should be capitalized, since it's referring to a specific label ("Variables panel").
- "on canvas" should have a hyphen ("on-canvas") because it's a modifier phrase that comes before the noun it modifies.

**Comment by barmac** [comment]
Thanks for the suggestions. I updated https://github.com/camunda/camunda-modeler/pull/4716#issue-2683076280 with the changes.

**Comment by nikku** [comment]
Good stuff :checkered_flag:

**Comment by nikku** [comment]
If we update to `Variables panel` then we have to do it in the header, too.

**Review by nikku — APPROVED** [review]

**Comment by barmac** [comment]
Right! OK I'm merging this with the capitalization fix. I won't update the screenshot though.

**Pull request merged**
