### PR TITLE
Integrate new context pad

### PR DESCRIPTION
**Pull request by philippfromme**
Adds the ability to enable the new context pad through the `enable-new-context-pad` flag.

electron_RvzZDnvUz7

----

Related to https://github.com/camunda/camunda-modeler/issues/4263

### CODE REVIEW

**Comment by philippfromme** [comment]
@nikku I changed the background to white.

**Comment by philippfromme** [comment]
Forgot to add to dmn-js.

**Comment by nikku** [comment]
As discussed we don't have comments in the core modeling domain and would need to get rid of them:

image

**Comment by nikku** [comment]
@philippfromme I assume this closes https://github.com/camunda/camunda-modeler/issues/4263?

If so, let's tag this PR accordingly.

**Pull request merged**
