### PR TITLE
Remove toolbar

### LINKED ISSUE #2569: Remove toolbar all together
__What should we do?__

Remove the toolbar completely and the the existing toolbar fills (align, distribute, color helpers).

__Why should we do it?__

Support [UX re-design](https://github.com/camunda/camunda-modeler-design/issues/32).

---

Depends on https://github.com/camunda/camunda-modeler/issues/2568.

### PR DESCRIPTION
**Pull request by smbea**
Closes #2569

image

cc @andreasgeier

### CODE REVIEW

**Review by nikku — APPROVED** [review]
Bye bye :wave:

**Comment by nikku** [comment]
Hold on, looks like we gotta [clean up behind us, too](https://camunda.slack.com/archives/C80C0EC79/p1638270316121300).

**Comment by smbea** [comment]
> Hold on, looks like we gotta [clean up behind us, too](https://camunda.slack.com/archives/C80C0EC79/p1638270316121300).

All fixed

**Comment by nikku** [comment]
:wave:

**Pull request merged**
