### PR TITLE
deps: update @camunda/linting dependency

### PR DESCRIPTION
**Pull request by philippfromme**
* new signal event types supported by Camunda 8.3 (no error)
* warning about deprecated secrets format starting with Camunda 8.3
* change warning icon color from yellow to orange

image

---

Closes https://github.com/camunda/camunda-modeler/issues/3819
Closes https://github.com/camunda/camunda-modeler/issues/3834

### CODE REVIEW

**Comment by nikku** [comment]
@philippfromme Please link this pull request + the commit with the respective issues it closes.

We'll not be able to reasonably follow up on what got integrated when otherwise.

**Comment by nikku** [comment]
I found that selecting the respective entry does not work as previously showcased in the demo. Is this a bug or intended?

capture B90nNL_optimized

What I'd expect: Selecting the warning entry focusses the field; this also works in element-template mapped fields.

**Review by nikku — CHANGES_REQUESTED** [review]
TODO:

* [ ] Update colors as discussed (cf. https://github.com/camunda/web-modeler/pull/6230)
* [x] Investigate selection in properties panel not working (https://github.com/camunda/camunda-modeler/pull/3885#issuecomment-1733772915)

**Comment by philippfromme** [comment]
> It doesn't seem to work with element templates and custom entries. The properties panel ID is `"Activity_0hsx14b-input-undefined-source"` so something isn't right. I'll look into it.

I've root-caused the issue and it seems like we don't set `$parent` on the `zeebe:Input` that is created. Therefore the index of the input within the parents inputs can't be determined and the properties panel ID ends up being wrong.

**Comment by philippfromme** [comment]
> Update colors as discussed (cf. https://github.com/camunda/web-modeler/pull/6230)

I've updated the color as discussed.

> Investigate selection in properties panel not working (https://github.com/camunda/camunda-modeler/pull/3885#issuecomment-1733772915)

I've created an issue for the bug that prevents custom properties panel entries from being selected: https://github.com/bpmn-io/bpmn-js-element-templates/issues/16 We should follow up on this, I think it's not a blocking issue.

**Comment by nikku** [comment]
Integration testing the signal support I _may_ have found a bug:

image

Expected behavior: Signal catch events require a signal reference. [There exists no catch-all](https://github.com/camunda/camunda-modeler/issues/3819#issuecomment-1701174639).

Cf. [test diagram](https://github.com/camunda/camunda-modeler/files/12724377/signal.bpmn.txt)

**Comment by nikku** [comment]
@smbea Could you double-check https://github.com/camunda/camunda-modeler/pull/3885#issuecomment-1734977272 and create a bug report if my suspicion is correct?

**Review by nikku — APPROVED** [review]
Works as specified. We want to follow-up with everything else.

**Comment by nikku** [comment]
Follow-up: https://github.com/camunda/camunda-modeler/issues/3889.

**Comment by nikku** [comment]
Great stuff :clap:

**Pull request merged**
