### PR TITLE
feat(updateChecks): always include versionInfo prior to releaseNote

### LINKED ISSUE #2422: Automatically include version number in the release notes
__Is your feature request related to a problem? Please describe.__

When I add a new version of the application, I always have to add the version number in the HTML so that it's not confused with newer version. Cf. https://github.com/camunda/camunda-modeler-update-server/pull/72#issuecomment-918877174

__Describe the solution you'd like__

Add the version number automatically before each chunk of the release notes.

__Describe alternatives you've considered__

Leave it as it is and check it manually each time.

### PR DESCRIPTION
**Pull request by MaxTru**
* Note: when this is released, we shall not include the releaseVersion
  in the releaseNoteBody in updateServer anymore
* closes #2422

I will also add a note to updateServer

Screenshot_20220119_090649

### CODE REVIEW

**Comment by philippfromme** [comment]
Is it expected that `4.12` is shown twice?

**Comment by MaxTru** [comment]
> 

yes. Because in the past we manually inserted it into the hmtl snippet in the update server. So we would not need to do that in the future anymore :-)

Practically this would not happen, since Modeler 5.0.0 will not retreive update notifications from 4.x or older.

**Comment by philippfromme** [comment]
How do we make sure to not accidentally include the version in the release note anymore? 🤔

**Comment by MaxTru** [comment]
> How do we make sure to not accidentally include the version in the release note anymore? thinking

If we wanted to do that, it would need to be done in the update-server.

But in the end it is html that we configure there... So I guess it is very hard.

**Review by philippfromme — APPROVED** [review]
👏🏻

**Pull request merged**
