### PR TITLE
CAM-10354 Cursor pointer changing in few scenario into cursor:not allowed automatically

### PR DESCRIPTION
**Pull request by RamjiRamachandran**
Cursor pointer changing in few scenario into cursor:not allowed automatically
**Issue description:** 

    OS: [Windows 10]
    Camunda Modeler Version: [3.*]

Cursor behavior changing while connecting tasks module using arrow option.

Scenario :
When 2 objects are close and trying to connected the flow using arrow icon available from object tool bar. After mouse release inside another object also, cursor icon not changed from not-allowed mode to default mode.End user felt that its not allowed to add text or do other activities. Its changing only after the arrow icon from object tool tip.

here is the  attachment video for deatils 
https://github.com/camunda/camunda-modeler/files/3211147/May.23.2019.12_52.PM.zip 

__Which issue does this PR address?_
This will address https://app.camunda.com/jira/browse/CAM-10354 

Closes #1387 #1383

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I'm not sure whether this is the correct way to fix the problem. We should rather go for a fix in `bpmn-js` or `diagram-js`, if reproducible.

**Comment by RamjiRamachandran** [comment]
> I'm not sure whether this is the correct way to fix the problem. We should rather go for a fix in `bpmn-js` or `diagram-js`, if reproducible.

Yeah , you are correct . This would be quick fix for the people who using electron (.exe) directly. They can easily add in css plugins to resolve this issue.

**Comment by RamjiRamachandran** [comment]
Thanks for the suggestion, Let me try debug in bpmn-js and diagram-js to resolve this issue.

**Comment by pinussilvestrus** [comment]
Thanks @RamjiRamachandran, we would very appreciate this!

**Comment by pinussilvestrus** [comment]
As stated out in [this comment](https://github.com/camunda/camunda-modeler/issues/1383#issuecomment-506296386) we will try to find a proper solution to fix it in `diagram-js`. So let's close this for the moment.

**Pull request closed without merging**
