### PR TITLE
Update to Electron 7

### LINKED ISSUE #1448: Update to latest Electron
[Electron 6 got released](https://electronjs.org/blog/electron-6-0) and as a result, support for Electron 3 got dropped. This means we won't get fixes for Electron 3 anymore and should consider the update to the latest version.

In the mean time, Electron 7 got released, too.

A first investigation showed that the new version is not a drop-in replacement for us. It disables node integration per default (which is a good thing). That requires additional work on our side though. 

__Tasks__

* [x] Update our app to work without node integration (https://github.com/camunda/camunda-modeler/issues/1453)
* [ ] Fix XML editor layouting issue
* [ ] Update to `Electron@7` (https://github.com/camunda/camunda-modeler/issues/1448)

### PR DESCRIPTION
**Pull request by nikku**
__Works on__

* [x] Linux
* [x] MacOS
* [x] Windows

---

Closes #1448

### CODE REVIEW

**Comment by nikku** [comment]
This was straight forward (and works on Linux).

**Comment by nikku** [comment]
Needs double check on MacOS and Windows.

**Comment by oguzeroglu** [comment]
I cannot export images on Mac. Could you verify it works on Linux?

**Comment by nikku** [comment]
I can reproduce it on Linux, too. Will look into it and report back on my findings.

**Comment by nikku** [comment]
Fixed by updating our dialog. The Electron Dialog is promisified now.

**Comment by oguzeroglu** [comment]
Works on Mac 👍

**Comment by nikku** [comment]
@philippfromme Could you give this one a look and verify it works on Windows :copyright: :registered: :boom:, too?

**Comment by philippfromme** [comment]
Doesn't work on Windows. Built executables error with the following message:

image

In development mode SVGs cannot be loaded which probably is an issue with the Karma configuration.

**Comment by nikku** [comment]
What are your exact steps to reproduce the errors?

**Comment by philippfromme** [comment]
@nikku 

* `npm run build:distro` and running Camunda Modeler leads to `Not allowed to load local resource`
* `npm run dev` leads to `Failed to execute 'createElement' on 'Document': The tag name provided ('static/media/Play.f79fe6ae.svg') is not a valid name.` error in the log

**Comment by nikku** [comment]
Did you try a clean install `npm install && npm run all`, too?

**Comment by philippfromme** [comment]
I had to update `nyc` to successfully run `npm run all` on Windows (see https://github.com/istanbuljs/nyc/issues/1205). Of cource `npm run build:distro` doesn't build the client so that was the issue.

The issue regarding SVGs in development mode is not related to the Electron update.

**Comment by nikku** [comment]
Thanks for clarifying. :heart:

**Pull request merged**
