### PR TITLE
New loading indicator

### LINKED ISSUE #1719: Update loading indicator
__What should we do?__

Replace current Camunda Logo based loading indicator with new standard indicator: https://zpl.io/a84kq1X

__Why should we do it?__

Product UX alignment.

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #1719

For the spinner, we're using the `spinner-border` class compatible with [Bootstrap 4.4](https://getbootstrap.com/docs/4.4/components/spinners/) classname standards.

spinner

### CODE REVIEW

**Comment by oguzeroglu** [comment]
@nazlikaya Could you have a look at this?

**Comment by oguzeroglu** [comment]
To the code reviewer: I'll remove the WIP label once Nazli approves.

**Comment by philippfromme** [comment]
Approved 👍

**Comment by oguzeroglu** [comment]
This is the ticket about loading indicator positioning bug: https://github.com/camunda/camunda-modeler/issues/1736

**Comment by nazlikaya** [comment]
Design review 👍

**Pull request merged**
