### PR TITLE
Prevent duplicated help menu entries

### LINKED ISSUE #3032: Help menu contains a duplicate entry to 'DMN Tutorial'
### Describe the bug

image

Two entries are present in the menu for 'DMN Tutorial', they both point to the same link. We should clean this up as it doesn't serve any purpose.

### Steps to reproduce

1. Open the modeler
2. Navigate to menu > help

### Expected behavior

There should only be one entry. 

### Environment

- Camunda Modeler Version: 5.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pinussilvestrus**
_Originated from https://github.com/camunda/camunda-modeler/pull/3035._

This prevents duplicated help menu entries in the backend.

Closes #3032

### CODE REVIEW

**Review by barmac — CHANGES_REQUESTED** [review]
If we merge this PR, no link will be displayed when `--disable-platform` flag is set. We already don't display tutorial links for BPMN in such a situation, which I think could be considered as a bug as well.

**Comment by barmac** [comment]
So perhaps we should display/hide links based on the `--disable-<file-type>` flags, not based on provider appearance.

**Comment by pinussilvestrus** [comment]
Very good catch 👍 I will propose something.

**Comment by pinussilvestrus** [comment]
What about ensuring the help menus only got added once in the TabsProvider:

```js
const dmnProvider = (this.providersByFileType['dmn'] || [])[0];
if (dmnProvider) {
  dmnProvider.getHelpMenu = () => DMN_HELP_MENU;
}

const bpmnProvider = (this.providersByFileType['bpmn'] || [])[0];
if (bpmnProvider) {
  bpmnProvider.getHelpMenu = () => BPMN_HELP_Menu;
}
```

This way, we don't depend on `--disable-platform` | `--disable-zeebe` flags. Looks a bit like monkey-patching, but we are anyway manipulating the providers via flags this way.

**Comment by pinussilvestrus** [comment]
As the backend does not know about BPMN, or DMN, we could definitely filter for duplicates, e.g. via `label`, or `label` + `action`.

**Comment by pinussilvestrus** [comment]
I updated the PR to prevent duplicates in the backend. Added @smbea as any other is on vacation 🙂

**Review by smbea — APPROVED** [review]
I think this looks good 🚀

**Pull request merged**
