### PR TITLE
Migrate to GitHub actions (1/2)

### PR DESCRIPTION
**Pull request by barmac**
This migrates CI and nightly jobs to GitHub Actions. Next step will be to migrate the release jobs.

### CODE REVIEW

**Comment by barmac** [comment]
I've verified the nightly job with experiment branch: https://github.com/camunda/camunda-modeler/actions/runs/812859608

**Comment by nikku** [comment]
Looks good so far!

**Comment by barmac** [comment]
This is blocked because we still need to configure the S3 bucket.

**Comment by barmac** [comment]
> This is blocked because we still need to configure the S3 bucket.

I was able to configure it with the old bucket so we can decouple the migration from this PR.

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
Let's try it out in the next days.

**Pull request merged**
