### PR TITLE
Load modeling styles

### LINKED ISSUE #3030: Templates can't be unbind if section header is behind the dropdown options
### Describe the bug

You can not unbind any template if a section header is behind the dropdown options (which is mostly the case, only avoidable by expanding the template section itself)

This may relate to the sticky header issue that we shipped, but only monkey patched. It seems to be a `z-index` issue. 
All dropdowns should have a higher `z-index` then the (non-)sticky headers.

Bildschirmfoto 2022-07-14 um 17 36 15

### Steps to reproduce

See the video:

https://user-images.githubusercontent.com/56470362/179020742-9bc1b9e1-86f9-40c3-b22a-b14e06846e8d.mov

### Expected behavior

Unbind is possible (Dropdown is clickable)

### Environment

- Camunda Modeler Version: 5.1.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Related to https://github.com/bpmn-io/internal-docs/issues/590
Closes #3030

* Remove patch CSS fixes
* Load modeling library styles globally

**Summary**

Find some more context in https://github.com/bpmn-io/internal-docs/issues/590#issuecomment-1181765569 and https://github.com/bpmn-io/internal-docs/issues/590#issuecomment-1185305654.

Instead of loading the `camunda-bpmn|dmn-js` modeling styles on the editor component level, and causing duplicated style definitions in `head`, it now loads everything in a central place. This has the advantage that we have full control of when and in which order the styles are loaded.

Note that we do not use the "bundled" modeler styles from the packages, but the individual components to prevent duplicates. This only works under the assumption that we anyway want _only one version_ of library styles in BPMN and DMN.

**Artifacts**

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/load-modeling-styles/camunda-modeler-load-modeling-styles-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/load-modeling-styles/camunda-modeler-load-modeling-styles-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/load-modeling-styles/camunda-modeler-load-modeling-styles-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/load-modeling-styles/camunda-modeler-load-modeling-styles-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/load-modeling-styles/camunda-modeler-load-modeling-styles-win-x64.zip

**Todo**
* [x] Build artifacts ([_is running..._](https://github.com/camunda/camunda-modeler/actions/runs/2675709864)).
* [ ] Gather feedback from the team
* [ ] Consider test coverage?

### CODE REVIEW

**Comment by barmac** [comment]
I am wondering if we can automate this so that we don't need to update `_modeling.less` when a new stylesheet is added to any of `camunda-xxxx-js` packages. We know upfront that the file names like `bpmn-js.css` or `diagram-js.css` should be loaded only once, so perhaps we could filter them out with the webpack configuration. Thus, we could keep `camunda-xxxx-js` styles as a blackbox. WDYT?

**Comment by barmac** [comment]
BTW I like the idea of preloading styles in one place instead of lazy-loading with each of the editor tabs.

**Comment by pinussilvestrus** [comment]
> I am wondering if we can automate this so that we don't need to update `_modeling.less` when a new stylesheet is added to any of `camunda-xxxx-js` packages. We know upfront that the file names like `bpmn-js.css` or `diagram-js.css` should be loaded only once, so perhaps we could filter them out with the webpack configuration. Thus, we could keep `camunda-xxxx-js` styles as a blackbox. WDYT?

I like this idea; let's try it out. It should be possible around the [`style-loader#insert`](https://github.com/camunda/camunda-modeler/pull/3031#issuecomment-1186943031) configuration. Our used style-loader version is fairly outdated, so let's see how easy it is to make it configurable.

**Comment by pinussilvestrus** [comment]
There might be other options using `postcss`: https://github.com/webpack-contrib/css-loader/issues/1233. But I agree; let's keep things simple for now. If we see the necessity, let's get back to it.

**Pull request merged**
