### PR TITLE
feat: run renderer in sandbox per default

### PR DESCRIPTION
**Pull request by barmac**
This can be overridden if app is run with node integration enabled.

### CODE REVIEW

**Comment by barmac** [comment]
This will need to be tested on build artifacts (available in ~20 minutes):

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/sandbox-per-default/camunda-modeler-sandbox-per-default-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/sandbox-per-default/camunda-modeler-sandbox-per-default-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/sandbox-per-default/camunda-modeler-sandbox-per-default-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/sandbox-per-default/camunda-modeler-sandbox-per-default-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/sandbox-per-default/camunda-modeler-sandbox-per-default-win-x64.zip

**Comment by barmac** [comment]
We need to verify that it works fine on each platform.

**Comment by nikku** [comment]
Works on Linux. Good job @barmac! :heart_eyes:

**Comment by marstamm** [comment]
Works on windows as well, let's merge 🎉

**Pull request merged**
