### PR TITLE
deps: update BPMN modeling libraries

### LINKED ISSUE #4450: Support user task priority in C8
### What should we do?

Support adding priority for user tasks in C8:

```xml
<userTask id="" name="">
  <bpmn:extensionElements>
    <zeebe:priorityDefinition priority="15" />
  </bpmn:extensionElements>
</userTask> 
```

* [x] https://github.com/camunda/zeebe-bpmn-moddle/issues/62
* [x] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1069
* [x] https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/170
* [x] https://github.com/camunda/linting/issues/113
* [ ] https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1073

### Why should we do it?

Related to https://github.com/camunda/product-hub/issues/217

### PR DESCRIPTION
**Pull request by Skaiir**
### Proposed Changes

Updates BPMN modeling dependencies, adding support for #4450.

Closes https://github.com/camunda/camunda-modeler/issues/4450
Closes https://github.com/camunda/camunda-modeler/issues/4140
Closes https://github.com/camunda/camunda-modeler/issues/3534

#### Validation (for task definition priority)

* Add a user task
* Priority field should be available under assignment
* Should be feel optional
* Should take any integer between 0 & 100, or a feel expression, and should have corresponding linting rules + properties panel errors when not
* Should be unsupported pre 8.6, and have corresponding linting rules
* Should have a tooltip explaining more or less how it works
* Should set extension property `priorityDefinition`, attribute `priority`
* Should clean the extension property on clearing the priority

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [x] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
Not sure if we can tell the linked issue will be closed via this PR given https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1073 is still open. WDYT?

**Comment by Skaiir** [comment]
@barmac Since we are not concerning ourselves with documentation for now due to prios, we can still close it and deal with it independently I believe.

**Comment by Skaiir** [comment]
But if you prefer, we can keep the tracking issue. For me it won't make a difference I'll just unassign myself from the tracking :).

**Comment by nikku** [comment]
@Skaiir I'd just like you to connect the follow-ups to whatever epic you work on. From our end it is fine to incrementally ship things, hence :+1: for closing the issue, with some follow-ups to do.

**Review by nikku — CHANGES_REQUESTED** [review]
You can enter strings in the field, which I'm not sure is expected:

screenshot EQmVEl

I cannot see any validation (not supported pre-8.6).

----

I propose we take this the usual route, integrate a working thing in camunda-bpmn-js, and take it from there.

**Comment by nikku** [comment]
Package published as https://github.com/camunda/camunda-bpmn-js/releases/tag/v4.18.0.

**Comment by nikku** [comment]
This now bumps all modeling dependencies, consistently via `camunda-bpmn-js`, and includes the [latest version of linting](https://github.com/camunda/camunda-modeler/pull/4468/commits/74f49da1dfafac2bf5cae52f014b6682027cf6a7), too.

@Skaiir I strongly suggest you to get your DEV setup for the modeler sorted, so you can efficiently test this locally. We're not the ones to do primary user testing :see_no_evil:, but we want you to [verify the definition of done](https://github.com/bpmn-io/internal-docs/blob/main/development/DEFINITION_OF_DONE.md) yourself, before you move the PR to `needs review`.

**Pull request merged**
