### PR TITLE
chore(RELEASE): refer to marketing form to update download page

### PR DESCRIPTION
**Pull request by MaxTru**

### CODE REVIEW

**Comment by philippfromme** [comment]
Shouldn't [PATCH_RELEASE.md](https://github.com/camunda/camunda-modeler/blob/4903f0837e5d05d5bddb0b4f7cca82678002c486/docs/.project/PATCH_RELEASE.md) be updated as well?

**Comment by MaxTru** [comment]
> Shouldn't [PATCH_RELEASE.md](https://github.com/camunda/camunda-modeler/blob/4903f0837e5d05d5bddb0b4f7cca82678002c486/docs/.project/PATCH_RELEASE.md) be updated as well?

Ups - yes. Thanks for spotting. Will follow up

**Comment by MaxTru** [comment]
Done @philippfromme

**Review by philippfromme — APPROVED** [review]
✅

**Pull request merged**
