### PR TITLE
fix: collect both app and client deps for license book

### LINKED ISSUE #3714: Investigate incomplete third party notices
### What should we do?

With the v5.13.0 release and the [sentry bump](https://github.com/camunda/camunda-modeler/pull/3698) we're seeing incomplete third party notices.

As an example the following is part of the dependency tree:

```json
,
    "app/node_modules/@sentry/node": {
      "version": "7.57.0",
      "resolved": "https://registry.npmjs.org/@sentry/node/-/node-7.57.0.tgz",
      "integrity": "sha512-63mjyUVM6sfJFVQ5TGVRVGUsoEfESl5ABzIW1W0s9gUiQPaG8SOdaQJglb2VNrkMYxnRHgD8Q9LUh/qcmUyPGw==",
      "dependencies": {
        "@sentry-internal/tracing": "7.57.0",
        "@sentry/core": "7.57.0",
        "@sentry/types": "7.57.0",
        "@sentry/utils": "7.57.0",
        "cookie": "^0.4.1",
        "https-proxy-agent": "^5.0.0",
        "lru_map": "^0.3.3",
        "tslib": "^2.4.1 || ^1.9.3"
      },
      "engines": {
        "node": ">=8"
      }
    }
```

It is, however, not part of the [third party notices](https://github.com/camunda/camunda-modeler/blob/develop/THIRD_PARTY_NOTICES).

### Why should we do it?

Ensure we ship a consistent `THIRD_PARTY_NOTICES` file.

### PR DESCRIPTION
**Pull request by barmac**
Closes #3714

### CODE REVIEW

**Comment by barmac** [comment]
This is the first step to fix https://github.com/camunda/camunda-modeler/issues/3714

Some information needs to be manually submitted:

```
missing license text: https-proxy-agent
missing license text: agent-base
missing license text: lru_map
missing license text: err-code
missing license text: typed-duration
missing license text: keyv
missing license text: @camunda/linting
missing license text: mitt
missing repository: @bpmn-io/cm-theme
missing license text: @bpmn-io/moddle-utils
missing repository: preact-compat
missing license text: preact-compat
missing repository: preact-hooks
missing license text: preact-hooks
missing repository: jsx-runtime
missing license text: jsx-runtime
missing repository: @camunda/form-linting
missing license text: bpmn-js
missing repository: feelers
missing repository: undefined
missing license text: undefined
missing repository: style-mod
missing repository: htm_preact
missing license text: htm_preact
missing license text: dmn-js-decision-table
missing license text: dmn-js-drd
missing license text: dmn-js-literal-expression
missing license text: dmn-js-shared
missing license text: dmn-js
missing repository: @bpmn-io/variable-resolver
missing license text: bpmn-js-color-picker
missing license text: bpmn-js-executable-fix
missing license text: cmmn-js
missing license text: hat
missing license text: @bpmn-io/form-js-editor
missing license text: @bpmn-io/form-js-playground
missing license text: @bpmn-io/form-js-viewer
missing repository: @camunda/example-data-properties-provider
```

Also, we need to figure out `unknown` licenses. This should however be resolved if we give the information above to the tool:

```
Summary of used third party licenses:
- MIT - 199
- Apache-2.0 - 6
- ISC - 10
- BSD-3-Clause - 13
- BSD-2-Clause - 1
- unknown - 3
- SEE LICENSE IN LICENSE - 10
- OFL-1.1 - 1
- MIT OR SEE LICENSE IN FEEL-FREE.md - 1
- MIT/X11 - 1
```

**Comment by barmac** [comment]
Also, we don't handle optional dependencies correctly right now. I believe the final license book should be composed of dependencies belonging to each platform. Still, it already looks much better and we could just manually supplement the single-platform deps' licenses instead.

**Comment by barmac** [comment]
I missed the optional dependencies' licenses.

**Comment by barmac** [comment]
Ready.

**Review by nikku — APPROVED** [review]
This looks like a solid solution to me :medal_sports:. Thank you.

**Pull request merged**
