### PR TITLE
fix: make sorting deterministic

### PR DESCRIPTION
**Pull request by philippfromme**
* fix error message formatting (cf. https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/27)
* make sorting deterministic

9wlAHxBcwt

---

Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/27

### CODE REVIEW

**Review by MaxTru — APPROVED** [review]

**Comment by andreasgeier** [comment]
@philippfromme 

> make sorting deterministic

Pleas elaborate how this works / what is the expected behavior?

**Comment by MaxTru** [comment]
> @philippfromme
> 
> > make sorting deterministic
> 
> Pleas elaborate how this works / what is the expected behavior?

This change will ensure that errors are always ordered the same way (alphabetically). Prior to this it was random.

**Comment by andreasgeier** [comment]
I assume, sorted by name or ID of the element? What is the sort behavior for errors of the same element (like in the screencast above)?

**Comment by nikku** [comment]
> What is the sort behavior for errors of the same element

My assumption is that it would still be grouped by element.

I personally don't care about alphabetic sorting, but sort by "element" > "kind of bug"

**Comment by nikku** [comment]
Makes sense, thanks for confirming my intuition (grouped by element).

**Comment by andreasgeier** [comment]
Thanks for the explanation. I agree that having it deterministic is a reasonable first step. Particularly helpful, it avoids the very confusing jumping up and down of error messages (as shown in the bug report).

**Comment by philippfromme** [comment]
As for the implementation, the sorting is done based on the label or ID of the element.

**Pull request merged**
