### PR TITLE
feat(bpmn): persist layout across sessions

### PR DESCRIPTION
**Pull request by marstamm**
closes https://github.com/camunda/camunda-modeler/issues/2638

Recording 2023-04-14 at 10 10 56

### CODE REVIEW

**Review by nikku — COMMENTED** [review]
I'm wondering: Shall we also persist DMN and FORM properties panel state? I don't see a reason we should not.

**Review by nikku — CHANGES_REQUESTED** [review]
I can confirm that it works as expected. Good stuff!

However I found an annoying flicker that degrades the perceived utility of this feature: The app feels shaky, as demonstrated by the following screen capture (switching between two tabs):

capture NkyOJr_optimized

Is there a way we can avoid this? One way _could be_ to update the properties panel layout pre-mount? Potentially other options exist.

**Comment by marstamm** [comment]
It looks like it marks headers as sticky for one frame. My guess is that because we change the layout before mounting, the scroll position in an unmounted state is always "out of screen". I'll check if we can disable sticky headers checks when the properties panel is unmounted and if this fixes it

**Comment by barmac** [comment]
My gut feeling is some problems may come from this: https://github.com/bpmn-io/properties-panel/blob/main/src/hooks/useStickyIntersectionObserver.js

**Comment by marstamm** [comment]
I can confirm that this is not caused by applying the layout, In Camunda Modeler 5.10.0 opened Groups are also initially rendered as sticky:

Recording 2023-04-19 at 10 18 36

**Comment by marstamm** [comment]
So you are both right @barmac and @nikku 🎉 

- The header is sticky, which is caused by the stickyIntersection hook
- The Group is also rendered in it previous state for 1 render cycle, which is fixed by `useLayoutEffect`

Thank you for your inputs, the fixes in the properties panel are here: https://github.com/bpmn-io/properties-panel/pull/238

**Comment by marstamm** [comment]
I updated the branch with the changes made in the properties panel. Feel free to try it out again

Recording 2023-04-19 at 11 51 25

**Review by nikku — APPROVED** [review]
I'm kinda still impressed how natural (aka intuitive, not bad) this feels. Thanks for getting that done @marstamm!

I also like how this naturally just works with connector templates:

capture xlYbcq_optimized

----

As a follow up in the UX department I'd suggest the following:

* Introduce error indicators for closed sections
* Hook up connector template errors with our linting infrastructure

**Comment by nikku** [comment]
Added @YanaSegal and @christian-konrad as reviewers so that both are in the loop here (non-blocking).

**Comment by christian-konrad** [comment]
Great contribution, improving the QoL of both new and power users!

> Hook up connector template errors with our linting infrastructure

We have an (soon to be defined) epic for it: https://github.com/camunda/product-hub/issues/498

> Introduce error indicators for closed sections

I like that idea, remembered we discussed that quite a while ago @YanaSegal

**Pull request merged**
