### PR TITLE
deps: update to `electron@30.0.6`

### PR DESCRIPTION
**Pull request by nikku**
Closes https://github.com/camunda/camunda-modeler/issues/4299

### CODE REVIEW

**Review by barmac — APPROVED** [review]
Works great on Mac

**Comment by jomu78** [comment]
Tested on same system as used in #4299 - works fine.

**Comment by barmac** [comment]
> Tested on same system as used in #4299 - works fine.

Thank you so much for the verification. @philippfromme or @marstamm please check Windows so that we can make sure it works fine.

**Comment by philippfromme** [comment]
I tested on Windows and it works. ✅

**Review by philippfromme — APPROVED** [review]
Works on Windows. ✅

**Pull request merged**
