### PR TITLE
Allow Setting Execution Platform of Forms through UI

### PR DESCRIPTION
**Pull request by philippfromme**
### Changes

* engine profile is shown by respective editor instead of tab
* engine profile of form can be selected through UI

y3KR5ePxw3

---

Depends on https://github.com/camunda/camunda-modeler/pull/2379
Depends on https://github.com/bpmn-io/form-js/pull/140 to be released and integrated

### CODE REVIEW

**Comment by philippfromme** [comment]
As @andreasgeier pointed out during our recent discussion we haven't considered the case of opening a form with an unknown execution platform (and version). For example, let's assume the user opens a form created with a more recent Camunda Modeler that supports Platform 7.16:

g3M2ijbkbk

We could either
* not open a form if we encounter an unknown execution platform (and version)

or

* open the form, indicate that we don't know the execution platform but still allow the user to set it to something we know

**Comment by andreasgeier** [comment]
> * open the form, indicate that we don't know the execution platform but still allow the user to set it to something we know

Not sure if this is reasonable. Assumed, the form contains elements that are unknown, we would need to (a) remove them while downgrading the version or (b) provide a placeholder and freeze that part. Both options sound undesirable.

Maybe we could ask the user. But why should a user accept a downgrade and the loss of data?

**Comment by philippfromme** [comment]
@andreasgeier I've discussed this with @volkergersabeck. Our initial solution was to

### 1. Don't open the form if it contains unknown fields (that is already the behavior)

9NbLvgvj9y

### 2. Don't open the form if we don't know the execution platform

TxLaDymEip

### 3. Offer to set the version to the last known if we don't know the execution platform version

FK8uMWtfET

However, this presents us with a new set of issues:

1. What if we add new properties to existing form fields (e.g. new validation properties). These won't be editable and won't be linted if we allow the user to open a form created with a more recent version of the Camunda Modeler.
2. If we offer to set the execution platform version to the last known version this can be undone through <kbd>Cmd+Z</kbd>. This is a _technical limitation_ that we have at the moment.

> Technical Explanation: In the case of DMN we offer migration based on the XML, so _before_ the import. In the case of forms we wouldn't want to offer migration first and then still show an error (e.g. because of unknown form fields). So we want to offer migration of the execution platform version after we successfully opened the form. However, by that time we're dealing with a form editor instance, not with the JSON, so we have to execute a command to change the version. That command can then be reverted by the user.

My proposal is: Do not open any forms with an unknown execution platform or version for the time being. These forms can always be opened in the Camunda Modeler they were created with.

**Comment by andreasgeier** [comment]
> My proposal is: Do not open any forms with an unknown execution platform or version for the time being. These forms can always be opened in the Camunda Modeler they were created with.

I second this proposal.

**Comment by philippfromme** [comment]
As discussed we are not going to open a form if an unknown execution platform or version is detected:

5YlbNdUIYP

**Comment by philippfromme** [comment]
@nikku form-js@0.4.0 is integrated so this pull request is ready to be reviewed.

**Review by nikku — APPROVED** [review]
Very nice :clap:

**Review by andreasgeier — COMMENTED** [review]
I like that we do not try to open any form file which does not have a specific platform and version and is known by the Modeler.

What I can see in the provided gifs is that in case we do not open the file, still a new tab opens with the json and also the log is opened.

What I would like to suggest is that we stick to our usual behavior if a file cannot be opened (e.g. when trying to open a PDF). There is a dialog that informs the user about the failure, but no tab will be opened in the background and no log activity is made.

**Comment by nikku** [comment]
> What I would like to suggest is that we stick to our usual behavior if a file cannot be opened (e.g. when trying to open a PDF). There is a dialog that informs the user about the failure, but no tab will be opened in the background and no log activity is made.

@andreasgeier What you're seeing here is our usual behavior if we recognize the text format but cannot actually open it as a diagram. Opening the JSON editor allows a user to inspect the file and expert users to correct the error (setting the execution platform to something known).

**Review by andreasgeier — APPROVED** [review]
I see. I was able to reproduce this behavior with a manipulated bpmn file.

✅ &nbsp; So, I can approve this request.

**Pull request merged**
