### PR TITLE
fix: DMN overview icons ignore pointer events

### LINKED ISSUE #2804: Activity icon in DRD blocks interaction
__Describe the Bug__

In the split screen, the symbols on the DMN elements are blocking the click event to switch the view.

__Steps to Reproduce__

1. create a DRD with at least two elements
2. open a DMN element in split view
3. try to switch the view by clicking on the icons in the elements

https://user-images.githubusercontent.com/938244/156809977-85f75b15-be38-4b1a-aa0a-2cb78abf8b0b.mov

__Expected Behavior__

Basically, it shouldn't matter where the user moves the mouse pointer over the element in the DRD or clicks within the element. The symbol area must not block this interaction.

__Environment__

 * Version: 5.0.0-nightly.20220303
 * Operating System: Mac OS 10.15.7 
 * Plugins: <no plugins>
 * Execution Platform: DMN - Camunda Platform or Cloud

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #2804

### CODE REVIEW

**Comment by andreasgeier** [comment]
Just to make sure that it is considered in the bug fix: this bug is not only about the css hover effect, it is about the blocked interaction. Currently, the table can be selected if the user clicks on the symbol area.

**Comment by barmac** [comment]
@andreasgeier Understood and I also checked this during the review.

https://user-images.githubusercontent.com/28307541/161912893-52b68509-92c2-4388-a741-bfc4141b03f4.mov

**Comment by Skaiir** [comment]
> This solves the issue, but I don't quite get why we have to add the `pointer-events: none` in the first place.

Well this is a detail of the implementation but the way I understand it: The minimap makes use of the exact same components as the regular dmn diagram. On the modeling view, hovering the corner button clears the hover effect. I guess whatever causes that also causes the minimap behavior. We override certain things in the minimap to disable that behavior, hence the need for `pointer-events: none`

**Comment by nikku** [comment]
I think we did not fully understand / root cause this thing (cf. [ISSUE_PHASES](https://github.com/bpmn-io/internal-docs/blob/master/development/ISSUE_PHASES.md)).

Let us try to do that, next time, and clean up this fix.

**Pull request merged**
