### PR TITLE
feat(client/BpmnEditor): allow passing linting configurations via plugin

### PR DESCRIPTION
**Pull request by pinussilvestrus**
This allows parsing linting configuration to the Camunda Modeler.

Reference: https://github.com/bpmn-io/bpmn-js-bpmnlint#usage

Related by https://github.com/bpmn-io/camunda-modeler-linter-plugin/pull/5

### CODE REVIEW

**Comment by nikku** [comment]
@pinussilvestrus Let's have a quick chat regarding this tomorrow. 

I'll meet you in our favorite chat tool.

**Comment by pinussilvestrus** [comment]
:+1: I'll create an appointment for this.

**Comment by nikku** [comment]
Let's not merge this as is but consider a way how to create a generic extension point for the BPMN editor (and the others).

The idea would be that a plugin is simply a function of `(options) => newOptions`.


SKETCH:

```
// BpmnEditor.js


    const linterExtension = function(options) {

      return {
        ...options,
        linter: {

        }
      };
    };

    const additionalModulesExtension = function(options) {

      const additionalModules = options.additionalModules || [];

      return {
        ...options,
        additionalModules: [
          ...additionalModules,
          getPlugins('bpmn.modeler.additionalModules') || []
        ]
      };
    };

    const middlewares = [
      linterExtension,
      additionalModulesExtension

      // ...
    ];

    const modeler = new CamundaBpmnModeler(loadConfiguration(middlewares, {
      exporter: {
        name,
        version
      },
      moddleExtensions,
      position: 'absolute'
    }));
```

**Comment by nikku** [comment]
Closing in favor of https://github.com/camunda/camunda-modeler/pull/1434.

**Pull request closed without merging**
