### PR TITLE
deps: update to `@camunda/linting@3.20.0`

### LINKED ISSUE #4277: Warn about missing BPMN Shape
### Problem you would like to solve

I was not warned by Modeler that the diagram was missing a BPMN Shape for a process element.

Specifically, there was no `<bpmndi:BPMNShape>` for this:
```xml
<bpmn:sequenceFlow id="Flow_1d8avtw" sourceRef="Activity_1ipwzk8" targetRef="Activity_0ll9m9k" />
```

### Proposed solution

Warn the user with a problem stating that the process model has an item not visible in the diagram, and which item.

### Alternatives considered

Pay really good attention to the XML :)

In all honesty, another option is for Zeebe to reject models where the visual diagram does not provide a shape for each element in the process. There are several issues with this:
- breaks backward compatibility
- less interoperability with models produced by third parties
- I like doing less

### Additional context

I investigated [a process instance](https://bru-2.operate.camunda.io/689a796f-7efa-487f-9e44-76ca3a98c77b/processes/4503599664803449) that unexpectedly had an extra token after a parallel gateway. This made us think we had a bug in the engine.

After detailed root causing, I discovered that Zeebe executed the process instance correctly. There was a rogue Sequence Flow by passing the Parallel Gateway in the bpmn process (XML), but the visual diagram did not contain a BPMNShape for this item.

- incident channel with analysis: [#inc-unexpected-token-in-process-instance](https://camunda.slack.com/archives/C072L6FLWSG/p1715174440703259)
- applied fix of process after encountering issue https://github.com/zeebe-io/zeebe-engineering-processes/pull/389

### PR DESCRIPTION
**Pull request by marstamm**
closes #4277
image

### CODE REVIEW

**Comment by nikku** [comment]
This looks good for Camunda 8 diagrams. I'd expect the warning to appear for Camunda 7 diagrams, too, but that does not seem to be the case (yet).

**Review by nikku — CHANGES_REQUESTED** [review]
Cf. https://github.com/camunda/camunda-modeler/pull/4309#issuecomment-2129167840

**Comment by marstamm** [comment]
I can not reproduce this on Camunda 7.22 or 7.15:

image

**Comment by nikku** [comment]
Thanks for double-checking. Turns out this is only happening when no execution platform is set (which should be an edge case): 

image

**Review by nikku — APPROVED** [review]

**Pull request merged**
