### PR TITLE
fix(app): activate edit menu if provided only

### LINKED ISSUE #1070: Edit menu stays when last tab is closed
__Describe the Bug__

Edit menu stays and editor actions are still emitted on shortcuts despite the last tab being closed:

foo

__Steps to Reproduce__

* Create BPMN tab
* Close BPMN tab
* (no tabs are open anymore at this point)
* __Edit Menu is still active, keyboard shortcuts still trigger__

__Expected Behavior__

* [ ] No tabs are open -> Edit menu is not visible, keyboard shortcuts don't trigger

__Environment__

 - OS: Any
 - Camunda Modeler Version: `next`

### PR DESCRIPTION
**Pull request by nikku**
* ensures we only show the edit menu, if the
  client provides it
* the empty tab does not provide it, thus
  it is disabled without a tab open

Closes #1070

### CODE REVIEW

**Comment by nikku** [comment]
The general question is: When should we update the menu / reset it?

* When the old tab is unmounted
* When the new tab is shown
* _All tabs_ must update it? Or will the app update / reset it implicitly.

This PR implements the following:

* App updates menu implicitly on tab activation, assuming there will always be a tab shown
* If a tab would like to provide menu entries, it must pass that via `onShown` or `onChanged`

**Comment by nikku** [comment]
This needs additional investigation, as the proposed implementation seems to break the component updating, most notably the exports button disappearing.

**Comment by nikku** [comment]
Addressed the issue. Should work :+1: now.

**Comment by nikku** [comment]
@barmac Could you review this and verify it works on Mac, too?

**Comment by barmac** [comment]
Sure, I'm finishing tests in a sec.

**Pull request merged**
