### PR TITLE
Fix Error Panel Styles

### PR DESCRIPTION
**Pull request by philippfromme**
Fixes according to https://github.com/camunda/camunda-modeler-design/issues/104.

### General Styles

electron_lvSM3ZowV2

### Multi-Line Styles

electron_0QOpyFJGGT

---

Required https://github.com/camunda/camunda-modeler/pull/3014

### CODE REVIEW

**Comment by philippfromme** [comment]
For some reason, the macOS checks won't run. 😢 They are canceled immediately.

**Comment by philippfromme** [comment]
Artifacts:

* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/error-panel-styles/camunda-modeler-error-panel-styles-linux-x64.tar.gz
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/error-panel-styles/camunda-modeler-error-panel-styles-mac.dmg
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/error-panel-styles/camunda-modeler-error-panel-styles-mac.zip
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/error-panel-styles/camunda-modeler-error-panel-styles-win-ia32.zip
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/error-panel-styles/camunda-modeler-error-panel-styles-win-x64.zip

**Comment by philippfromme** [comment]
@marstamm As Camunda Modeler 5.2 code freeze is approaching and you're the only one available, could you maybe have a look at this? These are only style fixes, and I'd like to include them in the upcoming release.

**Comment by marstamm** [comment]
Of course! I'll have a look today

**Comment by marstamm** [comment]
I noticed is that the Error Icon is not centered in its containing div and thought it might be unaligned. But neither is the text center, so they align with each other 😄
image

**Review by marstamm — APPROVED** [review]

**Comment by philippfromme** [comment]
> I noticed is that the Error Icon is not centered in its containing div and thought it might be unaligned. But neither is the text center, so they align with each other 😄 image

Alright, I changed it an now everything is aligned nicely. 😇 

image

**Comment by marstamm** [comment]
🏆

**Comment by philippfromme** [comment]
> 🏆

I'll add that one to my growing collection. 🏆 🎖️ 🏅

**Pull request merged**
