### PR TITLE
Reusable resize container

### LINKED ISSUE #2959: Add resize handler for bottom panel
__What should we do?__

Design issue: https://github.com/camunda/camunda-modeler-design/issues/105

* [ ] make [properties panel](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/PropertiesContainer.js) resize handler a reusable component
* [ ] add resize handler to the bottom panel

__Why should we do it?__

We defined the resize handler as a general concern and shall use it where applicable.

Depends on https://github.com/camunda/camunda-modeler-design/issues/90

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #2959 
Depends on https://github.com/camunda/camunda-modeler-design/issues/90

* moves properties panel resize handlers to reusable component (supported positions for now: `right`, `bottom`)
* use resizable container for bottom panel

Kapture 2022-05-17 at 10 39 31

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2959-resize-container/camunda-modeler-2959-resize-container-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2959-resize-container/camunda-modeler-2959-resize-container-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2959-resize-container/camunda-modeler-2959-resize-container-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2959-resize-container/camunda-modeler-2959-resize-container-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2959-resize-container/camunda-modeler-2959-resize-container-win-x64.zip

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I tried to remove the "globe" drag image on resizing. Apparently, that's not an easy task.

Kapture 2022-05-16 at 16 05 03

What I read in various docs, [`event.dataTransfer.setDragImage`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage) should be the way to go. It seems we already tried to fix this in the past via our [`dragger` util](https://github.com/camunda/camunda-modeler/blob/develop/client/src/util/dom/dragger.js#L48)

```js
event.dataTransfer.setDragImage(emptyCanvas(), 0, 0);
```

Which doesn't work in the current versions; the drag preview also looks different in older versions (although we didn't change the behavior).

Kapture 2022-05-17 at 10 07 15

Therefore I'd propose to de-scope this issue from this PR and fix it in an orderly manner.

**Comment by pinussilvestrus** [comment]
This is ready for review now. I just added @andreasgeier for a design review (if he finds the time).

**Comment by andreasgeier** [comment]
@pinussilvestrus Thank you for taking this issue.

The "globe" on drag is annoying, we should tackle that soon as well
The click button (the grey icon) is not vertically centered
I had a situation in which the click button does not reappear on closed state - but cannot reproduce

There seem to be 2 border-top on the panel
| as is| expected |
|---|---|
| Screen Shot 2022-05-17 at 15 00 09 | Screen Shot 2022-05-17 at 14 59 49 |

**Comment by andreasgeier** [comment]
While we have quite large snapping distance for the properties panel (which makes sense because of the contents), we could reduce the snapping points for the vertical resizing to, say, 200px. So, a user can minimize the view while still. keeping it open.

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus Thank you for taking this issue.
> 
> The "globe" on drag is annoying, we should tackle that soon as well The click button (the grey icon) is not centered I had a situation in which the click button does not reappear on closed state - but cannot reproduce
> 
> There seem to be 2 border-top on the panel
> 
> as is	expected
> Screen Shot 2022-05-17 at 15 00 09	Screen Shot 2022-05-17 at 14 59 49

* I removed the second top border (it was a left over from the bottom panel)
* I set the toggle left position to `calc(50%)`

**Comment by andreasgeier** [comment]
> The minimal height is already set to 200px

ok, so maybe 100 then. I think the min height is too much currently

> I set the toggle left position to calc(50%)

Didn't check it yet but calc(50%) is actually not correct. You need to consider the width of the button, too, and subtract 50% of that number, to be precise. Or better, use transform:translateX(50%) on the button.

**Comment by andreasgeier** [comment]
For reference: min height of bottom panel in VSCode:

Screen Shot 2022-05-18 at 11 54 11

**Comment by pinussilvestrus** [comment]
I adjusted both the min-height (100px) and the vertical position of the bottom toggle. It should be centered now. Updated builds are in the making. 👍 

image

image

**Review by MaxTru — CHANGES_REQUESTED** [review]
* When the log is open and you collapse the panel, you get to a weird state where errors is shown twice, even though the panel is closed:
logSnapping
* Maybe I missunderstand, so learning question:
  * Do we expect to be able to close the container by a simple click?
  * This is indicated by https://github.com/camunda/camunda-modeler/pull/2967/files#diff-d969a518a50a988eff9f0fdd7e8928068bff159d6a249584891e7224b01b2a2fR292 (or do I missunderstand the test case)?
  * If so, then it seems not work for me (e.g., I can click to toggle open, but just clicking won't toggle close -> I need to drag to close)

**Comment by pinussilvestrus** [comment]
> Do we expect to be able to close the container by a simple click?

As I understand, the toggle is only visible when the container is closed. Therefore you can't use it to close. The test case (`should toggle (close)` is just testing the API, but not possible via UI.

image

**Comment by pinussilvestrus** [comment]
> When the log is open and you collapse the panel, you get to a weird state where errors is shown twice, even though the panel is closed

Weird stuff 😆  I will have a look, probably just a CSS issue

**Comment by MaxTru** [comment]
> > Do we expect to be able to close the container by a simple click?
> 
> As I understand, the toggle is only visible when the container is closed. Therefore you can't use it to close. The test case (`should toggle (close)` is just testing the API, but not possible via UI.
> 
> image

Ah - got it. Thanks

**Comment by pinussilvestrus** [comment]
> * When the log is open and you collapse the panel, you get to a weird state where errors is shown twice, even though the panel is closed:

I fixed this. However, now I see more problems coming up with the Log and the Panel open at the same time:

Kapture 2022-05-20 at 10 37 08

One way to fix it would be to make the maximum height of the resizable panel depending on the Log. Still resizing the Log when the Panel is on maximum height would cause the same trouble. This is also hacky, as both panels shouldn't know about each other and work independently. 

For me, it seems like a better fix would be to re-arrange the Log (cf. https://github.com/camunda/camunda-modeler-design/issues/90). I'm inclined to move this one to _Draft_ until we have a proper solution about the Panel - Log dependency.

**Comment by philippfromme** [comment]
This was fixed by https://github.com/camunda/camunda-modeler/pull/3509.

**Pull request closed without merging**
