### PR TITLE
Integrate properties panel improvements

### PR DESCRIPTION
**Pull request by nikku**
This is PR tests the latest properties panel improvements:

* Fixing external errors shadowed by local errors

---

Closes https://github.com/camunda/camunda-modeler/issues/3845

### CODE REVIEW

**Comment by nikku** [comment]
Found issue with canvas tracking. It still seems like event bubble up in the tree:

```
[/home/nikku/Downloads/MyProject/Foo.bpmn] Cannot read properties of undefined (reading 'closest')
    at ContextPadTracking.trackTrigger (webpack://camundanode_modules/bpmn-js-tracking/lib/features/context-pad/ContextPadTracking.js:16:0)
    at invokeFunction (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:580:0)
    at EventBus._invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:0)
    at EventBus._invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:0)
    at EventBus.fire (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:0)
    at ContextPad.triggerEntry (webpack://camundanode_modules/diagram-js/lib/features/context-pad/ContextPad.js:260:0)
    at Object.appendElement (webpack://camundanode_modules/bpmn-js-create-append-anything/dist/index.es.js:1855:0)
    at EditorActions.trigger (webpack://camundanode_modules/diagram-js/lib/features/editor-actions/EditorActions.js:178:0)
    at BpmnEditor.triggerAction (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:704:0)
    at MultiSheetTab.triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:0) [ error ]
```

**Comment by smbea** [comment]
> Found issue with canvas tracking. ~It still seems like event bubble up in the tree:~
> 
> ```
> [/home/nikku/Downloads/MyProject/Foo.bpmn] Cannot read properties of undefined (reading 'closest')
>     at ContextPadTracking.trackTrigger (webpack://camundanode_modules/bpmn-js-tracking/lib/features/context-pad/ContextPadTracking.js:16:0)
>     at invokeFunction (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:580:0)
>     at EventBus._invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:0)
>     at EventBus._invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:0)
>     at EventBus.fire (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:0)
>     at ContextPad.triggerEntry (webpack://camundanode_modules/diagram-js/lib/features/context-pad/ContextPad.js:260:0)
>     at Object.appendElement (webpack://camundanode_modules/bpmn-js-create-append-anything/dist/index.es.js:1855:0)
>     at EditorActions.trigger (webpack://camundanode_modules/diagram-js/lib/features/editor-actions/EditorActions.js:178:0)
>     at BpmnEditor.triggerAction (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:704:0)
>     at MultiSheetTab.triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:0) [ error ]
> ```
> 
> ### Root cause
> This is due to shortcuts triggering through the global (app) context. We want to make sure to global shortcuts do not trigger if the popup is open.

This was already reported [here](https://github.com/bpmn-io/properties-panel/pull/282#issuecomment-1719766120). Niklas said he would deal with it in a follow up but I guess since he went on sick leave, it didn't happen. I can handle this

**Comment by smbea** [comment]
Opened a PR to be more forgiving in tracking: https://github.com/bpmn-io/bpmn-js-tracking/pull/37

**Comment by nikku** [comment]
Opened https://github.com/bpmn-io/bpmn-js-properties-panel/issues/974 as a foundation that would unblock the desktop modeler integration.

**Comment by nikku** [comment]
Split up FEEL popup editor integration into [a separate issue](https://github.com/camunda/camunda-modeler/issues/3877) so we can proceed with the rest of the integration.

**Review by smbea — APPROVED** [review]

**Pull request merged**
