### PR TITLE
fix(app): remove + button to avoid ambiguous behavior

### LINKED ISSUE #2293: Remove `+` button
__What should we do?__

Remove the `+` button. Display the (uncloseable) empty tab with the label `Welcome` only if no other tab is opened.

Empty tab

__Why should we do it?__

Starting with Camunda Cloud the `+` button becomes even more ambiguous. Especially given our current strict separation between execution platforms this can lead to undesired behavior for the user, cf. https://github.com/camunda/camunda-modeler/issues/2283.

### PR DESCRIPTION
**Pull request by MaxTru**
Closes #2293

* Adds a new welcome tab:

No+Button

### CODE REVIEW

**Comment by MaxTru** [comment]
Also see: https://github.com/camunda/camunda-modeler/issues/2309

**Review by nikku — APPROVED** [review]

**Comment by andreasgeier** [comment]
Today we discussed that we should remove the keyboard shortcut for this plus as well (cmd+t). Is that already considered in this PR?

**Comment by andreasgeier** [comment]
✅ &nbsp; The removal looks as expected. Feel free to merge (didn't use the approval because of my previous comment)

**Comment by MaxTru** [comment]
> Today we discussed that we should remove the keyboard shortcut for this plus as well (cmd+t). Is that already considered in this PR?

I will create a seperate PR for that. 

Thanks

**Pull request merged**
