### PR TITLE
Telemetry for cloud dmn diagrams

### LINKED ISSUE #2853: Telemetry for Cloud DMN diagrams
* [x] `diagramOpened`
  * [x] execution platform details
* [x] `deployment`
  * [ ] context?
  * [x] outcome
  * [x] execution platform details
* [X] [documentation is up to date](https://docs.camunda.io/docs/components/modeler/desktop-modeler/telemetry/)

### PR DESCRIPTION
**Pull request by barmac**
Closes #2853

---

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-win-x64.zip

### CODE REVIEW

**Comment by barmac** [comment]
Built on top of https://github.com/camunda/camunda-modeler/pull/2877

**Comment by barmac** [comment]
I had to use a shorter build name as ET rejected the version for being too long.

**Comment by barmac** [comment]
Ready to test with ET integration now :)

**Review by MaxTru — APPROVED** [review]
It lives and sends data! Approved

**Pull request merged**
