### PR TITLE
deps: bump to eslint-plugin-bpmn-io@0.13

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Fixing all the issues regarding the added `space-infix-ops` and `array-bracket-spacing` rules. 

Question: Shall this also apply for single object arrays? Like

```js
const buttons = [ {
  id: 'close',
  label: 'Close'
} ];
```

or 

```js
const providers = [ {
  type: 'default',
  editor: BrokenEditor,
  defaultName: 'Default'
  ..
} ];
```

Currently, the linter would create an issue if these spaces are not set.

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Related to [this comment](https://github.com/camunda/camunda-modeler/pull/2656#discussion_r778053820).

**Comment by MaxTru** [comment]
> Question: Shall this also apply for single object arrays?

Hm - I am not super opinionated, but would rather say "no". Is there an option to disable it for single object arrays?

If not, I think this is acceptable and would approve.

**Comment by pinussilvestrus** [comment]
Taking the rest of the team into the discussion, would be really interested in your opinions 🙂 

For me, these additional spaces for single object arrays look a bit messy, taking more space as needed. But I'd also be fine to simply apply the rules we have everywhere now.

**Comment by pinussilvestrus** [comment]
There is an option for [`objectsInArrays`](https://eslint.org/docs/rules/array-bracket-spacing), but I think that would go for all object arrays then.

**Comment by philippfromme** [comment]
I'd say it's fine. I mostly use

```javascript
const foo = [
  {
    bar: 42
  }
];
```

anyway. 🤡

**Comment by barmac** [comment]
I am fine with either way as long as the formatter fixes it for me 😅

**Review by barmac — APPROVED** [review]

**Comment by nikku** [comment]
:+1: from my side. We've bumped these rules, we shall embrace them everywhere :).

**Pull request merged**
