### PR TITLE
feat(usage-statistics): track icons usage

### PR DESCRIPTION
**Pull request by pinussilvestrus**
This is a preparation for once we support template icons in the Modeler.

Related to https://github.com/bpmn-io/internal-docs/issues/445

### CODE REVIEW

**Comment by barmac** [comment]
Looks good so far. Do we expect to track any properties of the icon, e.g. format, size, aspect ratio?

**Comment by pinussilvestrus** [comment]
I'd assume not, so far. Correct me if I'm wrong @MaxTru @christian-konrad

**Comment by pinussilvestrus** [comment]
I think we are ready to merge this, right? Since icons are already integrated 👍

**Pull request merged**
