### PR TITLE
chore: load axe-devtools extension in dev mode

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/bpmn-io/internal-docs/issues/892

### CODE REVIEW

**Comment by barmac** [comment]
Axe doesn't work yet, but at least the React extension is up again.

image
image

**Review by nikku — APPROVED** [review]

**Comment by barmac** [comment]
> We could also try installing WAVE; it’s not the recommended tool, but if it works in Chromium, we can at least get started.

**Comment by barmac** [comment]
I checked WAVE but it's not available in the devtools but you need to click the icon which is unavailable in the Modeler: https://chromewebstore.google.com/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh?pli=1

**Comment by barmac** [comment]
Idea: Instead of trying to make devtools work, use `axe-core` to generate a report. This could be a Modeler plugin.

**Comment by barmac** [comment]
I got the axe-devtools extension running. To make it load the URL correctly, you need to reload the application window once. Have a look at the recording below:


Uploading Screen Recording 2024-05-22 at 12.11.11.mov…

**Comment by barmac** [comment]
Together with @lmbateman, we've struggled with getting this to work. It looks that the latest distribution of the extension does not work with Electron due to missing manifest v3 support. If the extension does not load on your machine, you may need replace the files at `~/Library/Application\ Support/camunda-modeler/chrome-extensions` (or respective directory on your OS) with the attachment.
[axe.zip](https://github.com/camunda/camunda-modeler/files/15404615/axe.zip)

**Comment by nikku** [comment]
Verified that installation via manual procedures (https://github.com/camunda/camunda-modeler/pull/4247#issuecomment-2124921586) worked for me on Linux :heavy_check_mark:

**Pull request merged**
