### PR TITLE
Housekeeping: integrate library changes

### LINKED ISSUE #3510: Resolver suggests not yet defined variables
### Describe the bug

Right now completion suggests the variable that I'm currently writing, and other variables that may not yet have been written to me:

image

### Steps to reproduce

1. Open [`test.bpmn`](https://github.com/bpmn-io/variable-resolver/files/10978847/test.bpmn.txt)
1. Select task
2. Complete on input variables `foo` and `bar`
3. See that the variable itself, but also the variable that has not been written yet (`bar` if you complete on `foo`) is suggested

### Expected behavior

Only actually available variables are completed.

### Environment

- OS: any
- Camunda Modeler Version: 5.9.0
- Execution Platform: Camunda Cloud
- Installed plug-ins: None

### Additional context

_No response_

### LINKED ISSUE #3807: Be able to define collapsed by default groups in an element template
### Problem you would like to solve

Consider any connectors element template, i.e. [HTTP REST](https://github.com/camunda/connectors/blob/main/connectors/http/rest/element-templates/http-json-connector.json).

All properties are structured within _Groups_. All groups are _expanded_ by default. Requesting to add a flag to the `group` element that would indicate that a specific _group_ is collapsed by default.

### Proposed solution

The following construct should make _My Collapsed Group_ collapsed by default:

```
"groups": [
    {
      "id": "myCollapsedGroup",
      "label": "My Collapsed Group",
      "collapsedByDefault": true
    },
...
]
```

### Alternatives considered

Since our use-case is [epic-related](https://github.com/camunda/product-hub/issues/1363), we could dedicate one specific group for the task definition type property and hardcode it being collapsed by default but I would not recommend taking this route.

### Additional context

Via discussion: https://camunda.slack.com/archives/CKGH9LR40/p1693222832075709?thread_ts=1692785474.018059&cid=CKGH9LR40.

This FR is related to the [epic](https://github.com/camunda/product-hub/issues/1363), and is a feature gap related to the epic. See related [explanation](https://camunda.slack.com/archives/CKGH9LR40/p1693221008941389?thread_ts=1692785474.018059&cid=CKGH9LR40).

### LINKED ISSUE #3876: FEEL popup editor does not integrate well with validation
### Describe the bug

The FEEL popup editor at this stage does not properly integrate with validation, showing the following issues:

* The error outline is shown on the disabled element, albeit only partially
* The error is not shown inside the editor itself, making it harder for the user to recognize it.

image

### Steps to reproduce

1. Open a FEEL input
2. Enter an invalid expression, i.e. `FOO\nBAR`
3. Open popup editor, see :arrow_up: screen

### Expected behavior

* The error outline is completely shown, also on disabled field.
* (optional) An error is shown inside the editor as well, especially given that very detailed errors may be specified.

### Environment

- OS: Any
- Camunda Modeler Version: v5.16.0-dev
- Execution Platform: Any
- Installed plug-ins: None

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marstamm**
- bpmn-js-element-templates@1.6.0
- bpmn-js-properties-panel@5.6.0
- camunda-bpmn-js@3.6.0

closes #3876, closes #3510, closes #3807

### CODE REVIEW

**Comment by barmac** [comment]
I don't know why but I cannot `npm install` in `camunda-modeler` right now :/

**Comment by marstamm** [comment]
That's strange, it works on my machine. CI also seems to be okay as well

**Comment by barmac** [comment]
I discovered I was on npm@9. Trying out npm@10 right now and it seems to progress.

**Comment by barmac** [comment]
And it failed. Trying out npm@8.

**Comment by barmac** [comment]
Oh ok it's chromium and apple chip:

```
npm ERR! code 1
npm ERR! path /Users/maciej/workspace/bpmn-io/camunda-modeler/client/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with:
npm ERR!
npm ERR!  sudo apt install chromium
npm ERR!
npm ERR!
npm ERR!  sudo apt install chromium-browser
npm ERR!
npm ERR! /Users/maciej/workspace/bpmn-io/camunda-modeler/client/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115
npm ERR!                     throw new Error();
npm ERR!                     ^
npm ERR!
npm ERR! Error
npm ERR!     at /Users/maciej/workspace/bpmn-io/camunda-modeler/client/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:115:27
npm ERR!     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR!
npm ERR! Node.js v20.7.0
```

**Comment by barmac** [comment]
OK I discovered the issue. For some reason I had an old branch called `update-properties-panel` on my machine, and `gh` checked it out instead of your PR.

**Comment by barmac** [comment]
It looks like the syntax error is still not quite there:

https://github.com/camunda/camunda-modeler/assets/28307541/8860574a-595b-4ed6-8e0c-d8aa89a8ff31

The outline looks OK though.

**Review by barmac — APPROVED** [review]

**Comment by marstamm** [comment]
> syntax error is still not quite there

This looks like a clash of local and global validation, which we also sometimes have in the collapsed editor 🤔

Still better than the broken outline

**Comment by nikku** [comment]
@marstamm Could you take over incorporating this into web modeler, too? As I understood this fixes some [nasty issues](https://camunda.slack.com/archives/CKGH9LR40/p1697717361863099).

**Comment by marstamm** [comment]
I can bump the dependencies in web-modeler as well

**Pull request merged**
