### PR TITLE
deps: update to dmn-js@16.7.1

### LINKED ISSUE #4342: Literal expression editor body has small hitbox
### Describe the bug

In an empty literal expression editor, I need to select the first line to get keyboard focus

Recording 2024-06-06 at 10 38 04

### Steps to reproduce

1. Open a literal expression editor
2. Click around in the function body
3. If you do not hit the first line, Keyboard focus is lost/not achieved

### Expected behavior

I can click anywhere and the cursor gets positioned at the end of the file

### Environment

 * Version: 5.24.0-rc.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: DMN - Camunda 8

### Additional context

The cursor also suggests that I can click anywhere to edit

[SUPPORT-23549](https://jira.camunda.com/browse/SUPPORT-23549)

### PR DESCRIPTION
**Pull request by jarekdanielak**
Closes #4342

### Proposed Changes

Make literal expression editor take full height of its container, effectively allowing text area to focus when clicking anywhere on the editor, not only on the text lines.

https://github.com/user-attachments/assets/e18cc810-59f2-418b-85a1-95b3b7ce8cb6

 

### Checklist

To ensure you provided everything we need to look at your PR:

* [X] __Brief textual description__ of the changes present
* [X] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [X] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
Let's make sure we also update [camunda/camunda-dmn-js](https://github.com/camunda/camunda-dmn-js/).

**Comment by jarekdanielak** [comment]
> Let's make sure we also update [camunda/camunda-dmn-js](https://github.com/camunda/camunda-dmn-js/).

👍 https://github.com/camunda/camunda-dmn-js/pull/123

**Review by barmac — APPROVED** [review]
Fantastic!

**Comment by barmac** [comment]
Likely this is related to https://stackoverflow.com/questions/46997189/why-height-100-doesnt-work

**Comment by nikku** [comment]
Let's create a relevant follow-up for BKM. I'm merging this PR.

**Pull request merged**
