### PR TITLE
chore: simplify link-dependencies task

### PR DESCRIPTION
**Pull request by barmac**
Use `yarn link` without additional scripts for diagram-js and bpmn-js.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
Any reason we still handle dmn-js and form-js differently?

**Comment by barmac** [comment]
They are monorepos, so plain `yarn link` won't work there. We can probably improve linking of those libraries, but it's additional work.

**Comment by barmac** [comment]
One step at time :)

**Comment by nikku** [comment]
What I propose (instead of linking) is to facilitate [`npm override`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides), using core (on board) facilities.

**Comment by barmac** [comment]
Sure, we could try this out. Last time I checked I wasn't able to get it to work, but it was long time ago.

**Pull request merged**
