### PR TITLE
Integrate form-js v0.3.0

### PR DESCRIPTION
**Pull request by philippfromme**
Integrates form-js v0.3.0 into the Camunda Modeler.

### Changes

* form editor instances are reused
* import is asynchronous
* undo and redo is supported
* ensure async tests are working (cf. https://github.com/bpmn-io/hour-of-code/blob/master/snippets/CamundaModelerAsyncTest.md)

### CODE REVIEW

**Review by nikku — COMMENTED** [review]
Found an issue that may very well be a core form-js issue: If you undo and redo the selection does not properly change on element deletion:

capture 2QemOF_optimized

Fine to merge it right now if we have a clear plan to fix it in upcoming form-js versions.

**Comment by philippfromme** [comment]
@nikku Good finding. This is indeed an issue with form-js. Something that we can fix with https://github.com/bpmn-io/form-js/pull/140. A v0.3.1 could bring this fix to the Camunda Modeler.

**Comment by nikku** [comment]
Please don't forget to include `Closes #issueNr` in the bump commit for _fixed upstream_ addressed by the version bump.

Also: Consider updating the form-js version via `deps: ...`.

**Comment by philippfromme** [comment]
@nikku I've gone ahead and merged this as the selection issue will be fixed with https://github.com/bpmn-io/form-js/pull/140.

**Pull request merged**
