### PR TITLE
fix: correct feel error css

### PR DESCRIPTION
**Pull request by marstamm**
Uses the correct CSS and sets the complete border to red

Old:
image

New:
image

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
That should go to `master`, right?

**Comment by marstamm** [comment]
Yes, I changed it 👍

**Review by pinussilvestrus — APPROVED** [review]
Works 🏁

**Comment by marstamm** [comment]
I was wondering why it said "merge failed" until I refreshed the page and you already did it 😄

**Comment by pinussilvestrus** [comment]
You were quicker than GitHub's page updater 😄

**Pull request merged**
