### PR TITLE
deps: update @camunda/linting to v0.9.1

### LINKED ISSUE #3148: Show version that enables the feature if not supported in currently selected version
### Problem you would like to solve

When using properties that are not supported in the currently selected platform version (e.g. Camunda Platform 8.0), the only statements I get from error messages is that the field is not supported (by Camunda 8):

image
### Proposed solution

I would like to see the version which makes the desired property available, if available. The error message should clearly state the minimum target that supports the feature:

```
[...] is only supported by Camunda Platform 8.1 or newer
```

In case we don't know yet when to support it, it should show:  
```
[...] is not supported by <Platform version>
```

This gives me as a user some insight on the evolution of the capabilities I have available to design and enhance my process.

Also, marking properties that are not available in the current version would help to sort out quickly what I can actually do.

### Alternatives considered

As an alternative, not available options could be filtered out.

Pro: Cleaner working environment

Con: No awareness of features in newer versions.

### Additional context

With regards to the evolution of Camunda 8, it would make sense to raise awareness of feature evolution and not leaving a user with a simple "Not supported" which is frustrating.

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #3148

### CODE REVIEW

**Review by barmac — COMMENTED** [review]
Something is wrong with this:
image

It should say `Zeebe 1.0.0`.

**Comment by philippfromme** [comment]
> Something is wrong with this:

I'll look into this.

**Comment by marstamm** [comment]
@philippfromme 

It looks like the util needs to cast the PlatformVersion to Minor before doing the label translation
https://github.com/camunda/linting/blob/main/lib/utils/error-messages.js#L28-L42

**Comment by philippfromme** [comment]
> @philippfromme
> 
> It looks like the util needs to cast the PlatformVersion to Minor before doing the label translation https://github.com/camunda/linting/blob/main/lib/utils/error-messages.js#L28-L42

Yes, we do this in other places but I forgot it here. 🙈

**Comment by marstamm** [comment]
And I missed it in the review 🙉

**Comment by philippfromme** [comment]
Updated `@camunda/linting` to v0.9.1 which fixes the issue with the execution platform label.

image

**Review by barmac — APPROVED** [review]

**Pull request merged**
