### PR TITLE
Update DRD editing to new diagram-js foundations

### LINKED ISSUE #1669: Update DRD editing features to same level like BPMN
__What should we do?__

* [ ] Pull in released `dmn-js@7.3` that ships with latest bpmn.io editing features (snapping, grid-snapping, alignment and distribution)
* [ ] Add alignment and distribution buttons similar to bpmn-js to allow users to organize their diagrams

__Why should we do it?__

Potential easy pick to improve DRD editing in the tool significantly.

### LINKED ISSUE #1679: DMN XML not correctly updated when changing IDs of Tables
__Describe the Bug__

When changing IDs of Tables in a DMN, the relations get lost on the diagram but remain in the XML.

__Steps to Reproduce__

SUPPORT-7040 (2)

__Expected Behavior__

When changing the IDs of an element, all relations get updated correctly.

__Environment__

- Camunda Modeler Version: all versions 
---

Related to [SUPPORT-7040](https://jira.camunda.com/browse/SUPPORT-7040)

```

### PR DESCRIPTION
**Pull request by nikku**
Closes #1669 
Closes #1679

### CODE REVIEW

**Comment by nikku** [comment]
Rebased on top of `develop`.

**Comment by barmac** [comment]
> Rebased on top of `develop`.

Are you willing to add any test coverage to this?

**Comment by nikku** [comment]
I've added a test in the same style like we test things in our BPMN tooling: https://github.com/camunda/camunda-modeler/pull/1689/files#diff-942aa455562c2c6de0b299b240871fc2R606

If you ask me, whether I'm willing to add additional tests: For me personally, that is good enough :wink:.

**Comment by barmac** [comment]
👍

**Pull request merged**
